### ISSUE TITLE
Implement press release & "in the news" overview pages

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#10]
- [ ] setup index containing the press release & in the news docs, index the template field
- [ ] create separate, filtered sheets for press releases & in the news entries
- [ ] implement "list block" used on both pages, with pre filtering config in the doc for types to be displayed

See Press Releases: https://www.moleculardevices.com/newsroom/news
See in the news: https://www.moleculardevices.com/newsroom/in-the-news

**Comment by lydiapuric** [comment]
WIP in https://github.com/hlxsites/moleculardevices/tree/publication-overview
