### ISSUE TITLE
Customer breakthrough should not be full width on this page

### ISSUE THREAD

**Issue by alexcarol** [hlxsites/moleculardevices#1004]
https://franklin.moleculardevices.com/technology/time-resolved-fluorescence-trf-tr-fret-htrf#overview

![](https://user-images.githubusercontent.com/138755144/257439871-7fe5726a-1dab-49f9-a8c0-7f7993bc5b18.png)

**Comment by MeghnaTewari** [comment]
@duynguyen  To main consistency, wherever this styling is coming for customer breakthroughs the image should be on the left and the text on the right. Please update the same on this page. https://franklin.moleculardevices.com/technology/time-resolved-fluorescence-trf-tr-fret-htrf#overview
Also, the color for the "Customer Breakthroughs" title looks a bit off, please check that too. 

styling should be like this example on Franklin - 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/47017e8e-b3dc-420a-8444-74a6f57f2c3f)
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers

**Comment by alexcarol** [comment]
> @duynguyen To main consistency, wherever this styling is coming for customer breakthroughs the image should be on the left and the text on the right. Please update the same on this page. https://franklin.moleculardevices.com/technology/time-resolved-fluorescence-trf-tr-fret-htrf#overview Also, the color for the "Customer Breakthroughs" title looks a bit off, please check that too.
> 
> styling should be like this example on Franklin - ![image](https://user-images.githubusercontent.com/138755144/258105321-47017e8e-b3dc-420a-8444-74a6f57f2c3f.png) https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers

Done, this is the fix: https://issue-1004--moleculardevices--hlxsites.hlx.page/technology/time-resolved-fluorescence-trf-tr-fret-htrf
