### ISSUE TITLE
Request pricing CTA issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1015]
[Issues after the transfer.docx](https://github.com/hlxsites/moleculardevices/files/12258867/Issues.after.the.transfer.docx)

Customers have reported issues with the "Request Pricing" button. I've attached the document they shared. Please fix it.

**Comment by lydiapuric** [comment]
Addressed CTA buttons
1. https://www.moleculardevices.com/products/axon-patch-clamp-system
2. https://www.moleculardevices.com/products/axon-patch-clamp-system/amplifiers/axon-instruments-patch-clamp-amplifiers
Note: View Media Gallery is still shown, however as a secondary button
3. https://www.moleculardevices.com/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer
Note: View Media Gallery is still shown, however as a secondary button
4. https://www.moleculardevices.com/products/axon-patch-clamp-system/acquisition-and-analysis-software/pclamp-software-suite
5. https://www.moleculardevices.com/products/flipr-penta-high-throughput-cellular-screening-system/screenworks-software

**Comment by MeghnaTewari** [comment]
@lydiapuric 

1. For this page, **Request pricing and Download Ebook** should be visible for US and EU, replace view products with Download Ebook ( No changes for other regions ) 

https://www.moleculardevices.com/products/axon-patch-clamp-system

2.  For these 2  pages, only **Request pricing** CTA should be visible for US and EU. Secondary buttons are not required  ( No changes for other regions ) 
https://www.moleculardevices.com/products/axon-patch-clamp-system/amplifiers/axon-instruments-patch-clamp-amplifiers
https://www.moleculardevices.com/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer

I know this is a bit confusing :sweat_smile:

**Comment by lydiapuric** [comment]
@MeghnaTewari Looking at the german page, I can see View Products as 2nd button of https://www.moleculardevices.com/products/axon-patch-clamp-system
And not Download Ebook. So this will not match because buttons will not be ordered differently by country.


Because the secondary button is not required, it sounds for me it can be still displayed. Can you confirm?

**Comment by MeghnaTewari** [comment]
@lydiapuric Not sure if I follow 

https://www.moleculardevices.com/products/axon-patch-clamp-system

1. But for other regions, the CTA should be View products and Download eBook for this page ( Which is right currently ) 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ec4540a8-b752-47a1-8c1f-55513e1476b1)

2. And for the US and EU regions "View products" should be replaced by Request pricing CTA, so it should show the 2 buttons i.e Request pricing and Download ebook

Please let me know if you have further questions

**Comment by MeghnaTewari** [comment]
And for these 2 pages, we need to just display a single CTA which is Request pricing 

https://www.moleculardevices.com/products/axon-patch-clamp-system/amplifiers/axon-instruments-patch-clamp-amplifiers
https://www.moleculardevices.com/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer

**Comment by lydiapuric** [comment]
Size of virtual demo adjusted in:
1. https://www.moleculardevices.com/products/axon-patch-clamp-system
2. https://www.moleculardevices.com/products/axon-patch-clamp-system/acquisition-and-analysis-software/pclamp-software-suite

**Comment by MeghnaTewari** [comment]
@lydiapuric Please let me know when these are fixed 

> @lydiapuric Not sure if I follow
> 
> https://www.moleculardevices.com/products/axon-patch-clamp-system
> 
> 1. But for other regions, the CTA should be View products and Download eBook for this page ( Which is right currently )
>    ![image](https://user-images.githubusercontent.com/138755144/258430586-ec4540a8-b752-47a1-8c1f-55513e1476b1.png)
> 2. And for the US and EU regions "View products" should be replaced by Request pricing CTA, so it should show the 2 buttons i.e Request pricing and Download ebook
> 
> Please let me know if you have further questions



> And for these 2 pages, we need to just display a single CTA which is Request pricing
> 
> https://www.moleculardevices.com/products/axon-patch-clamp-system/amplifiers/axon-instruments-patch-clamp-amplifiers https://www.moleculardevices.com/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer

**Comment by lydiapuric** [comment]
@MeghnaTewari thanks for summarizing the missing parts. Starting addressing it now...

**Comment by lydiapuric** [comment]
@MeghnaTewari See single CTA button for Request pricing
https://1015-cta--moleculardevices--hlxsites.hlx.page/products/axon-patch-clamp-system/amplifiers/axon-instruments-patch-clamp-amplifiers
https://1015-cta--moleculardevices--hlxsites.hlx.page/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer

**Comment by lydiapuric** [comment]
https://de.moleculardevices.com/products/axon-patch-clamp-system
@MeghnaTewari In the german version the buttons are Request Pricing (Preise anfordern) + View Products (Produkte ansehen).
Why in the com version you would expect the Download eBook as 2nd button and not the View Products button?

**Comment by MeghnaTewari** [comment]
@lydiapuric  

I think it was working wrong on the old site as well.

Just found a comment from the past discussion.  Please check 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/51de568e-0eb5-44e7-b4d8-abb83454e0f0)
