### ISSUE TITLE
Add anchor link on the CTA

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1016]
1. Add anchor link on "View Products" CTA in the banner. The link should  to this section 

https://www.moleculardevices.com/products/axon-patch-clamp-system

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5b7bf394-871f-46a7-ab3e-358041b0ce79)

2. Fix application menu links. These links should go to the application landing page with pre-selected filters.
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7d2f0c71-dd39-43e9-8714-fab3a7c7612a)

Example- This should go to - https://www.moleculardevices.com/applications#COVID-19
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/537514b7-aba4-4067-a996-7f028a750912)

**Comment by duynguyen** [comment]
@dev-rajneeshkumar I fixed 1. do you want to take over to do the content changes for 2?

**Comment by dev-rajneeshkumar** [comment]
Sure @duynguyen  but first I need to have a walkthrough how these bookmark links are working. Let me take a look how you fixed 1st one then will get back to you if needed

**Comment by duynguyen** [comment]
Megamenu docs have been shared in Slack.
Basically for the anchor links, you need to grab the ID of the title (e.g. H2) you want to link to. Then modify the link to have the own page URL + '#' + ID link.

**Comment by dev-rajneeshkumar** [comment]
Thanks @duynguyen 
@dev-rajneeshkumar Application submenu links has been fixed now!

**Comment by duynguyen** [comment]
@MeghnaTewari have you verified all fixes? can we close this issue now?

**Comment by MeghnaTewari** [comment]
Yes, @duynguyen  Please close this issue.
