### ISSUE TITLE
Fix publication icon in search

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1022]
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/76bda564-6bc3-4276-b56c-e19a7d9b6414)

https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=[Publication]

Please replace the blog icon for publication with the document icon.

**Comment by andreituicu** [comment]
@MeghnaTewari This is now fixed. Thank you!

**Comment by MeghnaTewari** [comment]
Thanks! Looks good.
