### ISSUE TITLE
Apply character limit in the resources description 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1024]
https://www.moleculardevices.com/applications/3d-cell-models/organoids/intestinal-organoids#resources

Please apply a character limit in the resource description. The limit should be up to 230 characters globally.

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ccc97b9f-46e5-41a7-8c23-1101f307ed59)

**Comment by lydiapuric** [comment]
@MeghnaTewari Please verify fix in https://1024-resources--moleculardevices--hlxsites.hlx.page/applications/3d-cell-models/organoids/intestinal-organoids#resources

**Comment by MeghnaTewari** [comment]
@lydiapuric  Looks good! Please merge
