### ISSUE TITLE
Fix caption style and UI issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1031]
https://www.moleculardevices.com/applications/synthetic-biology

Facing a couple of issues- 

1. Unable to update the caption font size to 14 px under this video.
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/363df755-eda3-4b4c-ad65-be3ca8e9d40a)

2. This image size needs to be reduced so that there is no extra space above the 3rd bullet
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3a0ac59e-4890-4817-9b3b-60af21f28712)

Like this- 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a2271913-f895-4a06-b193-90ac25dcb51b)

3. Need to make view the video CTA outlined
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b2f9d6df-3aa5-47e9-bccd-7ce5fb759c91)

4. Not able to reduce the extra space coming for certain sections

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/779e4613-f43c-4f79-a229-afca5a014575)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ec778cd4-3c8a-4466-93fe-20d71381cc23)

You can check the appropriate spacing for this page on this URL- https://1-md30.pantheonsite.io/applications/synthetic-biology

**Comment by duynguyen** [comment]
@MeghnaTewari number 2 is fixed, can you check?
What I did: added `Image Figure Large` style to the columns block where the image is in. That limits the image width to 75%.
If you want 50%, add `Image Figure` style instead.

**Comment by MeghnaTewari** [comment]
Thanks for explaining @duynguyen

**Comment by MeghnaTewari** [comment]
> https://www.moleculardevices.com/applications/synthetic-biology
> 
> Facing a couple of issues-
> 
> 1. Unable to update the caption font size to 14 px under this video.
>    ![image](https://user-images.githubusercontent.com/138755144/259104968-363df755-eda3-4b4c-ad65-be3ca8e9d40a.png)
 
@alinarublea This issue is still not fixed.

**Comment by MeghnaTewari** [comment]
Please remove one line space here

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/10bbd902-d6a7-455e-b5c0-383fdf132d30)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d922fee0-f737-4e20-8ca3-e83af9a9caaf)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8228119b-ed6d-4965-88e4-6d0a447a21e4)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3216aa91-75a6-4bb2-b6ee-af2801daefad)

**Comment by alinarublea** [comment]
Yes, of course to resolve the spaces issues you need to add a section metadata table inside the section and add (No padding top, No padding bottom) if you want to eliminate space from both, or only one of them if you want to eliminate spece from just one

Section Metadata
--
style | No padding top, No padding bottom

**Comment by MeghnaTewari** [comment]
Thanks! @alinarublea

**Comment by MeghnaTewari** [comment]
@alinarublea Please update when these are done and let me know the solution as well.


> Thanks! @alinarublea We are able to remove the extra spaces in most of the places now but for unable to remove them from these sections.
> 
> > Please remove one line space here
> > ![image](https://user-images.githubusercontent.com/138755144/259378461-10bbd902-d6a7-455e-b5c0-383fdf132d30.png) ![image](https://user-images.githubusercontent.com/138755144/259378917-3216aa91-75a6-4bb2-b6ee-af2801daefad.png) ![image](https://user-images.githubusercontent.com/138755144/259385832-27cc59e8-8da1-4318-bee5-d24dfd589540.png)

**Comment by MeghnaTewari** [comment]
@alinarublea any update on this?

**Comment by MeghnaTewari** [comment]
@alinarublea any update on this? 
@duynguyen could you please help us with the spacing? how we can remove spaces from the places that I have mentioned. 

https://www.moleculardevices.com/applications/synthetic-biology

> Thanks! @alinarublea We are able to remove the extra spaces in most of the places now but for unable to remove them from these sections.
> 
> > Please remove one line space here
> > ![image](https://user-images.githubusercontent.com/138755144/259378461-10bbd902-d6a7-455e-b5c0-383fdf132d30.png) ![image](https://user-images.githubusercontent.com/138755144/259378917-3216aa91-75a6-4bb2-b6ee-af2801daefad.png) ![image](https://user-images.githubusercontent.com/138755144/259385832-27cc59e8-8da1-4318-bee5-d24dfd589540.png)

**Comment by alinarublea** [comment]
@MeghnaTewari I am back today after finishing my oncall shift and will resume working on it

**Comment by alinarublea** [comment]
@MeghnaTewari can you check on https://issue-1031--moleculardevices--hlxsites.hlx.page/applications/synthetic-biology, I made the changes

**Comment by MeghnaTewari** [comment]
@alinarublea Please add one line spacing here, it is looking too less now

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/93622998-e8fe-4569-9b5b-19e09932dbce)

**Comment by alinarublea** [comment]
Yes, this one required code changes

**Comment by alinarublea** [comment]
@MeghnaTewari I hope I got it right this time

**Comment by MeghnaTewari** [comment]
@alinarublea Looks good now.
