### ISSUE TITLE
Fix "null with the vertical line" issue, globally

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1040]
Example URL- 

https://www.moleculardevices.com/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging
https://www.moleculardevices.com/en/assets/tutorials-videos/dd/img/automation-high-content-imaging-for-organoid-research

**Comment by duynguyen** [comment]
@MeghnaTewari - have you found this issue only on tutorials-videos pages or other sections as well?

**Comment by MeghnaTewari** [comment]
@duynguyen  Till now I have only seen this issue on tutorial videos resource pages where the banner image is coming. I am checking other pages as well and I will update if I see it on other pages as well.

**Comment by MeghnaTewari** [comment]
Sure @duynguyen Sending you the list.

**Comment by duynguyen** [comment]
I have fixed the 2 pages you reported originally.
The fix is straightforward, you can also do it yourself in Sharepoint:
- remove the table column that contains the `null`
- preview the document, make sure the updated page looks good
- publish the page

**Comment by MeghnaTewari** [comment]
Thanks, @duynguyen Will do.

Another issue that I have noticed is that on these pages the title font size is very large. Should be 36 px and in blue color.
How can we fix this globally? There are around 35 pages.

https://www.moleculardevices.com/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f4d64328-2281-4890-adf6-a06ecded6064)

**Comment by duynguyen** [comment]
@MeghnaTewari so all tutorial videos pages should have smaller and blue title? or only a subset of them?

**Comment by MeghnaTewari** [comment]
@duynguyen  No, not all of them. This styling is only implemented for video resources for landing pages.

Like this one-  
https://www.moleculardevices.com/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging

To distinguish such resources, they have a wave and a banner image, so on those pages, the body title should be 36 px and blue. Also the label "ON-DEMAND WEBINAR" should be blue.

For video resource pages that are created for tagging (having the default blue banner), no changes on those. 
Example - https://www.moleculardevices.com/en/assets/tutorials-videos/bpd/colony-picking-automation

**Comment by duynguyen** [comment]
@MeghnaTewari is it all clear to you in this issue (null column), and you can update the content yourself? closing it here, please lmk if you have more questions.

**Comment by MeghnaTewari** [comment]
Yes, @duynguyen. We have fixed this issue on all the pages. Thanks.
