### ISSUE TITLE
[Videos Resources] Title style below wave hero

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#1044]
This styling is only implemented for video resources for landing pages.

Like this one-
https://www.moleculardevices.com/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging

To distinguish such resources, they have a wave and a banner image, so on those pages, the body title should be 36 px and blue. Also the label "ON-DEMAND WEBINAR" should be blue.

For video resource pages that are created for tagging (having the default blue banner), no changes on those.
Example - https://www.moleculardevices.com/en/assets/tutorials-videos/bpd/colony-picking-automation

**Comment by MeghnaTewari** [comment]
@duynguyen So it means we need to fix each page manually? I have a list of 35 URLs where we need to make these changes.

Also, can we make the title 36px? it is 40 px right now and make the label "ON-DEMAND WEBINAR" blue.

**Comment by duynguyen** [comment]
solution for content only update: add the "Section Metadata" table above the Metadata table, and apply the style `Blue Title, Product Titles`.

**Comment by duynguyen** [comment]
@MeghnaTewari if the rule of "blue and font size of 36px" body title applies to pages meeting these criteria:
- "videos and webinars" resources page
- following a wave hero section

then we might be able to do it globally in the code. Can you confirm?

**Comment by MeghnaTewari** [comment]
@duynguyen Yes, I can confirm that.

Just make sure we don't apply that styling to pages with the default blue banner like  - https://www.moleculardevices.com/en/assets/tutorials-videos/bpd/colony-picking-automation

For your reference, here is the list of videos and webinar pages that need to be fixed.
[videos and webinars pages.xlsx](https://github.com/hlxsites/moleculardevices/files/12303497/videos.and.webinars.pages.xlsx)

**Comment by duynguyen** [comment]
> Just make sure we don't apply that styling to pages with the default blue banner like - https://www.moleculardevices.com/en/assets/tutorials-videos/bpd/colony-picking-automation

correct, this has no wave hero banner hence the rule does not apply.

**Comment by MeghnaTewari** [comment]
Correct!

**Comment by duynguyen** [comment]
@MeghnaTewari can you verify the fix here?
https://1044--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging

Also checked a few other pages in your excel (except the null issue which has to be fixed in content):
https://1044--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/imaging-challenges-for-transitioning-high-content-assays-to-3d
https://1044--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/accelerate-your-screening-with-high-content-and-automated-imaging

The non wave version is kept as before: https://1044--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/bpd/colony-picking-automation

**Comment by MeghnaTewari** [comment]
@duynguyen  Looks great! Thank you
