### ISSUE TITLE
Please implement dynamic tagging approach in on thank you page resources

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1049]
Please implement dynamic tagging approach in on thank you page resources carousel .  Right now they are being contributed from document only but they are common resources so should be changes at one place only.

https://www.moleculardevices.com/en/assets/app-note/dd/img/high-throughput-modeling-inflammatory-bowel-disease-using-human-intestina-organoids?page=thankyou

![image](https://github.com/hlxsites/moleculardevices/assets/42608830/a692042b-3b1e-4765-956a-b39b75084626)

![image](https://github.com/hlxsites/moleculardevices/assets/42608830/465dca72-bdc8-483d-8ee9-e7e82c8e3d5a)

@andreituicu has more context about it.

Thanks,
Rajneesh

**Comment by andreituicu** [comment]
What I discussed with @dev-rajneeshkumar is that what would work for him is a carousel with links to the pages that dynamically retrieves the:
* image
* title
* description
* type

and constructs the carousel with this information.

We might have this already so please check before writing the code if any of the existing carousels would work for this.

**Comment by duynguyen** [comment]
where would those "highlighted resources" be tagged then? as metadata on the page? how about tagging some resources that are files and don't have doc?
