### ISSUE TITLE
Fix regional contacts  issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1055]
https://www.moleculardevices.com/contact-search?country=United%20States&product_family=

- [x] 1. No results styling is applied for a few countries

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/186da3d2-493a-4e3a-b89d-5376a6eef200)

- [x] 2. Add an arrow icon after Contact CTA for all the regions

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a1fc691d-21e7-4c3b-9472-d4f5b4b95b09)

- [x] 3. The external icon is missing on regional contacts

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c88f6d98-7b03-4523-88a7-a92ab6c95a36)

- [x] 4. Remove this duplicate text 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d59efef7-8a7e-46bd-8cee-325e219d75cc)

- [x] 5. Website links are missing for several countries because where there are values in both email and link columns, it only fetches the data from the email column. 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d6802571-dae0-4c8c-9cee-a6ea0db9dd87)

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/df97c911-1681-4958-9210-6ccbebcf13d4)

Please take reference from old live - https://live-md30.pantheonsite.io/contact-search?data=submit

**Comment by duynguyen** [comment]
@MeghnaTewari some comments:
1. `No results styling is applied for a few countries` can you please elaborate what it means?
2. we might fix it in code block
3. we might fix it in code block
4. You can update the content sheet at https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BF7AEBB0F-B58A-4A67-B032-F917F064E890%7D&file=local-distibutors.xlsx&action=default&mobileredirect=true - go to the US rows, delete the duplicate text, then preview and publish the sheet.
5. @dev-rajneeshkumar did you work on this block before and can quickly investigate?

**Comment by MeghnaTewari** [comment]
> 
> 1. `No results styling is applied for a few countries` can you please elaborate what it means?

@duynguyen The styling should be like this

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/226e91f5-9fe9-445a-9d1d-ff6100c40884)

**Comment by alexcarol** [comment]
Regarding "1. No results styling is applied for a few countries", I saw that it was happening for india, the issue was due to a line that contained "British Indian Ocean Territory (the)" as a country, but nothing else. The fix was as simple as removing it, are there any more countries with this issue?

**Comment by MeghnaTewari** [comment]
@alexcarol Yes I think this issue is with a few other countries as well

Found this one 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b09a2219-b4c3-4f23-a51c-b6d03b2be7c9)

**Comment by alexcarol** [comment]
> @alexcarol Yes I think this issue is with a few other countries as well
> 
> Found this one ![image](https://user-images.githubusercontent.com/138755144/261549590-b09a2219-b4c3-4f23-a51c-b6d03b2be7c9.png)

Good catch, this actually shows that this feature is broken (it's showing "papua new guinea", rather than "guinea", I'll get right on that.

**Comment by alexcarol** [comment]
> @alexcarol Yes I think this issue is with a few other countries as well
> 
> Found this one ![image](https://user-images.githubusercontent.com/138755144/261549590-b09a2219-b4c3-4f23-a51c-b6d03b2be7c9.png)

Fix for the first issue:  https://github.com/hlxsites/moleculardevices/pull/1082

**Comment by MeghnaTewari** [comment]
@alexcarol Looks good! So is it fixed for all the countries now or do I need to check all for this issue?

**Comment by alexcarol** [comment]
> @alexcarol Looks good! So is it fixed for all the countries now or do I need to check all for this issue?

This issue is fixed for all countries. Let me know if you see any other errors with countries though (I checked a few, but couldn't check them all).

**Comment by alexcarol** [comment]
@MeghnaTewari  What's the logic to determine whether we show "online support request" or "Website: <url>"? My assumption is that the ones with the URL https://mdc.custhelp.com/app/ask should have "online support request" shown, and the rest should show "Website...", could you confirm?

> * [ ]  5. Website links are missing for several countries because where there are values in both email and link columns, it only fetches the data from the email column.
> 
> ![image](https://user-images.githubusercontent.com/138755144/260387454-d6802571-dae0-4c8c-9cee-a6ea0db9dd87.png)
> 
> ![image](https://user-images.githubusercontent.com/138755144/260387502-df97c911-1681-4958-9210-6ccbebcf13d4.png)
> 
> Please take reference from old live - https://live-md30.pantheonsite.io/contact-search?data=submit

**Comment by MeghnaTewari** [comment]
@alexcarol Correct.

**Comment by alexcarol** [comment]
@MeghnaTewari here's a PR fixing the rest of the issues: https://github.com/hlxsites/moleculardevices/pull/1086

**Comment by lydiapuric** [comment]
@MeghnaTewari Can you please re-verify in https://issue-1055--moleculardevices--hlxsites.hlx.page/contact-search

**Comment by MeghnaTewari** [comment]
@lydiapuric missed your comment

Just checked and found a few issues

1. There is inconsistency in the arrow icons after Contact your local Sales Team CTA, for some regions it shows and for some it doesn't. Check my screenshot for Albania
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/6daa01c5-50c9-49cc-bf5f-15cda48430e5)

2. Inconsistency in external icons as well
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c4054322-a1d0-41b4-8177-eae170f8612f)
 visible for some countries, example- US
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7d8de5b7-5943-4499-9eef-50013242fdcf)

3. Please fix the URL for this page
https://www.moleculardevices.com/contact-search?country=United%20States&product_family=

should be

https://live-md30.pantheonsite.io/contact-search?data=submit

**Comment by lydiapuric** [comment]
@MeghnaTewari I created issue #1123 to address your missing findings regarding regional contacts.

**Comment by MeghnaTewari** [comment]
Thanks!
