### ISSUE TITLE
Fix import issue for chat.moleculardevices

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1057]
Gated resources which have gated URLs such as  "https://chat.moleculardevices.com/" has not been imported into Franklin.

Example URL- https://chat.moleculardevices.com/confocal

**Comment by andreituicu** [comment]
The resources can be found here:

[3rd-party-gated-urls.xlsx](https://github.com/hlxsites/moleculardevices/files/12358094/3rd-party-gated-urls.xlsx)

**Comment by lydiapuric** [comment]
@duynguyen Question: After addressing all redirects (expected vs current) I can see now following redirect:
Source: /sites/default/files/en/assets/brochures/dd/img/imagexpress-confocal-ht-ai-imaging-system.pdf 
Destination: https://chat.moleculardevices.com/confocal
Does this mean that we should remove these redirects in future? For the moment I will leave them inside.

**Comment by MeghnaTewari** [comment]
@duynguyen  Description is missing wherever chat URLs are there 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/12a3a390-3438-4e70-801f-8fd035d473e5)

Example- https://www.moleculardevices.com/products/flipr-penta-high-throughput-cellular-screening-system#resources

**Comment by mhaack** [comment]
@MeghnaTewari the export sheet (https://github.com/hlxsites/moleculardevices/issues/1057#issuecomment-1680306725) does not contain any description. @andreituicu @dev-rajneeshkumar where is the sheet from?

**Comment by andreituicu** [comment]
@mhaack : @dev-rajneeshkumar provided it in a Slack thread: https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1692008336932299?thread_ts=1691763614.722459&cid=C04QNDDUADT

**Comment by dev-rajneeshkumar** [comment]
> @MeghnaTewari the export sheet ([#1057 (comment)](https://github.com/hlxsites/moleculardevices/issues/1057#issuecomment-1680306725)) does not contain any description. @andreituicu @dev-rajneeshkumar where is the sheet from?

@mhaack  Sheet in #1057 just contains high level information of the resources which were missed as requested by @andreituicu . Complete information for this particular flyer is already provided in  the export sheet  #5078 https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B4E302AAE-E3E0-4D51-BC7C-4A4E28BF0945%7D&file=moldev-resources-sheet-06232023.xlsx&action=default&mobileredirect=true 

![image](https://github.com/hlxsites/moleculardevices/assets/42608830/d144738d-1b47-4e3a-890a-241221e0e532)

**Comment by duynguyen** [comment]
@lydiapuric yes that's correct - the redirect is already there on old site. Hence we leave it as is.
@MeghnaTewari description should be available for the flyers now. The brochures have it already. Could you please check?
@dev-rajneeshkumar @mhaack @andreituicu what I did was importing the missing pages from the new sheet `3rd-party-gated-urls.xlsx` and added the metadata according to the export sheet. Those brochure rows (at path /node/xyz) are imported into /resources/brochure/ in sharepont.

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari description should be available for the flyers now. The brochures have it already. Could you please check?



Yes, looks fine.

**Comment by duynguyen** [comment]
thanks for checking @MeghnaTewari . Hence all resources in 3rd-party-gated-urls.xlsx should be imported.
[As mentioned in slack](https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1692203070253719?thread_ts=1691763614.722459&cid=C04QNDDUADT) to @dev-rajneeshkumar , one resource at URL https://live-md30.pantheonsite.io/en/assets/brochures/dd/img/imaging-solutions-to-answer-your-biological-questions got redirected to the chat URL, therefore no way to import the original page. On Franklin site, it is also redirected to the chat URL.
