### ISSUE TITLE
Search issue [ Make arrow icons consistent ] 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1059]
To maintain consistency, please either remove or add the arrows from all the filters 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/077de30a-5940-439a-bcfa-7a71186da83e)

**Comment by lydiapuric** [comment]
@MeghnaTewari @dev-rajneeshkumar 
These arrows come from Coveo itself and are set dynamically when the entry is a leaf and contains another entry group inside.
Checking documentation and code, I don't find a way to change this behavior inside the Coveo facet / menu:
https://github.com/coveo/search-ui/blob/master/src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRenderer.ts#L64
Please correct me if I am wrong.

A possible implementation to hide all the arrows could be done via CSS.
