### ISSUE TITLE
Import missing Files or File Metadata

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#1066]
Files without metadata (these files are present in Sharepoint, but we don't have metadata for them, so they are not indexed by coveo):
- [x] /sites/default/files/en/assets/brochures/bpd/clonepix-2.pdf
- [x] /sites/default/files/en/assets/coa/reagents/clonedetect-human-igg-specific-fluorescein-k8200-cda0821a.pdf
- [x] /sites/default/files/en/assets/coa/reagents/clonematrix-k8510-mcw0921c.pdf
- [x] /sites/default/files/en/assets/coa/reagents/clonematrix-k8510-mcw0921d.pdf
- [x] /sites/default/files/en/assets/coa/reagents/clonematrix-k8510-mcw1021a.pdf
- [x] /sites/default/files/en/assets/coa/reagents/clonemedia-cho-growth-a-without-l-gln-k8840-99901210801.pdf
- [ ] /sites/default/files/en/assets/data-sheets/reagents/calcium-assays-for-the-flipr-system.pdf
- [ ] /sites/default/files/en/assets/infographics/dd/cns/patch-clamp-rig.pdf
- [x] /sites/default/files/en/assets/infographics/dd/img/history-of-organoid-research.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/br/high-throughput-igg-quantitation-platform-for-clone-screening-during-drug-discovery-development.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/br/multi-parametric-phenotypic-thp-1-cell-differentiation-and-cytokine-secretion-assay-for-evaluation-of-anti-inflammatory-compounds.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/flipr/complex-event-analysis-for-neurotoxic-profiling-on-human-ipsc-derived-neural-spheriod-3d-cultures.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/flipr/high-throughput-assessment-of-compound-induced-pro-arrhythmic-effects-in-human-ipsc-derived-cardiomyocytes.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/3d-imaging-and-analysis-of-angiogenesis-in-the-organ-on-a-chip-platform.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/ai-based-analysis-of-complex-biological-phenotypes.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/automated-3d-cell-based-assays-using-novel-flowchip-system-and-high-content-imaging.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/cell-migration-analysis-using-automated-cell-imaging.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/deep-learning-based-image-analysis-for-label-free-live-monitoring-of-ipsc-3d-organoid-cultures.pdf
- [x] /sites/default/files/en/assets/scientific-posters/dd/img/improving-robustness-of-cell-painting-with-near-infrared-label-and-advanced-image-and-data-analytics.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/live-cell-assays-measuring-complex-compound-effects-in-real-time.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/lung-organoids-as-an-assay-model-for-in-vitro-assessment-of-toxicity-effects-by-3d-high-content-imaging-and-analysis.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/measure-cell-migration-using-automated-cell-imaging-and-analysis.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/monitoring-organoid-development-and-characterization-of-calcium-oscillation-activities-in-ipsc-derived-3d-cerebral-organoids.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/multiplexed-assays-for-neurotoxicity-evaluation-using-neural-3d-cell-models.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/multiplexed-automated-imaging-assays-for-compound-testing-using-induced-pluripotent-stem-cell-derived-cells.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/multiplexed-automated-imaging-assays-for-compound-testing-using-ipsc-derived-cell-models.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/neurotoxicity-profiling-using-human-ipsc-derived-neural-spheroid-3d-cultures.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/novel-assay-methods-for-cancer-patient-derived-organoids.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/novel-high-throughput-solution-for-screening-drugs-with-versagel-3d-tumor-culture-model-and-high-content-imaging.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/organoids-for-disease-modeling-and-in-vitro-drug-screening.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/phenotypic-cell-based-assays-with-new-automated-imaging-system-and-cell-analysis-software.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/quantitative-analysis-of-cytotoxicity-using-ipsc-derived-stem-cells.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/simplified-workflow-for-phenotypic-profiling-based-on-the-cell-painting-assay.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/using-a-laser-light-source-for-high-content-automated-imaging-to-improve-sensitivity-speed-precision-for-complex-biological-assays.pdf
- [ ] /sites/default/files/en/assets/scientific-posters/dd/img/water-immersion-objectives-for-automated-high-content-imaging.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/flipr/screenworks-system-control-software-v5-1-4.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-installation-guide-5089268a.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-phenoglyphs-user-guide-5087398b.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-qr-protocol-design-5089273a.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-qr-select-view-image-data-5089274a.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-qr-view-classify-export-results-5089275a.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-sinap-user-guide-5087400b.pdf
- [x] /sites/default/files/en/assets/user-guide/dd/img/in-carta-volumetrics-user-guide-5087399b.pdf
- [ ] /sites/default/files/en/assets/white-paper/br/gxp-regulated-industry-assessments-of-microplate-readers.pdf
- [ ] /sites/default/files/en/assets/white-paper/br/gxp-regulated-industry-assessments-of-softmax-pro-software.pdf
- [ ] /sites/default/files/en/assets/publications/reagents/clonemedia-hek.pdf
- [ ] /sites/default/files/en/assets/publications/reagents/clonemedia-chok1sv.pdf
- [ ] /sites/default/files/en/assets/publications/reagents/hybridoma-clonemedia-reagent-guide.pdf
- [ ] /sites/default/files/en/assets/publications/bpd/industry-view-on-relative-importance-of-clonality-of-biopharmaceutical-producing-cell-lines.pdf
- [ ] /sites/default/files/en/assets/publications/bpd/clonepix-fl-and-intracellular-staining-facilitate-isolation-of-high-producer-cell-lines-for-monoclonal-antibody-manufacturing.pdf
- [ ] /sites/default/files/en/assets/publications/bpd/qpix-chroma-filter.pdf
- [ ] /sites/default/files/en/assets/publications/bpd/sequential-screening-by-clonepix-fl-and-intracellular-staining-facilitate-isolation-of-high-producer-cell-lines-for-monoclonal-antibody-manufacturing.pdf
- [ ] /sites/default/files/en/assets/publications/bpd/transcriptomics-based-drug-repositioning-pipeline-identifies-therapeutic-candidates-for-covid-19.pdf
- [ ] /sites/default/files/en/assets/app-note/br/detect-endotoxin-with-the-kinetic-qcl-kinetic-chromogenic-lal-assay.pdf

Files missing (both the file and the metadata is not present)
- [x] /sites/default/files/en/assets/presentations/dd/flipr/functional-and-mechanistic-neurotoxicity-profiling-using-human-ipsc-derived-neural-3d-cultures.ppsx

**Comment by duynguyen** [comment]
@dev-rajneeshkumar as discussed, we don't have the metadata for these files as they don't exist in the files export sheet. could you please verify?

**Comment by mhaack** [comment]
@andreituicu checked of a view as we found some issue with the export and could add a few of the missing one.

**Comment by mhaack** [comment]
Closing this as outdated as applications & product resources have been cheked.
