### ISSUE TITLE
Confirm redirects/removal

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#1067]
The following pages have been removed, or have redirects pointing to a different URL, please confirm that this is correct. On the drupal implementation, either the page is present or it doesn't have a redirect.

- [ ] /applications/cell-counting/guess-cellconfluence -> removed
- [x] /events/bioprocess-international -> redirects to `/events`
- [x] /events/festival-biologics -> redirects to `events`

**Comment by dev-rajneeshkumar** [comment]
Hi @andreituicu 
1. Incorrectly removed, should go to /applications/cell-counting/guess-cellconfluence.
2. Might be old redirect in the system but the the event is new so now redirect can be removed and page should work as https://live-md30.pantheonsite.io/events/bioprocess-international
3. Might be old redirect in the system but the the event is new so now redirect can be removed and page should work as https://live-md30.pantheonsite.io/events/festival-biologics

Below redirects were there in old system but can be corrected as commented above.

From: https://www.moleculardevices.com/guess-cellconfluence > [No redirect found  must be alias of same page or url changed]
From: https://www.moleculardevices.com/events/bioprocess-international > /events
From :https://www.moleculardevices.com/events/festival-biologics > /products/clone-screening

Regards,
Rajneesh

**Comment by lydiapuric** [comment]
@dev-rajneeshkumar Page https://live-md30.pantheonsite.io/applications/cell-counting/guess-cellconfluence and page
https://live-md30.pantheonsite.io/applications/cell-counting/guess-cellconfluence shows 
Interactive content unavailable
This Riddle is currently offline.

In new page this page does/applications/cell-counting/guess-cellconfluence and guess-confluence does not exist.
How to proceed?
cc @mhaack

**Comment by dev-rajneeshkumar** [comment]
@lydiapuric Both the above given urls seems to be same. I'll check it with business and get back to you.


Thanks,
Rajneesh

**Comment by lydiapuric** [comment]
As discussed in Slack, see https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1692784517318989?thread_ts=1692781070.129969&cid=C04QNDDUADT, redirecting `/applications/cell-counting/guess-cellconfluence` to home page.
