### ISSUE TITLE
Redirects are missing 

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1074]
Many Redirects are missing or seems to be redirecting wrong.
e.g. 
www.moleculardevices.com/SMPdownloadsite supposed to redirect https://danaherlifesciences.ent.box.com/s/2vtpmv1xt9iarzeprkr2c6zx720fdqtk as per old sheet but 
it was pointing to /s/2vtpmv1xt9iarzeprkr2c6zx720fdqtk [Fixed.]

Please cross check others as per old sheet or re-import it.
Here is the sheet of all 301 redirects from old site.
[301-MD.xlsx](https://github.com/hlxsites/moleculardevices/files/12368402/301-MD.xlsx)

**Comment by andreituicu** [comment]
Looks like the redirect to the external website was added as a relative redirect.

**Comment by lydiapuric** [comment]
I compared all the current defined redirects and the expected ones from 301-MD.xlsx.
When the current data did not match the expected target, I replaced it with the expected target.
When I found a redirect in our existing redirect configuration, I left it untouched, with the current target defined.

@dev-rajneeshkumar It would be great if you could verify some of the redirects like the one you mention here and recheck. Thanks




[5:50](https://cq-dev.slack.com/archives/DAKDHSW95/p1692373849363679)
so i can copy / paste in redirect excel file





[5:51](https://cq-dev.slack.com/archives/DAKDHSW95/p1692373865420559)
looks great for me what we have now





[5:51](https://cq-dev.slack.com/archives/DAKDHSW95/p1692373881024549)
and the redirect links are now for sure matching with what is expected

**Comment by lydiapuric** [comment]
Done
