### ISSUE TITLE
Publish Images from /sites/default/files/assets/images

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#1081]
In `/sites/default/files/assets/images` there are currently ~4000 images. These images are used cross site on https://support.moleculardevices.com using absolute URLs, for example https://support.moleculardevices.com/s/article/How-to-use-the-Wavelength-tab-in-MDA . The customer uploaded the images and requested bulk publishing

**Comment by andreituicu** [comment]
Solution:
* Requested a list of assets from the folder from @dev-rajneeshkumar using `dir > imagelist.txt` in his folder locally where all the images are
* Created a node script which parses the file and retrieves the list of images and for each image:
** Does a request to the Helix admin API to Preview
** Does a request to the Helix admin API to Publish
** Checks the franklin resulting sanitised path and if it differs from the original writes the redirect information to two files.

the script is executed as follows:
`node bulk-preview-publish.js 2> err.txt`
Reads from: `imagelist.txt`
Outputs:
* in `err.txt` any assets failed to be previewed/published
* in `unsuported.txt` any asset which are not supported (currently: `.gif`, `.tif`, `.bmp`)
* in `newredirectsfrom.txt` Source redirects -> contents can be copy/pasted into the `redirects.xls` Source column
* in `newredirectsto.txt` Destination redirects -> contents can be  copy/pasted into the `redirects.xls` Destination column

The script can be parametrised by changing the constants inside.

**Note:** the script cleans up the files when is executed, if you need to keep the files between executions, create copies/rename them before starting the script again.

https://gist.github.com/andreituicu/957a0047c464e0a2a451c637c3efe0d2

**Comment by andreituicu** [comment]
Executed the script and previewed/publish + created redirects for all `.png` and `.jpg` images: 3000+.
A few images had the wrong extension so I had to change the extension and reupload.

There are ~700 `.gif` files remaining where I am in discussion with the core team if this particular asset type can be added to the can be supported OOTB, if that's the case, then I can rerun the script for them.

There are a few remaining assets which are unsupported. @dev-rajneeshkumar I leave these up to you and your team to convert to a supported format (`.png` or `.jpeg`), reupload and create redirects for.
```
Microarray_QA634a.bmp
Microarray_QA634b.bmp
18851-1.bmp
18855-1.bmp
18855-2.bmp
20200-1.bmp
20200-2.bmp
20200-3.bmp
20200-4.bmp
20200-5.bmp
fileservermgr.bmp
Histogram1.bmp
KB_846_10-um.tif
KB_846_100-um.tif
KB_846_20-um.tif
KB_846_40-um.tif
KB_846_5-um.tif
KB_846_60-um.tif
KB_846_80-um.tif
KB_846_PreviewScan.tif
mm.tif
```

**Comment by andreituicu** [comment]
Keeping this issue open until we can understand what we do with the `.gif` assets.

**Comment by andreituicu** [comment]
The core team has added support for `.gif` assets. Preview/Published and added redirects for 717 gifs. In the root folder `/sites/default/files/assets/images`. 

Three failed and require further investigation:
```
231: ERROR: Failed to preview -1: 19583-7.gif due to -1 - Failed to parse response: error from content-bus
493: ERROR: Failed to preview -1: Flex.gif due to -1 - Failed to parse response: error from content-bus
615: ERROR: Failed to preview -1: MPW.gif due to -1 - Failed to parse response: error from content-bus
```

Moldev team has uploaded additional 9 subfolders (with less assets) which require additional publishing.

**Comment by andreituicu** [comment]
The images from the 10 subfolders have also been previewed / published and redirects created where needed.

**Comment by mhaack** [comment]
We wait for confirmation from @dev-rajneeshkumar
