### ISSUE TITLE
Broken links in the autoresponder email 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1083]
After submitting a form, we are getting broken pdf links for several landing pages in the autoresponder.

**Comment by duynguyen** [comment]
@MeghnaTewari could you please list a few examples?

**Comment by MeghnaTewari** [comment]
@duynguyen 
Found one

For these LP, the pdf is broken 

LP- https://www.moleculardevices.com/en/assets/ebook/dd/img/cell-pathways
PDF- https://www.moleculardevices.com/sites/default/files/en/assets/ebook/br/explore-pathways-like-a-pro.pdf

LP- https://www.moleculardevices.com/en/assets/ebook/br/spectramax-i3x
PDF- https://www.moleculardevices.com/sites/default/files/en/assets/ebook/dd/img/explore-pathways-like-a-pro.pdf?_hsmi=216428077&_hsenc=p2ANqtz-8OxnfvP-xNH34efDzorJzTRXkNUpweAyF-hGBT0qujLCdYh8d3n8FCDATX2WWelhwOA-kAzOcqq6jUQVSvKvCoLljyvw

**Comment by andreituicu** [comment]
`P1`: recreating the missing reported PDFs.
`P2`: understanding how can we find out what are all the items sent as links in emails, so we can cross check that nothing else is missing.

**Comment by alinarublea** [comment]
@MeghnaTewari I think I added the missing pdf s, is there a way to check easily which ones are missing ?

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari I think I added the missing pdf s, is there a way to check easily which other ones are missing?

@alinarublea 
I don't think so...these PDFs come through the autoresponder for gated landing pages, so they might be blocked by the robots.txt file. As a result, the tool can't scan these PDFs which are broken.

**Comment by alinarublea** [comment]
I see, but you could check the missing reported ones are ok ?

**Comment by MeghnaTewari** [comment]
@alinarublea Yes, those are fine.

**Comment by mhaack** [comment]
@MeghnaTewari how could we missed these with the 404 check? Are these added later after the 404 check?
How can we get a full list?

**Comment by MeghnaTewari** [comment]
> > @MeghnaTewari I think I added the missing pdf s, is there a way to check easily which other ones are missing?
> 
> @alinarublea I don't think so...these PDFs come through the autoresponder for gated landing pages, so they might be blocked by the robots.txt file. As a result, the tool can't scan these PDFs which are broken.

As I mentioned in my comment, these might be blocked so the tool is unable to crawl these pdfs

**Comment by mhaack** [comment]
Can we close this issue now?

**Comment by alinarublea** [comment]
@MeghnaTewari did you find other missing ones, or we can close the ticket and open another one if we find other missing ones

**Comment by MeghnaTewari** [comment]
@alinarublea Found one more. After fixing this we can close this issue as I haven't found any other broken pdf yet.

LP- https://www.moleculardevices.com/en/assets/presentations/dd/img/advantages-and-challenges-of-phenotypic-screening-in-3d-culture-including-ecm

Broken URL- https://www.moleculardevices.com/sites/default/files/en/assets/presentations/dd/img/advantages-and-challenges-of-phenotypic-screening-in-3d-culture-including-ecm.ppsx


old live URL for reference- https://live-md30.pantheonsite.io/sites/default/files/en/assets/presentations/dd/img/advantages-and-challenges-of-phenotypic-screening-in-3d-culture-including-ecm.ppsx

**Comment by alinarublea** [comment]
@MeghnaTewari this should be fixed now

**Comment by mhaack** [comment]
I checked the URL, resolving as fixed.
