### ISSUE TITLE
[HubSpot] Only Receiving Autoresponder upon Checking "Request More Info" Checkbox

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1084]
Autoresponder emails are coming only when users select the "Request More Info" checkbox.  Emails are not being received when the form is simply filled out and the "Submit" button is clicked.

Example URL- https://www.moleculardevices.com/en/assets/scientific-posters/br/rapid-assessment-of-viability-in-patient-derived-colorectal-cancer-organoids

**Comment by lydiapuric** [comment]
@MeghnaTewari This form is an iframe where we don't control the behaviour.
@dev-rajneeshkumar Can you have a look into this one please?

**Comment by lydiapuric** [comment]
According to @dev-rajneeshkumar  this issue seems to be from hubspot end. The MolDev team hs already opened discussion thread with hubspot team regarding the same.
See https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1692358404799029?thread_ts=1692357239.464769&cid=C04QNDDUADT

**Comment by lydiapuric** [comment]
Update status via Slack by @dev-rajneeshkumar , see https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1692794468575479

We are in touch with Hubspot team and so far threre is no permanent fix done for it. Now  
[@Jayant Kanchinadham](https://adobe-dx-support.slack.com/team/U04R20FJMRS) will contact with their live support team.
Sometimes email is working in both cases and in some scenarios there is a delay or No email at all

**Comment by mhaack** [comment]
Closing this as we have the interim solution in place.
