### ISSUE TITLE
[Accordion] load smaller images

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#109]
See LHS screenshot, we don't need images with width=2000 here.

![Screenshot 2023-03-23 at 09 39 26](https://user-images.githubusercontent.com/2643450/227148529-d00e72e4-65a6-4a2e-9387-2a4206d80d45.png)

**Comment by paolomoz** [comment]
@mhaack based on my research Google is testing 412px screen. Franklin default breakpoint is 400px. IMO there could be an opportunity of aligning Franklin default breakpoint with PageSpeed, but not worth it at project level

**Comment by paolomoz** [comment]
This will be fixed in the Franklin pipeline by https://github.com/adobe/helix-html-pipeline/pull/280

**Comment by paolomoz** [comment]
Fixed in Franklin pipeline https://github.com/adobe/helix-html-pipeline/pull/280
