### ISSUE TITLE
Fix poster landing page issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1091]
LP banner image is cutting off
https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023

TY page banner image is distorted
https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023?page=thankyou&rfq=Call&subscribe=false

Link in the autoresponder email is broken 
https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023-resources?cmp=7014u000001AVV1AAO&_hsmi=251404753&_hsenc=p2ANqtz-_L9fm_iRJD5o0nsNdiFKKicyOrB66VSyyixXDph9-B_uF3XB5bZ4s3xI6PmY9gcurg_KkWVa4oy8Kh3HOL_valCLknfQ

**Comment by duynguyen** [comment]
@MeghnaTewari : please verify if the fix is good:
https://1091--moleculardevices--hlxsites.hlx.page/en/assets/scientific-posters/dd/img/slas-2023-resources

Also https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023 is fixed.

**Comment by MeghnaTewari** [comment]
@duynguyen 

1. All Request Demo links should anchor link to the form on the page
here- https://1091--moleculardevices--hlxsites.hlx.page/en/assets/scientific-posters/dd/img/slas-2023-resources
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/87ed87eb-61c0-4bc3-8dfe-7c7dc88e85a1)

2. Fix this link, coming 404
https://1091--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/automating-organoid-models-and-assay-workflows
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3950ac57-d674-49d1-86a9-f3225fd4146e)

3. On submitting the form, TY page content is incorrect
https://1091--moleculardevices--hlxsites.hlx.page/en/assets/scientific-posters/dd/img/slas-2023-resources
https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023-resources?page=thankyou&rfq=Quote&subscribe=false

Please update as per- https://live-md30.pantheonsite.io/en/assets/scientific-posters/dd/img/slas-2023-resources?page=thankyou&rfq=Quote&subscribe=false


4. Banner is missing from the thank you page

https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023?page=thankyou&rfq=Call&subscribe=false
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1c8a3f9c-4747-47c2-b546-eb67d2564e04)
