### ISSUE TITLE
Remove video URL from search

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1092]
Please remove this URL from search 
https://www.moleculardevices.com/search-results#t=Videos&sort=relevancy

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/96d1a7a4-9895-4fc6-a681-c6e0772b8c2c)

We tried to delete this and rescan coveo but it is still there.

**Comment by andreituicu** [comment]
@duynguyen @mhaack the issue is that the coveo xml generator is not yet integrated with the github actions to refresh and needs to be executed manually.

https://github.com/hlxsites/moleculardevices/blob/main/coveo/generate-coveo-sitemap.js

Let's have a quick sync tomorrow on this

**Comment by andreituicu** [comment]
Please let me know if it looks ok for you and I can close it. Thank you!

**Comment by MeghnaTewari** [comment]
@duynguyen Yes please close this issue. It is fixed now.
