### ISSUE TITLE
PID missing for some category pages, hence going to global RFQ

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1093]
The link for the "Speak to a specialist and Request a demo" buttons are not going to their pid in the RFQ. They are going to the global RFQ.
https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers
https://www.moleculardevices.com/products/microplate-readers/absorbance-readers
https://www.moleculardevices.com/products/microplate-readers/fluorescence-readers
https://www.moleculardevices.com/products/microplate-readers/luminescence-readers

Please fix this globally, wherever there are "Speak to a specialist" and "Request a demo" CTA

1. Both the URLs should have their pid and call/demo request type
2. Thank you URL should have pid and rfq = call/demo (Will be addressed with #1094)

**Comment by MeghnaTewari** [comment]
@lydiapuric Markus asked me to open a new one for him, please check his comment.
 Please assign this issue to Markus

https://github.com/hlxsites/moleculardevices/issues/1080#issuecomment-1686158961

**Comment by mhaack** [comment]
Assigned to myself. @lydiapuric this is only for the for global RFQ and buttons don't have PID. This is for the for examples above a content issue.

**Comment by mhaack** [comment]
@MeghnaTewari please double check this is fixed now
