### ISSUE TITLE
Outdated URLs in robots.txt

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#1095]
@dev-rajneeshkumar I see of outdated URLs in robots.txt like `/web-design-style-guide` the are not on Franklin so we don't need them in robots.txt. Can you please remove them with another PR.

**Comment by dev-rajneeshkumar** [comment]
Ok Sure @mhaack  lmc with Raj

**Comment by dev-rajneeshkumar** [comment]
@mhaack  PR https://github.com/hlxsites/moleculardevices/pull/1097 has been opened for the same

**Comment by mhaack** [comment]
Fixed by #1097
