### ISSUE TITLE
Import /privacy-policy-archive

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#1098]
https://live-md30.pantheonsite.io/privacy-policy-archive is missing from Franklin.

Referenced in https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD4E4DB77-2C0C-4384-895C-17348405D8DA%7D&file=pending-kb-images-filtered.xlsx&action=default&mobileredirect=true

**Comment by mhaack** [comment]
Missing pages has been added
