### ISSUE TITLE
Pending broken links on the website

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1102]
Hi All,

PFA for the pending broken links on the website.
[404 error URLs on site.xlsx](https://github.com/hlxsites/moleculardevices/files/12409469/404.error.URLs.on.site.xlsx)

**Comment by MeghnaTewari** [comment]
Adding few more

https://www.moleculardevices.com/sites/default/files/2018-04/Video-Gn.png https://www.moleculardevices.com/sites/default/files/2019-08/user-guide.png https://www.moleculardevices.com/sites/default/files/icons/sds.png https://www.moleculardevices.com/sites/default/files/icons/coa.png

**Comment by mhaack** [comment]
All have been address in the sheet. Either imported, created redirect or missing on old site as well.

**Comment by mhaack** [comment]
Closing as we have https://github.com/hlxsites/moleculardevices/issues/1081 also for 404 issues.
