### ISSUE TITLE
Missing Schema and Hreflang Tag

### ISSUE THREAD

**Issue by RajMankotia** [hlxsites/moleculardevices#1105]
Hi @mhaack 
Please look into this and fix-
Hreflang Tag missing, blog, event and app note schema are also missing. 

Hreflang tag excluded for these sections like Resources and Blogs, news, and events.

For reference- 
Blog- https://live-md30.pantheonsite.io/lab-notes/clone-screening/role-of-crispr-in-microbiome-engineering
Event- https://live-md30.pantheonsite.io/events/slas-2023-building-biology-in-3d-symposium
App Note- https://live-md30.pantheonsite.io/en/assets/app-note/dd/img/ai-enabled-phenotypic-analysis-of-label-free-intestinal-organoids

**Comment by lydiapuric** [comment]
@RajMankotia Regarding your comment to 
Hreflang tag excluded for these sections like Resources and Blogs, news, and events.

I understand the Hreflang tag is missing for these sections.
Please identify the exact types where Hreflang tag should be added.

**Comment by RajMankotia** [comment]
Hi @lydiapuric 
If you check the old website - https://live-md30.pantheonsite.io/
Hreflang was implemented in these sections--  Product Pages, Applications, Technology, Video Gallery, Lab Automation pages, Contact Us Page, About Us Page, Leadership Page, and Customer Breakthrough

**Comment by lydiapuric** [comment]
Thanks @RajMankotia.

Could you please verify in the meantime the fix for the schemas mentioned in this issue?

- Blog: https://1105-schema--moleculardevices--hlxsites.hlx.page/lab-notes/clone-screening/role-of-crispr-in-microbiome-engineering
- Event: https://1105-schema--moleculardevices--hlxsites.hlx.page/events/slas-2023-building-biology-in-3d-symposium
- App Note: https://1105-schema--moleculardevices--hlxsites.hlx.page/en/assets/app-note/dd/img/ai-enabled-phenotypic-analysis-of-label-free-intestinal-organoids

**Comment by RajMankotia** [comment]
Hi @lydiapuric 
The blog and App Note schema looks good but for the Event please check it again.

**Comment by lydiapuric** [comment]
Thanks for quick response, @RajMankotia ! Regarding the Event schema: The only difference I see is the date format for startDate and endDate, the schema otherwise matches the original one. Is there another issue in the event schema I am missing?

**Comment by lydiapuric** [comment]
@RajMankotia Could you please verify the Hreflang tags? Thanks!

Some example pages I used for verification:
- Homepage: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/
- Product: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers
- Lab Automation: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/service-support/lab-automation-solutions/lab-automation-for-high-throughput-clone-screening
- Application: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/applications/monoclonality
- Technology: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/technology/luminescence
- Customer Breakthrough: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/img/university-of-sheffield
- Video Gallery: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/video-gallery/flipr-system
- Contact Us: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/contact?region=americas
- About Us: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/about-us
- Leadership: https://1105-hreflang--moleculardevices--hlxsites.hlx.page/leadership
- Event (no Hreftag!): https://1105-hreflang--moleculardevices--hlxsites.hlx.page/events/slas-2023-building-biology-in-3d-symposium

**Comment by RajMankotia** [comment]
Hi @lydiapuric, 
It shows the same Home Page Hreflang tags for all pages. All pages have their own URL with countries.

Here are eg.-
**for page- https://live-md30.pantheonsite.io/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers**
<html>
<body>


<link rel="alternate" hreflang="x-default" href="https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />
--
  | <link rel="alternate" hreflang="de" href="https://de.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />
  | <link rel="alternate" hreflang="es" href="https://es.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />
  | <link rel="alternate" hreflang="fr" href="https://fr.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />
  | <link rel="alternate" hreflang="it" href="https://it.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />
  | <link rel="alternate" hreflang="ko" href="https://ko.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />
  | <link rel="alternate" hreflang="zh" href="https://www.moleculardevices.com.cn/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers" />


</body>
</html>

**and it is different for this page- https://live-md30.pantheonsite.io/applications/cell-viability-proliferation-cytotoxicity-assays**

<html>
<body>


<link rel="alternate" hreflang="x-default" href="https://www.moleculardevices.com/applications/cell-viability-proliferation-cytotoxicity-assays" />
--
  | <link rel="alternate" hreflang="de" href="https://de.moleculardevices.com/applications/cell-viability-proliferation-cytotoxicity-assays" />
  | <link rel="alternate" hreflang="es" href="https://es.moleculardevices.com/applications/cell-viability-proliferation-cytotoxicity-assays" />
  | <link rel="alternate" hreflang="fr" href="https://fr.moleculardevices.com/applications/cell-viability-proliferation-cytotoxicity-assays" />
  | <link rel="alternate" hreflang="it" href="https://it.moleculardevices.com/applications/cell-viability-proliferation-cytotoxicity-assays" />
  | <link rel="alternate" hreflang="ko" href="https://ko.moleculardevices.com/applications/cell-viability-proliferation-cytotoxicity-assays" />
  | <link rel="alternate" hreflang="zh" href="https://www.moleculardevices.com.cn/applications/cell-viability-proliferation-cytotoxicity-assays" />


</body>
</html>
 
I think this example will be helpful.

**Comment by lydiapuric** [comment]
@RajMankotia Can you please recheck, fix is done.

**Comment by RajMankotia** [comment]
@lydiapuric 
Yes, now looks good. Thanks

**Comment by lydiapuric** [comment]
Thank you for quick verification!
