### ISSUE TITLE
Product RFQ for preview

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#1117]
Currently product RFQ is based on the index and only works on published products. However to get the full preview for business users we need a work product RFQ for hlx.page as well. Idea:

- we implement an exception on hlx.page only, not on prod
- with that the RFQ form can use any family id in the URL param and displays the family id on top of the form
- this will be only fall back for cases the product is not publish, otherwise like normal (based on index)

![Untitled](https://github.com/hlxsites/moleculardevices/assets/2643450/6db9c4ee-ecbd-4c69-a97c-022267031356)

**Comment by dev-rajneeshkumar** [comment]
Overall good to me @alinarublea  @mhaack 
Just one thing, product family is not appearing in iframe url neither going in sfdc , though it's there in the doc
![image](https://github.com/hlxsites/moleculardevices/assets/42608830/23aa8abc-80d1-4b1e-a335-a347b4cd89aa)

**Comment by mhaack** [comment]
> Overall good to me @alinarublea @mhaack
> Just one thing, product family is not appearing in iframe url neither going in sfdc , though it's there in the doc

@dev-rajneeshkumar yes we are currently just use the familyId from the request parameter the RFQ form gets. The doc is not loaded. So the RFQ form display works, however not all meta data is there to submit the form. If that is a test case and required, we need to find another, more tricky solution. The RFQ form only has the familyId with that we cannot find the product page URL, hence the other data cannot be extracted.
