### ISSUE TITLE
KB Resources visible in Tagging

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1122]
KB resources are showing in Tagging, they should remain hidden where the source is KB. For instance, if we take the example of the SpectraMax i3x product page 

https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers#resources
The user guide should not be displayed in the resources section and should be hidden.

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/79d52970-f19f-490d-9397-0a4ae090ffb6)

**Comment by mhaack** [comment]
@dev-rajneeshkumar @MeghnaTewari what is the rule here? Should all KB resources be hidden in the resource tab, every time?
We did not get that requirement, so far we filter only some of the resources by resource type.

**Comment by dev-rajneeshkumar** [comment]
Yes @mhaack  all KB resources should be hidden from tagging  however they will appear in resources hub/coveo search that's why source column is provided in the export. It might not be discussed directly but this is how it is on old site.

**Comment by mhaack** [comment]
@dev-rajneeshkumar what about sitemap.xml should they also be filtered out there?

**Comment by dev-rajneeshkumar** [comment]
Well in old site @mhaack we didn't excluded from sitemap but still we need to confirm from client that if they want to exclude it now.

**Comment by mhaack** [comment]
@MeghnaTewari please test again should be fixed. Overall this filtered out ~3.300 KB (tagged and untagged) entries which should not show up any more on the resource tabs.
