### ISSUE TITLE
[Regional contacts] UI issues

### ISSUE THREAD

**Issue by lydiapuric** [hlxsites/moleculardevices#1123]
Reported by @MeghnaTewari in #1055

1. There is inconsistency in the arrow icons after Contact your local Sales Team CTA, for some regions it shows and for some it doesn't. Check my screenshot for Albania
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/6daa01c5-50c9-49cc-bf5f-15cda48430e5)

2. Inconsistency in external icons as well
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c4054322-a1d0-41b4-8177-eae170f8612f)
 visible for some countries, example- US
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7d8de5b7-5943-4499-9eef-50013242fdcf)

3. Please fix the URL for this page
https://www.moleculardevices.com/contact-search?country=United%20States&product_family=

should be

https://live-md30.pantheonsite.io/contact-search?data=submit

**Comment by lydiapuric** [comment]
@MeghnaTewari
Question to point 3: Please fix the URL for this page
The functionality executed on submit is the same as on the previous side. 
However, technically, we are using the GET instead of POST method to submit data. 
The reason is that GET performs are better compared to POST because of the simple nature of appending the values in the URL.
Is there a reason why this should be handled via a POST request? 
@mhaack

**Comment by jose-correia** [comment]
The problem here is that:

- When we first access the page, the form defaults to USA, and the icons are showing
- However, when the form is changed, the icons disappear

**Comment by alexcarol** [comment]
> 3. Please fix the URL for this page
>    https://www.moleculardevices.com/contact-search?country=United%20States&product_family=
> 
> should be
> 
> https://live-md30.pantheonsite.io/contact-search?data=submit

@MeghnaTewari could you explain what you mean by this? If I go to https://www.moleculardevices.com/contact-search?data=submit it takes me to the same page as the other one. Where exactly on the site does the URL need to be replaced?

**Comment by MeghnaTewari** [comment]
On live when you click on search it takes you to this URL - https://www.moleculardevices.com/contact-search?country=United%20States&product_family=

which has the country name and product family parameter in it

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/dcb64e38-f73a-4ba9-ac37-12b8cebfcecf)


while on the old live, when you click on search it takes you to this URL - https://live-md30.pantheonsite.io/contact-search?data=submit

So on live, we need to fix the URL to be - /contact-search?data=submit'

without country name and product family parameter

**Comment by jose-correia** [comment]
@MeghnaTewari but what if the user selects a country and product group? If we change it to that behaviour, clicking search will show the `contact-us` page without any parameters already filled.

Currently if the user selects country and product group, we redirect them already to the contact-us page with the correct contacts shown

**Comment by mhaack** [comment]
@jose-correia @lydiapuric @MeghnaTewari what are the leftovers here? Is this being fixed.

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari but what if the user selects a country and product group? If we change it to that behavior, clicking search will show the `contact-us` page without any parameters already filled.
> 
> Currently if the user selects country and product group, we redirect them already to the contact-us page with the correct contacts shown

@jose-correia @lydiapuric  Can we remove all these parameters in the URL and just keep **/contact-search?data=submit**  like it is on the old site?
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/0a4e47c5-bbae-4260-9a72-5474d8aa538e)

If not then please modify the URL by replacing spaces with hyphens between the country and PF name, as it currently contains %20 due to the space

Something like this - https://www.moleculardevices.com/contact-search?country=Antigua-and-Barbuda&product_family=Assay-Kits-Media-Reagents

**Comment by lydiapuric** [comment]
Thanks @MeghnaTewari I will have a look at it and come back after adjusting

**Comment by lydiapuric** [comment]
@MeghnaTewari This is not reproducible for me, the URL stays /contact-search.
What I did (same behaviour in Firefox and Chrome):
1. Go to https://www.moleculardevices.com/contact-search
2. Select Antigua and Barbuda
3. Select Assay Kits, Media, Reagents
4. Click Search
==> URL stays https://www.moleculardevices.com/contact-search

**Comment by MeghnaTewari** [comment]
@lydiapuric  Can you please click on search button on the Contact Us page and check the URL

https://www.moleculardevices.com/contact?region=americas

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/bcb99833-56e0-4c44-9421-f3326b8fa46e)

When you directly go to this URL https://www.moleculardevices.com/contact-search it stays contact-search

**Comment by lydiapuric** [comment]
@MeghnaTewari I see. The %20 is browser behavior and is part of the encoding and cannot be changed. 
Firefox displays URLs containing spaces with an actual space (). Chrome always displays spaces as %20 in the address bar.

The search feature works perfectly, is the default browser behavior, has no security flaws and uses GET as a request method to optimize performance.

Replacing the %20 with hyphens introduces unnecessary application complexity and will slow down the page. Therefore I don't see this as a valid approach to go forward.
Introducing the request to be a POST to hide the parameters slows down the application too. 
With MolecularDevices to move to Franklin, the goal is to have page performance as good as possible, and this is how it is implemented now.
@MeghnaTewari @dev-rajneeshkumar Can we agree the feature works as expected and the feature does not have to be changed to keep the performance? 
cc @mhaack

**Comment by dev-rajneeshkumar** [comment]
I agree regarding the speed perspective but urls should also be clean. Let Raj(our seo expert) confirm on this!

**Comment by mhaack** [comment]
> The search feature works perfectly, is the default browser behavior, has no security flaws and uses GET as a request method to optimize performance.

I agree. Using URL parameters is perfectly fine. This way I also can copy the URL and share it in Slack or send to my colleagues. With POST this will not work.

Also this will not have any impact on SEO as the initial page url matters here, not urls people get after Form submit.

**Comment by RajMankotia** [comment]
Google's web crawlers don't like complex URLs that are filled with unnecessary characters. so in place of %20,
 Please use the Hyphen(-) to separate the words in URL parameters.

**Comment by lydiapuric** [comment]
@RajMankotia Parameter URLs are not bad for a website and it is not clear for me what's the benefit for SEO changing the URL parameters encoded by default browser behavior to hyphen version. The length is the same almost, can you please clarify?

**Comment by lydiapuric** [comment]
@RajMankotia @MeghnaTewari I will address the issue by replacing %20, commas and slashes by a hyphen
