### ISSUE TITLE
Schema and Hreflang tags missing for Main Pages

### ISSUE THREAD

**Issue by RajMankotia** [hlxsites/moleculardevices#1127]
Please check these pages. In these both schema and Hreflang tags are missing or either one of them.

https://www.moleculardevices.com/products
https://www.moleculardevices.com/products/3d-biology
https://www.moleculardevices.com/products/microplate-readers
https://www.moleculardevices.com/products/cellular-imaging-systems
https://www.moleculardevices.com/products/clone-screening
https://www.moleculardevices.com/products/axon-patch-clamp-system
https://www.moleculardevices.com/products/additional-products
https://www.moleculardevices.com/products/assay-kits
https://www.moleculardevices.com/products/accessories-consumables
https://www.moleculardevices.com/applications
https://www.moleculardevices.com/customer-breakthroughs
https://www.moleculardevices.com/video-gallery
https://www.moleculardevices.com/technology

**Comment by lydiapuric** [comment]
@RajMankotia Can you please confirm that the mentioned pages should have both, Schema & Hreflang? 
Is this an inclusive list of pages URLs or same page types should get schema and Hreftags?

**Comment by RajMankotia** [comment]
You can check in old website too-
https://live-md30.pantheonsite.io/products
https://live-md30.pantheonsite.io/products/cellular-imaging-systems
https://live-md30.pantheonsite.io/products/microplate-readers

**Comment by lydiapuric** [comment]
@RajMankotia Can you please verify?

- Products
https://1127-schema--moleculardevices--hlxsites.hlx.page/products

- Customer Breakthroughs
https://1127-schema--moleculardevices--hlxsites.hlx.page/customer-breakthroughs
https://live-md30.pantheonsite.io/customer-breakthroughs has no schema

- Video Gallery
https://1127-schema--moleculardevices--hlxsites.hlx.page/video-gallery
https://live-md30.pantheonsite.io//video-gallery has no schema

- Technology
https://1127-schema--moleculardevices--hlxsites.hlx.page/technology 
https://live-md30.pantheonsite.io/technology has no schema

- Applications
https://1127-schema--moleculardevices--hlxsites.hlx.page/applications 
https://live-md30.pantheonsite.io/applications has no schema


- Other main pages
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/3d-biology
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/microplate-readers
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/clone-screening
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/axon-patch-clamp-system
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/additional-products
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/assay-kits
- https://1127-schema--moleculardevices--hlxsites.hlx.page/products/accessories-consumables

**Comment by RajMankotia** [comment]
ok no problem if their is no schema please add. Rest looks good

**Comment by RajMankotia** [comment]
Hi,
 I have checked Google shows some error in the schema, will uou please update 
"@graph": [
    {
      "@type": "Product",
to 
"@graph": [
    {
      "@type": "WebPage",

and remove the  "category": " "     line 

and update 

 "brand": {
        "@type": "Brand",
        "name": "Molecular Devices",
to

 "author": {
        "@type": "Organization",
        "name": "Molecular Devices",

Here is a sample-

<script type="application/ld+json">{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "name": "Absorbance Plate Readers",
      "description": "Absorbance microplate readers and spectrophotometers for visible and UV-visible absorbance detection used for many research applications including ELISAs, nucleic acid and protein quantitation, and microbial growth.",
      "url": "https://www.moleculardevices.com/products/microplate-readers/absorbance-readers",
      "image": {
        "@type": "ImageObject",
        "representativeOfPage": "True",
        "url": "https://www.moleculardevices.com/products/microplate-readers/media_1a77a91b82f6f3b9879d4545f506ae371a9bee22d.jpeg?width=750&format=jpeg&optimize=medium"
      },
      "author": {
        "@type": "Organization",
        "name": "Molecular Devices",
        "description": "Molecular Devices is one of the leading provider of high-performance bioanalytical measurement solutions for life science research description pharmaceutical and biotherapeutic development.",
        "url": "https://www.moleculardevices.com/",
        "sameAs": [
          "http://www.linkedin.com/company/molecular-devices",
          "https://www.facebook.com/MolecularDevices",
          "http://www.youtube.com/user/MolecularDevicesInc",
          "https://twitter.com/moldev"
        ],
        "logo": {
          "@type": "ImageObject",
          "representativeOfPage": "True",
          "url": "https://www.moleculardevices.com/images/header-menus/logo.svg"
        }
      }
    }
  ]
}

Thanks

**Comment by RajMankotia** [comment]
Hi for Breadcrumb we are geeting error-
![image](https://github.com/hlxsites/moleculardevices/assets/142977173/afafc5a6-0e79-4a4d-b1da-3e73b4ff4446)

Please check sample and do needful-

    <script type="application/ld+json">
    {
     "@context": "https://schema.org",
     "@type": "BreadcrumbList",
     "itemListElement":
     [
      {
       "@type": "ListItem",
       "position": 1,
       "item":
       {
        "@id": "https://example.com/dresses",
        "name": "Dresses"
        }
      },
      {
       "@type": "ListItem",
      "position": 2,
      "item":
       {
         "@id": "https://example.com/dresses/real",
         "name": "Real Dresses"
       }
      }
     ]
    }
    </script>

**Comment by lydiapuric** [comment]
@RajMankotia Can you please specify the URLs where the product/ WebPage schema needs the mentioned adjustments?

The BreadcrumbList should be set for all pages which have a breadcrumb? Is this a new requirement because your sample doesn't show an example which matches site content? Can you please confirm?

**Comment by RajMankotia** [comment]
Regarding this - "URLs where the product/ WebPage schema"
Pick all pages having " .com/products/" in these pages, the schema needs to be updated as mentioned above.

and for breadcrumbs schema take the example of this page-
https://www.moleculardevices.com/products/microplate-readers/absorbance-readers

<script type="application/ld+json">
{
 "@context": "https://schema.org",
 "@type": "BreadcrumbList",
 "itemListElement":
 [
  {
   "@type": "ListItem",
   "position": 1,
   "item":
   {
    "@id": "https://www.moleculardevices.com",
    "name": "Home"
    }
  },
  {
   "@type": "ListItem",
   "position": 2,
   "item":
   {
     "@id": "https://www.moleculardevices.com/products",
     "name": "Products"
   }
  },
  {
   "@type": "ListItem",
  "position": 3,
  "item":
   {
     "@id": "https://www.moleculardevices.com/products/microplate-readers",
     "name": "Microplate Reader Solutions"
   }
   },
   {
   "@type": "ListItem",
  "position": 4,
  "item":
   {
     "name": "Absorbance Plate Readers"
  }
  }
 ]
}
</script>

**Comment by lydiapuric** [comment]
@RajMankotia When I try to understand on how to go forward with your comment in https://github.com/hlxsites/moleculardevices/issues/1127#issuecomment-1695052676 and looking at https://live-md30.pantheonsite.io/products/microplate-readers/absorbance-readers I cannot see why and where it is correct to change the type should from 'Product' to 'WebPage'. I also don't see the author node in the schema here. 
And looking on https://live-md30.pantheonsite.io/products/microplate-readers the type is 'Product' and has brand included. Can you please advice on how to differentiate and create the correct schema for which pages? Thanks!

**Comment by RajMankotia** [comment]
https://www.moleculardevices.com/products/microplate-readers/absorbance-readers
for this page currently schema is this-
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Product",
      "name": "Absorbance Plate Readers",
      "description": "Absorbance microplate readers and spectrophotometers for visible and UV-visible absorbance detection used for many research applications including ELISAs, nucleic acid and protein quantitation, and microbial growth.",
      "category": "absorbance microplate reader, spectrophotometer, UV-Vis absorbance plate readers",
      "url": "https://www.moleculardevices.com/products/microplate-readers/absorbance-readers",
      "image": {
        "@type": "ImageObject",
        "representativeOfPage": "True",
        "url": "https://www.moleculardevices.com/products/microplate-readers/media_1a77a91b82f6f3b9879d4545f506ae371a9bee22d.jpeg?width=750&format=jpeg&optimize=medium"
      },
      "brand": {
        "@type": "Brand",
        "name": "Molecular Devices",
        "description": "Molecular Devices is one of the leading provider of high-performance bioanalytical measurement solutions for life science research description pharmaceutical and biotherapeutic development.",
        "url": "https://www.moleculardevices.com/",
        "sameAs": [
          "http://www.linkedin.com/company/molecular-devices",
          "https://www.facebook.com/MolecularDevices",
          "http://www.youtube.com/user/MolecularDevicesInc",
          "https://twitter.com/moldev"
        ],
        "logo": {
          "@type": "ImageObject",
          "representativeOfPage": "True",
          "url": "https://www.moleculardevices.com/images/header-menus/logo.svg"
        }
      }
    }
  ]
}

----------------------------

Now check this and match this above- you find the difference, Tell me if got my point.

<script type="application/ld+json">{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "name": "Absorbance Plate Readers",
      "description": "Absorbance microplate readers and spectrophotometers for visible and UV-visible absorbance detection used for many research applications including ELISAs, nucleic acid and protein quantitation, and microbial growth.",
      "url": "https://www.moleculardevices.com/products/microplate-readers/absorbance-readers",
      "image": {
        "@type": "ImageObject",
        "representativeOfPage": "True",
        "url": "https://www.moleculardevices.com/products/microplate-readers/media_1a77a91b82f6f3b9879d4545f506ae371a9bee22d.jpeg?width=750&format=jpeg&optimize=medium"
      },
      "author": {
        "@type": "Organization",
        "name": "Molecular Devices",
        "description": "Molecular Devices is one of the leading provider of high-performance bioanalytical measurement solutions for life science research description pharmaceutical and biotherapeutic development.",
        "url": "https://www.moleculardevices.com/",
        "sameAs": [
          "http://www.linkedin.com/company/molecular-devices",
          "https://www.facebook.com/MolecularDevices",
          "http://www.youtube.com/user/MolecularDevicesInc",
          "https://twitter.com/moldev"
        ],
        "logo": {
          "@type": "ImageObject",
          "representativeOfPage": "True",
          "url": "https://www.moleculardevices.com/images/header-menus/logo.svg"
        }
      }
    }
  ]
}

**Comment by lydiapuric** [comment]
@RajMankotia Please verify in https://1127-webpage--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers
