### ISSUE TITLE
Breadcrumbs Schema issues

### ISSUE THREAD

**Issue by lydiapuric** [hlxsites/moleculardevices#1133]
Reported by @RajMankotia in issue #1127, see https://github.com/hlxsites/moleculardevices/issues/1127#issuecomment-1695061131
Hi for Breadcrumb we are geeting error-
![image](https://github.com/hlxsites/moleculardevices/assets/142977173/afafc5a6-0e79-4a4d-b1da-3e73b4ff4446)

Please check sample and do needful-

<script type="application/ld+json">
{
 "@context": "https://schema.org",
 "@type": "BreadcrumbList",
 "itemListElement":
 [
  {
   "@type": "ListItem",
   "position": 1,
   "item":
   {
    "@id": "https://example.com/dresses",
    "name": "Dresses"
    }
  },
  {
   "@type": "ListItem",
  "position": 2,
  "item":
   {
     "@id": "https://example.com/dresses/real",
     "name": "Real Dresses"
   }
  }
 ]
}
</script>

**Comment by lydiapuric** [comment]
@RajMankotia, see https://github.com/hlxsites/moleculardevices/issues/1127#issuecomment-1695262052:
and for breadcrumbs schema take the example of this page-
https://www.moleculardevices.com/products/microplate-readers/absorbance-readers

<script type="application/ld+json"> { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [ { "@type": "ListItem", "position": 1, "item": { "@id": "https://www.moleculardevices.com", "name": "Home" } }, { "@type": "ListItem", "position": 2, "item": { "@id": "https://www.moleculardevices.com/products", "name": "Products" } }, { "@type": "ListItem", "position": 3, "item": { "@id": "https://www.moleculardevices.com/products/microplate-readers", "name": "Microplate Reader Solutions" } }, { "@type": "ListItem", "position": 4, "item": { "name": "Absorbance Plate Readers" } } ] } </script>

**Comment by RajMankotia** [comment]
https://www.moleculardevices.com/products/microplate-readers/absorbance-readers
for this page currently schema is this-
{
"@context": "https://schema.org/",
"@graph": [
{
"@type": "Product",
"name": "Absorbance Plate Readers",
"description": "Absorbance microplate readers and spectrophotometers for visible and UV-visible absorbance detection used for many research applications including ELISAs, nucleic acid and protein quantitation, and microbial growth.",
"category": "absorbance microplate reader, spectrophotometer, UV-Vis absorbance plate readers",
"url": "https://www.moleculardevices.com/products/microplate-readers/absorbance-readers",
"image": {
"@type": "ImageObject",
"representativeOfPage": "True",
"url": "https://www.moleculardevices.com/products/microplate-readers/media_1a77a91b82f6f3b9879d4545f506ae371a9bee22d.jpeg?width=750&format=jpeg&optimize=medium"
},
"brand": {
"@type": "Brand",
"name": "Molecular Devices",
"description": "Molecular Devices is one of the leading provider of high-performance bioanalytical measurement solutions for life science research description pharmaceutical and biotherapeutic development.",
"url": "https://www.moleculardevices.com/",
"sameAs": [
"http://www.linkedin.com/company/molecular-devices",
"https://www.facebook.com/MolecularDevices",
"http://www.youtube.com/user/MolecularDevicesInc",
"https://twitter.com/moldev"
],
"logo": {
"@type": "ImageObject",
"representativeOfPage": "True",
"url": "https://www.moleculardevices.com/images/header-menus/logo.svg"
}
}
}
]
}

Now check this and match this above- you find the difference, Tell me if got my point.

<script type="application/ld+json">{ "@context": "https://schema.org", "@graph": [ { "@type": "WebPage", "name": "Absorbance Plate Readers", "description": "Absorbance microplate readers and spectrophotometers for visible and UV-visible absorbance detection used for many research applications including ELISAs, nucleic acid and protein quantitation, and microbial growth.", "url": "https://www.moleculardevices.com/products/microplate-readers/absorbance-readers", "image": { "@type": "ImageObject", "representativeOfPage": "True", "url": "https://www.moleculardevices.com/products/microplate-readers/media_1a77a91b82f6f3b9879d4545f506ae371a9bee22d.jpeg?width=750&format=jpeg&optimize=medium" }, "author": { "@type": "Organization", "name": "Molecular Devices", "description": "Molecular Devices is one of the leading provider of high-performance bioanalytical measurement solutions for life science research description pharmaceutical and biotherapeutic development.", "url": "https://www.moleculardevices.com/", "sameAs": [ "http://www.linkedin.com/company/molecular-devices", "https://www.facebook.com/MolecularDevices", "http://www.youtube.com/user/MolecularDevicesInc", "https://twitter.com/moldev" ], "logo": { "@type": "ImageObject", "representativeOfPage": "True", "url": "https://www.moleculardevices.com/images/header-menus/logo.svg" } } } ] }

**Comment by lydiapuric** [comment]
Can we please have a call @RajMankotia ?

**Comment by RajMankotia** [comment]
ok

**Comment by lydiapuric** [comment]
@RajMankotia Please verify BreadcrumbList:
`<ol itemscope="" itemtype="http://schema.org/BreadcrumbList"><li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"><a itemprop="item" href="/"><span itemprop="name">Home</span></a><meta itemprop="position" content="1"></li><li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"><a itemprop="item" href="/products"><span itemprop="name">Products</span></a><meta itemprop="position" content="2"></li><li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"><a itemprop="item" href="/products/microplate-readers"><span itemprop="name">Microplate Reader Solutions</span></a><meta itemprop="position" content="3"></li><li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"><span itemprop="name">Absorbance Plate Readers</span><meta itemprop="position" content="4"></li></ol>`

**Comment by lydiapuric** [comment]
Covered as part of PR https://github.com/hlxsites/moleculardevices/pull/1134
