### ISSUE TITLE
Add schema in FAQ 

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1142]
Hi @lydiapuric As Raj discussed with you, Please add this schema for FAQS.

<script type="application/ld+json">

{

"@context": "https://schema.org",

"@type": "FAQPage",

"mainEntity": [{

"@type": "Question",

"name": "What are CloneSelect Imager (CSI) and CSI FL?",

"acceptedAnswer": {

"@type": "Answer",

"text": "CloneSelect Imager (CSI) and CSI FL are advanced imaging systems designed for automated clone screening in mammalian cell culture. They provide high-throughput imaging and analysis capabilities to streamline the clone selection process."}

}, {

"@type": "Question",

"name": "What are the key features of CloneSelect Imager (CSI) and CSI FL?",

"acceptedAnswer": {

"@type": "Answer",

"text": "CloneSelect Imager (CSI) and CSI FL offer several key features, including automated imaging and analysis, high-resolution imaging with brightfield and fluorescence capabilities, customizable imaging protocols, and integrated software for data management and analysis."}

}, {

"@type": "Question",

"name": "How can CloneSelect Imager (CSI) and CSI FL optimize the clone screening process?",

"acceptedAnswer": {

"@type": "Answer",

"text":"CloneSelect Imager (CSI) and CSI FL can optimize clone screening by automating the imaging and analysis steps, reducing manual labor, and increasing throughput. The systems provide accurate and consistent image capture, enabling the identification of high-quality clones based on desired characteristics."}
}, {

"@type": "Question",

"name": "What types of assays can be performed using CloneSelect Imager (CSI) and CSI FL?",

"acceptedAnswer": {

"@type": "Answer",

"text":"CloneSelect Imager (CSI) and CSI FL support a wide range of assays, including viability and confluence measurements, cell counting, and fluorescence-based assays such as GFP expression analysis. The systems are versatile and can be adapted to specific experimental requirements.

The Fusion software in CSI-FL analyzes the cell counts and the presence of a fluorescence marker for the gene edit carried out. Each well is analyzed through a robust single-cell identification technique using both white light and fluorescence images."}
}, {

"@type": "Question",

"name": "Can CloneSelect Imager (CSI) and CSI FL integrate with existing laboratory workflows?",

"acceptedAnswer": {

"@type": "Answer",

"text":"Yes, CloneSelect Imager (CSI) and CSI FL are designed to integrate seamlessly with existing laboratory workflows. The systems can be connected to robotic platforms for fully automated processes and can also export data to various formats for further analysis or integration with other software tools."}
}, {

"@type": "Question",

"name": "How does CloneSelect Imager (CSI) and CSI FL contribute to scientific research?",

"acceptedAnswer": {

"@type": "Answer",

"text":"CloneSelect Imager (CSI) and CSI FL play a crucial role in scientific research by enabling efficient and reliable clone selection in mammalian cell culture. By automating the imaging and analysis processes, researchers can save time and resources, leading to faster and more accurate results."}
}, {

"@type": "Question",

"name": "Can CloneSelect Imager (CSI) and CSI FL be used in various laboratory workflows?",

"acceptedAnswer": {

"@type": "Answer",

"text":"Absolutely! CloneSelect Imager (CSI) and CSI FL are versatile imaging systems that can be seamlessly integrated into a wide range of laboratory workflows. Whether you're working on monoclonal antibody production, cell line development and characterization, disease modeling or screening for high-throughput cell-based assays, these systems can streamline and optimize your workflow."}
}, {

"@type": "Question",

"name": "What advantages does CloneSelect Imager (CSI) and CSI FL offer over manual clone screening methods?",

"acceptedAnswer": {

"@type": "Answer",

"text":"CloneSelect Imager (CSI) and CSI FL offer significant advantages over manual clone screening methods. These come with special software that successfully eliminates the subjectivity and variability associated with manual analysis, ensuring consistent and reproducible results. These results come with data reports, including various details, and image-based proofs - especially for the monoclonality verification. Additionally, the automated imaging capabilities significantly increase throughput and reduce the labor-intensive nature of clone screening and increase accuracy of data-driven assays"}
}, {

"@type": "Question",

"name": "Can CloneSelect Imager (CSI) and CSI FL be used for analyzing cell viability and growth rates?",

"acceptedAnswer": {

"@type": "Answer",

"text":"Yes, CloneSelect Imager (CSI) and CSI FL are equipped with advanced algorithms that allow the analysis of cell viability and growth rates. By capturing high-resolution images at multiple time points, researchers can accurately monitor cell growth dynamics, assess viability, and make informed decisions about clone selection."}
}, {

"@type": "Question",

"name": "Can CloneSelect Imager (CSI) and CSI FL help in optimizing the production of recombinant proteins?",

"acceptedAnswer": {

"@type": "Answer",

"text":"Absolutely! CloneSelect Imager (CSI) and CSI FL are valuable tools for optimizing the production of recombinant proteins. By efficiently identifying high-producing clones based on fluorescence intensity or other parameters, researchers can save time and resources during the cell line development process. This enables the selection of clones with high expression levels and desirable protein characteristics, leading to improved protein production workflows."}
}]

}

</script>

**Comment by lydiapuric** [comment]
@dev-rajneeshkumar Can you provide me a sample URL for a FAQ page?

**Comment by RajMankotia** [comment]
Need to add on this page- https://www.moleculardevices.com/products/clone-screening/mammalian-screening/cloneselect-imager

**Comment by RajMankotia** [comment]
for this section- 
![image](https://github.com/hlxsites/moleculardevices/assets/142977173/f7949db2-5c4d-4aa2-8043-a5a3ab435b31)

**Comment by RajMankotia** [comment]
Hi Alena, 
Regarding the FAQ Schema, please make it straight-way now it comes like FAQ section wise and each time we need to click and open it.

Currently, it shows like this- 
![image](https://github.com/hlxsites/moleculardevices/assets/142977173/a1e732d2-4b38-41a7-a551-12baa42f5618)

and we want it to be like this-
![image](https://github.com/hlxsites/moleculardevices/assets/142977173/53560286-1351-4432-af48-dbd7ff2b211e)

We can also discuss on call if needed.
Thanks

**Comment by MeghnaTewari** [comment]
@mhaack  Done https://github.com/hlxsites/moleculardevices/issues/1169
