### ISSUE TITLE
Missing resources for application pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1161]
I have attached the Excel for missing resources on the application pages
[Missing.assets_Apps.xlsx](https://github.com/hlxsites/moleculardevices/files/12514278/Missing.assets_Apps.xlsx)

**Comment by mhaack** [comment]
Using https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD6463026-2829-4ADC-9669-658B1D53961B%7D&file=MissingAssets_Apps.xlsx&action=default&mobileredirect=true for tracking

**Comment by mhaack** [comment]
Urls have been checked and fixed
