### ISSUE TITLE
Citations missing from app resources

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1166]
Citations category is missing from the application pages under the resources

Example URL- https://www.moleculardevices.com/applications/coronavirus-research/vaccine-development/antigen-immunogen-discovery-workflow#resources

old live- https://live-md30.pantheonsite.io/applications/coronavirus-research/vaccine-development/antigen-immunogen-discovery-workflow#resources

**Comment by mhaack** [comment]
@MeghnaTewari @dev-rajneeshkumar as written on Slack, we need the content of the citation itself first. When was this created/added?
