### ISSUE TITLE
Fix anchor link

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1178]
https://www.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/metaxpress 

view modules link should anchor link to the applications tab

**Comment by lydiapuric** [comment]
After setting the link in the content, the link seems not to work, checking

**Comment by lydiapuric** [comment]
The switch to tabs is done via JS, this might prevent it from switching

**Comment by lydiapuric** [comment]
The issue is that the menu contains same-name ids as the page tabs and then the menu id is chosen when switching. these ids need to be separated and handled in another way, investigating

**Comment by lydiapuric** [comment]
@MeghnaTewari Could you please verify following?

**Link with anchor**
https://1178-anchor--moleculardevices--hlxsites.hlx.page/about-us#who-we-are

**View Modules links to the applications tab**
https://1178-anchor--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/acquisition-and-analysis-software/metaxpress

**Link with anchor to a title in a tab:**
https://1178-anchor--moleculardevices--hlxsites.hlx.page/about-us#we-design-complete-solutions-for-any-application-to-meet-customer-needs-today--and-tomorrow

**Link with anchor that is nonexistent:**
https://1178-anchor--moleculardevices--hlxsites.hlx.page/about-us#nonexistent-id

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari Could you please verify following?
> 
> **Link with anchor** https://1178-anchor--moleculardevices--hlxsites.hlx.page/about-us#who-we-are
> 
> **View Modules links to the applications tab** https://1178-anchor--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/acquisition-and-analysis-software/metaxpress
> 
> **Link with anchor to a title in a tab:** https://1178-anchor--moleculardevices--hlxsites.hlx.page/about-us#we-design-complete-solutions-for-any-application-to-meet-customer-needs-today--and-tomorrow
> 
> **Link with anchor that is nonexistent:** https://1178-anchor--moleculardevices--hlxsites.hlx.page/about-us#nonexistent-id

@lydiapuric  These look good.

There are some anchor links  in the mega menu as well which are not working

Example- 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/09b85246-9471-49a8-9705-2ca26639652e)
https://1178-anchor--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems#imagexpress-high-content-imaginghci-technology

https://1178-anchor--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems#high-content-image-acquisition-and-analysis-software

**Comment by lydiapuric** [comment]
Thanks @MeghnaTewari I will have a look at the additional links

**Comment by lydiapuric** [comment]
@MeghnaTewari I just tested the 2 links in the mega menu in Firefox and Chrome, and they work for me. How can I reproduce the issue?

**Comment by MeghnaTewari** [comment]
@lydiapuric  Sent you a video on slack, please check

**Comment by MeghnaTewari** [comment]
@lydiapuric 
yes, it works here. https://1178-anchor--moleculardevices--hlxsites.hlx.page/

But the page is taking a bit longer to load that's why it is taking more time to anchor

. Can we do something about it?

**Comment by lydiapuric** [comment]
Loading performance will be addressed with #1194

**Comment by lydiapuric** [comment]
@MeghnaTewari reported:
Facing issues with anchor links again
We have added few anchor links on a page and they are not working.
Example -
https://main--moleculardevices--hlxsites.hlx.page/applications/3d-cell-models/organoids#cardiac-micro-tissues
https://main--moleculardevices--hlxsites.hlx.page/applications/3d-cell-models/organoids#patient-derived-colorectal-cancer-crc-organoids
https://main--moleculardevices--hlxsites.hlx.page/applications/3d-cell-models/organoids#cardiac-organoids

**Comment by lydiapuric** [comment]
@MeghnaTewari The behaviour is the same on old and new website, please check in https://live-md30.pantheonsite.io/applications/3d-cell-models/organoids#cardiac-micro-tissues 
The list of related applications still needs to be loaded; therefore, the anchor link only by posting it in URL is unavailable. The link can be reached by clicking on the anchor link in the list of related applications
This is implemented in old and new website to reduce page load time.

**Comment by MeghnaTewari** [comment]
@lydiapuric 
 we have a different id on old live. Please check with this URL, it works there https://live-md30.pantheonsite.io/applications/3d-cell-models/organoids#CardiacMicrotissues

**Comment by mhaack** [comment]
@MeghnaTewari hash id's are automatically generated and flow the new pattern of id generation. So this is expected and can not be influenced.

**Comment by dev-rajneeshkumar** [comment]
Ok understood @mhaack but then how we will make anchor links work then? Even it was fixed by @lydiapuric under this issue id only.
