### ISSUE TITLE
Implement automatic listing of new blogs in the 'Recent Posts' Section

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1183]
https://www.moleculardevices.com/lab-notes

**Comment by MeghnaTewari** [comment]
@lydiapuric  Each time a new blog is created, it should be automatically added to the 'Recent Posts' section, without the need for manually updating all three links
https://www.moleculardevices.com/lab-notes

cc @mhaack

**Comment by lydiapuric** [comment]
Found the Slack discussion in https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1694498387794559, this was in the old website automated, but now it's manually curated.

**Comment by mhaack** [comment]
@lydiapuric I'm going to work on this now
