### ISSUE TITLE
Need to add "name": "Molecular Devices", in home page Schema

### ISSUE THREAD

**Issue by RajMankotia** [hlxsites/moleculardevices#1207]
Hi @alexcarol ,
Need to add "name": "Molecular Devices", in home page Schema

![image](https://github.com/hlxsites/moleculardevices/assets/142977173/a72bb23c-d140-434e-84ea-d6bf9313a030)

**Comment by alexcarol** [comment]
Hi @RajMankotia, I'm happy to jump in and help if there's a time-sensitive issue or if the team has blind spots that I can help with, but as I'm no longer an active contributor to the project, could you either share the issue in the slack channel if you need it fixed soon or ask @mhaack to dispatch it if needed? Thanks!

**Comment by RajMankotia** [comment]
@mhaack Please do some needful on this.
