### ISSUE TITLE
Date Discrepancy Issues on events page

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1211]
Images are breaking on the events landing page.
https://www.moleculardevices.com/events 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/07b71a4f-e25e-4862-a49b-5bbe3f413279)

 Also, there is a discrepancy in the dates. An extra date appears on the events landing page for all the events.

For example, the first event displays Sept 18 - **Sept 22, 2023**, on the events landing page, but when you click on it, the date shows Sept 18 - **Sept 21, 2023**, on the event details page. (The date on the event details page is correct i.e. Sep 18 - Sep 21, 2023 ) 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5b8efa9e-9f36-4201-ad5a-2ab1d909d068)

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/cda26123-c7a0-4f1a-a3b1-2c9feb646213)

**Comment by mhaack** [comment]
Updated the issue title. The images are fixed and not broken any more, only the date issue is open.
