### ISSUE TITLE
Asset URL serving 404

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1217]
Getting 404 error in the autoresponder email for this ungated resource page 

404  URL - https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/laboratory-automation-screening-research?cmp=7014u000001t6X0AAI&utm_medium=email&_hsmi=216843178&_hsenc=p2ANqtz--s2D1BjCUyJ-ZkZJZCiU3RwOFtd0nOZyJKCjVY7J0fC3cbkyDuN8XBWu4qD37EbtBoig-lw4oxaeXzZzZ2K4jJqaqRTYBMiXycL4bPz69JEEnCYbQ&utm_content=216843178&utm_source=hs_automation

**Gated LP-** https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/laboratory-automation-and-screening-research

Old live resource page - https://live-md30.pantheonsite.io/en/assets/scientific-posters/dd/img/laboratory-automation-screening-research

**Comment by lydiapuric** [comment]
@MeghnaTewari Is this still an issue?
Accessing https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/laboratory-automation-screening-research?cmp=7014u000001t6X0AAI&utm_medium=email&_hsmi=216843178&_hsenc=p2ANqtz--s2D1BjCUyJ-ZkZJZCiU3RwOFtd0nOZyJKCjVY7J0fC3cbkyDuN8XBWu4qD37EbtBoig-lw4oxaeXzZzZ2K4jJqaqRTYBMiXycL4bPz69JEEnCYbQ&utm_content=216843178&utm_source=hs_automation I don't get a 404

**Comment by MeghnaTewari** [comment]
@lydiapuric This is fixed. Please close this issue.
