### ISSUE TITLE
? being added to destination urls in the redirects

### ISSUE THREAD

**Issue by RajMankotia** [hlxsites/moleculardevices#1218]
Hi Team,
? being added to destination urls in the redirects=
https://www.moleculardevices.com/sites/default/files/en/assets/user-guide/bpd/dispencell-userguide-5306400a.pdf
when it goes to the destination -
https://www.moleculardevices.com/sites/default/files/en/assets/user-guide/bpd/dispencell-userguide-5306400b.pdf?
at the end "?" is added

**Comment by mhaack** [comment]
@RajMankotia I will take care looks like some bug in the redirect handling.

**Comment by mhaack** [comment]
Fixed, @RajMankotia this should be fixed now.

**Comment by RajMankotia** [comment]
Thanks
