### ISSUE TITLE
Header Block not accepting any custom logo

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1219]
Hi All,

We want to create a page with different header/footer. Everything was going fine  so far as per adobe team instructions but then we realized that header nav brand block is not accepting any other image. It's always showing default logo of moldev.

Also, we don't need any other links and dropdown in the header which seems to be mandatory in current code implemenation.
 
https://main--moleculardevices--hlxsites.hlx.page/cellesce
![Asset 5](https://github.com/hlxsites/moleculardevices/assets/42608830/00ccdfc8-d7bb-41a1-8234-feb4821d5dde)

[cellesce.com is now...pdf](https://github.com/hlxsites/moleculardevices/files/12726386/cellesce.com.is.now.pdf)

Regards,
Rajneesh

**Comment by lydiapuric** [comment]
WIP in https://github.com/hlxsites/moleculardevices/tree/brandlogo-fix

**Comment by lydiapuric** [comment]
WIP in https://github.com/hlxsites/moleculardevices/tree/brandlogo-fix

**Comment by lydiapuric** [comment]
Additional requirements for the header:
- Allow to hide Global  RFQ link
