### ISSUE TITLE
Broken footer for blogs

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1220]
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/03853a65-e47a-4f6c-982a-843e995fa1be)

https://www.moleculardevices.com/lab-notes/blog

**Comment by mhaack** [comment]
@dev-rajneeshkumar this got introduced by https://github.com/hlxsites/moleculardevices/commit/bdc66231afb68680ef1b941a05724785f594c119 lately can you have a look

**Comment by lydiapuric** [comment]
@MeghnaTewari @dev-rajneeshkumar 
Can you please verify in https://1220-hq--moleculardevices--hlxsites.hlx.page/lab-notes/blog?

**Comment by lydiapuric** [comment]
Reopen issue but degrading priority because the footer contact and the big gap to links in the first column got fixed 
There are some more issues to be fixed, eg
- Headlines for row 1 and row 4 are not aligned on top
- Links in row 1 might be in one line

**Comment by mhaack** [comment]
@lydiapuric saw the frist PR, instead of unsetting it wouldn’t it be better to initially scope it to `main` only, it does not influence the footer.

**Comment by lydiapuric** [comment]
thx, adjusting

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari @dev-rajneeshkumar Can you please verify in https://1220-footer--moleculardevices--hlxsites.hlx.page/lab-notes/blog?

@lydiapuric  Verified! Looks fine.

Just one small thing, for the blog footer there is a bit less line spacing here, compared to other footers - 

https://1220-footer--moleculardevices--hlxsites.hlx.page/lab-notes/blog

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fe4ee20d-0814-479f-80a0-bb8d3bc9c41f)

**Comment by MeghnaTewari** [comment]
@lydiapuric Looks fine now.
