### ISSUE TITLE
Blurry images on site

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1229]
Some images on the website look blurry, like the banner images on certain product pages. 

The homepage pictures aren't blurry, but they're not as clear as they used to be on the old site. I've listed some pages where there is this issue. Please compare the pages with the old live.

https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers
https://www.moleculardevices.com/products/microplate-readers
https://www.moleculardevices.com/
https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers
https://www.moleculardevices.com/products/3d-biology/3d-ready-organoid-expansion-service
https://www.moleculardevices.com/applications/3d-cell-models/organoids

**Comment by lydiapuric** [comment]
Updated content in 
https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers
https://www.moleculardevices.com/products/microplate-readers

**Comment by MeghnaTewari** [comment]
> Unfortunately I don't find page https://www.moleculardevices.com/products/3d-biology/3d-ready-organoid-expansion-service to get original picture(s) from (https://live-md30.pantheonsite.io/products/3d-biology/3d-ready-organoid-expansion-service provides 404). Can you provide the pictures?

@lydiapuric  You can find this image here  - https://live-md30.pantheonsite.io/products/3d-biology/custom-organoid-expansion-service

The banner image is still blurry on this page https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers

**Comment by lydiapuric** [comment]
@MeghnaTewari Can you please recheck 
https://www.moleculardevices.com/products/3d-biology/3d-ready-organoid-expansion-service and
https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers
Thanks!
