### ISSUE TITLE
Product group name format issue on regional contacts

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1230]
On the regional contact page, there are hyphens between the product group names, and also separator is missing between the names.
https://www.moleculardevices.com/contact-search?country=brazil&product_family=

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c2fdfec1-2214-4222-977a-c35810fc2747)

Old live - 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5520336b-dc11-4f7f-829d-01e91c37d290)

**Comment by dev-rajneeshkumar** [comment]
Fixed in PR https://github.com/hlxsites/moleculardevices/pull/1233.
@mhaack @andreituicu @duynguyen  please review
