### ISSUE TITLE
Image is missing in the RFQ autoresponder

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1232]
Image of the product is missing in the autoresponder email. 

Example - 

https://www.moleculardevices.com/quote-request?pid=spectramax-i3x-multi-mode-microplate-reader
https://www.moleculardevices.com/quote-request?pid=3d-cell-models

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c677dcfc-8a31-466e-be68-1869897404bb)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/bb8687b2-b2c6-4544-aaea-58f13a6e5cb8)

Old live autoresponder - 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/62c068d2-8e4d-4fab-9f51-c966669bb461)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8a1ef858-da88-4dd3-9194-88ea7fd1162a)

**Comment by lydiapuric** [comment]
@dev-rajneeshkumar assigning this to you because I am assuming this is on the Hubspot side.

**Comment by mhaack** [comment]
@MeghnaTewari can you click on "view in browser" of the mail with missing image and share the link. I agree with @lydiapuric this seems to be a Hubspot issue or a combination of Hubspot linking to an image with fixed URL which we don't have.

**Comment by dev-rajneeshkumar** [comment]
@mhaack / @lydiapuric  image value is not being fetched in the iframe url  itself unlike old live.

Current: https://info.moleculardevices.com/rfq?product_family__c=SMax+iX&product_selection__c=SpectraMax+i3x+Multi-Mode+Microplate+Reader&product_primary_application__c=SpectraMax+i3x+Multi-Mode+Microplate+Reader&cmp=70170000000hlRa&google_analytics_medium__c=&google_analytics_source__c=&keyword_ppc__c=&gclid__c=&**product_image=NA**&requested_qdc_discussion__c=Quote&return_url=https%3A%2F%2Fwww.moleculardevices.com%2Fquote-request-success%3Fcat%3Dspectramax-i3x-multi-mode-microplate-reader

Old : https://info.moleculardevices.com/rfq?product_family__c=SMax iX&product_selection__c=SMax iX&product_primary_application__c=SpectraMax i3x Multi-Mode Microplate Reader&return_url=https://live-md30.pantheonsite.io/quote-request-success?pid%5B223%5D%3D223&**product_image**=https://live-md30.pantheonsite.io/sites/default/files/styles/related_products/public/products/banners/spectramax-i3x-thumb..png?itok=sMEY6i2m&website=https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers&Primary_Application_geo=SpectraMax%20i3x%20Multi-Mode%20Microplate%20Reader&cmp=70170000000hlRa&requested_qdc_discussion__c=Quote

**Comment by MeghnaTewari** [comment]
Here is the link @mhaack 

https://email.moleculardevices.com/request-quote-molecular-devices-2?ecid=ACsprvvi_dTFLGVAIiI-88p1rR62bfls6axnDwvR3JVxx38OmbsbHjUFd5mXyBx0hjaszDTff65O&_hsmi=225898476

**Comment by mhaack** [comment]
@dev-rajneeshkumar I see multiple differences in the URLs. `**product_image**` is that the correct parameter name? However we set it to "NA"

**Comment by dev-rajneeshkumar** [comment]
@mhaack  product_image is the exact name and it should be set to image url and shown in example url of old website.
I think updating it to the value of  'thumbnail' tab in the sheet should work but i am not sure.
![image](https://github.com/hlxsites/moleculardevices/assets/42608830/83b2f037-b030-4bd4-bfc5-18b40b66810c)

**Comment by mhaack** [comment]
Understood, working on a PR

**Comment by MeghnaTewari** [comment]
@mhaack found one issue with the links on the image in the autoresponder email.

I submitted 2 RFQs - one for ClonePix 2 and another for 3D Cell Models.
https://rfq-image--moleculardevices--hlxsites.hlx.page/quote-request?pid=clonepix-2-mammalian-colony-pickers
https://rfq-image--moleculardevices--hlxsites.hlx.page/quote-request?pid=3d-cell-models

In the autoresponder email for ClonePix 2, the link on the image is correct and takes you to the ClonePix 2 product page.

But, in the email for 3D Cell Models, the link on the image goes to the previously submitted product rfq i.e ClonePix 2 product page.

I think there is some cache issue.

**Comment by mhaack** [comment]
@MeghnaTewari I double checked with the two links above

* https://rfq-image--moleculardevices--hlxsites.hlx.page/quote-request?pid=clonepix-2-mammalian-colony-pickers has https://www.moleculardevices.com/media_176fe19452b51369cd14cc78bb3f6178433db12e0.png?width=750&format=png&optimize=medium as image
* https://rfq-image--moleculardevices--hlxsites.hlx.page/quote-request?pid=3d-cell-models has https://www.moleculardevices.com/media_1a7c35ec918098ac37972ea25d059d7f2f58b1602.jpeg?width=750&format=jpeg&optimize=medium as image

We send definitely different images for different products.

**Comment by MeghnaTewari** [comment]
@mhaack the images are correct, I was talking about the hyperlinks added on the images in the email. They should go to their respective product pages. But right now, maybe due to some cache issue, the links are incorrect.

**Comment by mhaack** [comment]
Oh sorry I misunderstood that. I have no idea how the links are generated, we don't send any hyperlink which is used in the mail, that must be generated by HubSpot.

**Comment by MeghnaTewari** [comment]
It's strange that I could see hyperlinks on these images yesterday, but I can't today.
Can you please implement the hyperlinks for the images in the autoresponder, the links should go to their appropriate page. ( it was the same on old Live)

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9e488d86-6f9d-42b8-8bad-e81f43df88fc)
