### ISSUE TITLE
Anchor links not working for dynamically loaded anchors

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#1241]
See https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers#protein-detection-quantitation-and-analysis

This should deep link to the applications tab to the correct applications. It works from the applications tabs toc but not on the very first load of the page. The application list is loaded dynamically and therefor the hash does not exist on the initial html. We need some JS to process this after the block has loaded.

**Comment by MeghnaTewari** [comment]
Hi, @mhaack  any update on this issue?

**Comment by lydiapuric** [comment]
@MeghnaTewari I didn't have yet the chance to work on it. I will keep you updated.

**Comment by lydiapuric** [comment]
@MeghnaTewari Could you please test in 
https://1241-fix--moleculardevices--hlxsites.hlx.page/applications/3d-cell-models/organoids#cardiac-organoids
https://1241-fix--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers#protein-detection-quantitation-and-analysis

**Comment by dev-rajneeshkumar** [comment]
@lydiapuric  working for for me
