### ISSUE TITLE
App note pages missing in content-sitemap.xml

### ISSUE THREAD

**Issue by RajMankotia** [hlxsites/moleculardevices#1246]
@mhaack We have 353 app notes on website but in [content-sitemap.xml](https://www.moleculardevices.com/content-sitemap.xml) only 141. please check and fix. App note pages and Gated App note Landing pages will be the part of sitemap. Please don not include gated App note HTML pages. Because their Landing pages will come in sitemap.

**Comment by RajMankotia** [comment]
@mhaack Please look into this.

**Comment by mhaack** [comment]
Do you have some URLs which are missing so I can look into it?

**Comment by mhaack** [comment]
Current rule for all pages is, they are in the sitemap.xml if:
* they are not marked as "no index"
* they are not for any special local (like zh or fr)
* they are not marked as gated = yes
* the url does not start with `/resources/data`

**Comment by mhaack** [comment]
>Please don not include gated App note HTML page

This should be the case already, every pages flagged with gates = yes is excluded

**Comment by RajMankotia** [comment]
In [sitemap](https://www.moleculardevices.com/content-sitemap.xml) I found only 137 app notes but we have 353 total count so please add the missing one in sitemap.

**Comment by mhaack** [comment]
@RajMankotia we need some example URLs which are missing to understand why some are not included. They are added based on rules. Need to understand why the rules we have do not apply to all of the relevant app note pages.

**Comment by RajMankotia** [comment]
Ok thanks, will share soon.

**Comment by RajMankotia** [comment]
Here are some -https://www.moleculardevices.com/en/assets/app-note/reagents/ila-contaminant-bsa-assay
https://www.moleculardevices.com/en/assets/app-note/br/measure-long-term-cell-growth-using-a-discontinuous-kinetic-reading
https://www.moleculardevices.com/en/assets/app-note/dd/flipr/screenworks-peaks-pro-software-for-flipr-tetra-cellular-screening-systems
https://www.moleculardevices.com/en/assets/app-note/dd/img/automating-the-generation-and-analysis-of-3d-cell-cultures-in-matrigel
https://www.moleculardevices.com/en/assets/app-note/dd/flipr/calcium-signaling-with-flipr-calcium-6-and-6-qf-assay-kits-on-flexstation-3-reader
https://www.moleculardevices.com/en/assets/app-note/br/assess-cell-viability-and-proliferation-with-colorimetric-readouts
https://www.moleculardevices.com/en/assets/app-note/reagents/earlytox-live-dead-assay-kit-on-spectramax-fluorescence-readers
https://www.moleculardevices.com/en/assets/app-note/dd/img/improve-nuclear-translocation-assay-results-using-image-deconvolution
https://www.moleculardevices.com/en/assets/app-note/dd/flipr/multi-parametric-assessment-of-compound-induced-pro-arrhythmic-effects-in-human-ipsc-derived-cardiomyocytes
https://www.moleculardevices.com/en/assets/app-note/br/measuring-neurite-outgrowth-with-spectramax-minimax-cytometer-and-metamorph-software

**Comment by mhaack** [comment]
Found an issue in the filter rules, should be fixed now. @RajMankotia please recheck, before it was ~1300 URL, not we have 1600 URLs.

**Comment by RajMankotia** [comment]
@mhaack Thanks, looks good.
