### ISSUE TITLE
Files sitemap is too heavy to load

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1266]
Hi All,
Files sitemap is becoming too heavy to load. Can we apply any pagination here?
https://www.moleculardevices.com/files-sitemap.xml

Regards,
Rajneesh

**Comment by mhaack** [comment]
Help us to understand why? Is there a tool or report telling this? Is that from GSC?

**Comment by mhaack** [comment]
Sitemaps are allowed to be way larger then we have today: `All formats limit a single sitemap to 50MB (uncompressed) or 50,000 URLs. `. https://www.moleculardevices.com/files-sitemap.xml is currently 35kByte (compressed) and 919kByte (uncompressed) with ~ 3.600 entries.

See: https://www.sitemaps.org/faq.html#:~:text=Sitemaps%20should%20be%20no%20larger,a%20maximum%20of%2050%2C000%20URLs & https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#sitemap-best-practices
