### ISSUE TITLE
Export all the required data for the applications 

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#180]
Need to export all the required for the applications from https://www.moleculardevices.com/

Source: https://www.moleculardevices.com/applications

**Comment by dev-rajneeshkumar** [comment]
Hi Team,
Here is the full export for the applications containing extra columns as **PARENT APPLICATION,CATEGORY,RELATED CATEGORIES,RELATED PRODUCTS**
[applications-full-export.xlsx](https://github.com/hlxsites/moleculardevices/files/11179216/applications-full-export.xlsx)

**Comment by dev-rajneeshkumar** [comment]
Hi @mhaack , new columns for Technology Redirect[next to Url] and SHORT DESCRIPTION[at the end ] has been added to applications export.  Short description having more than aprx. 200 characters here but in front we showing 100 only so you can manage accordingly. Next, as said  over slack, applications which has no category and no short description are not listed over landing page.

**Comment by mhaack** [comment]
Done, imported
