### ISSUE TITLE
Provide documentation and endpoint for the IP Checker API

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#182]
We should call that API async to not delay the page loading. This can be done centrally via delay.js and the result should be stored in a cookie. That can be used by blocks and other logic to show region specific elements.

**Comment by kapildhiman** [comment]
The name of the service is **ipstack**

For testing please get a free API key here https://ipstack.com/product.

//  jQuery ref. to get the location of an IP address
```
var ip = '134.201.250.155'
var access_key = 'YOUR_ACCESS_KEY';

// get the API result via jQuery.ajax
$.ajax({
    url: 'https://api.ipstack.com/' + ip + '?access_key=' + access_key,
    dataType: 'jsonp',
    success: function(json) {
        // output the "capital" object inside "location"
        alert(json.location.capital);

    }
});
```
Here is the complete documentation:  https://ipstack.com/documentation

**Comment by mhaack** [comment]
@kapildhiman in JS we don't have the IP address of the current user, that would require a different API call

**Comment by mhaack** [comment]
As discussed on Slack we can use http://api.ipstack.com/check?access_key=fa0c43f899d86d91bf5aa529a5774566 (with final API key) her and we are interested in the country field.
"country_code" == "US" we show the cart, everything else no cart and now add2cart buttons etc.

cc: @kapildhiman
