### ISSUE TITLE
[Import] Import mobile images for hero

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#183]

**Comment by paolomoz** [comment]
Example product page with the latest content structure, including the mobile image
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B5E1481D7-256B-4D42-BA19-80DC1F51B82B%7D&file=spectramax-i3x-readers1.docx&action=default&mobileredirect=true
