### ISSUE TITLE
Extract specification of all the products

### ISSUE THREAD

**Issue by kapildhiman** [hlxsites/moleculardevices#195]
Ref. 
https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers#specs

![image](https://user-images.githubusercontent.com/58678719/231397327-75dab707-7df6-4ecb-93ea-0657071e4f6f.png)

**Comment by kapildhiman** [comment]
Hi @mhaack ,

This page has specifications of all products: https://1-md30.pantheonsite.io/product-url (Product name + URL + specifications and separation line)

Hope this will help to import specs in Franklin. 

Thanks,

**Comment by mhaack** [comment]
Imported into sheets in https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fmoleculardevices%2Fproducts%2Fspecifications&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95
