### ISSUE TITLE
[Product] Implement "Related Products & Services" tab using "Cards" block

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#227]
Implement & style the "Related Products & Services" tab using "cards" block

For cards block
* use `Cards (Banner)` option to render slightly bigger cards with the green banner

Samples
* https://www.moleculardevices.com/products/gxp-compliance-solutions/softmax-pro-gxp-software#RelatedProducts
* https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-m-series-readers#RelatedProducts

**Comment by duynguyen** [comment]
@jose-correia you could render the cards with this: https://github.com/hlxsites/moleculardevices/blob/main/blocks/card/card.js.

Remaining would just be some styling work.

**Comment by duynguyen** [comment]
Major tasks are done in #369 . Categories is pending, hence keeping this issue open for now.
