### ISSUE TITLE
Provide static PDF newsletter files

### ISSUE THREAD

**Issue by kapildhiman** [hlxsites/moleculardevices#296]
ref.

https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/april-2023.html

![image](https://user-images.githubusercontent.com/58678719/236386538-a64b3bd7-b86e-4fb7-91ca-d7f792656e31.png)

**Comment by kapildhiman** [comment]
@lydiapuric 
As discussed I've all newsletter files under https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fmoleculardevices%2Fsites%2Fdefault%2Ffiles%2Fen%2Fassets%2Fnewsletter&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95

cc'd @mhaack @dev-rajneeshkumar

**Comment by mhaack** [comment]
As discussed we will go with PDF files instead of HTML and setup redirects for the .html links.

**Comment by kapildhiman** [comment]
All HTML newsletter converted to pdf and uploaded under https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fmoleculardevices%2Fsites%2Fdefault%2Ffiles%2Fen%2Fassets%2Fnewsletter&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95

**Comment by mhaack** [comment]
This was done and can be closed
