### ISSUE TITLE
[Product] Implement "Order Options" tab for Assay Kits - Part 1

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#304]
With the shopify keys available we can render the "Product Ordering Options" block.

The Shopify Keys are provided as block options, the block can have one or many entries.

Sample:

- https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/valitatiter#ordering-options
- https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/gpcrs/catchpoint-cgmp-fluorescent-assay-kit#ordering-options
- https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/clonedetect#ordering-options

**Comment by mhaack** [comment]
API usage:

- to get a complete detail of a product. use this call https://shop.moleculardevices.com/products/<PRODUCT-HANDLE>.js'
ref. https://shop.moleculardevices.com/products/flipr-calcium-6-assay-kit.js

- for cart
add to cart : https://shop.moleculardevices.com/cart/add.js?id=<productId>&quantity=<quantity>
get cart details : https://shop.moleculardevices.com/cart.json

**Comment by lydiapuric** [comment]
WIP in branch order-options-assay-kits-1
