### ISSUE TITLE
Provide Drift integration details

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#329]
Please provide the integration details for the Dirft widget.

**Comment by kapildhiman** [comment]
here is the drift script that needs to be added to the head tag.  Can used with/without setTimeout in our case we used with setTimeout.

    
		<script>
            "use strict";
    
            function LoadDriftWidget() {
              var t = window.driftt = window.drift = window.driftt || [];
              if (!t.init) {
                if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
                t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
                t.factory = function(e) {
                  return function() {
                    var n = Array.prototype.slice.call(arguments);
                    return n.unshift(e), t.push(n), t;
                  };
                }, t.methods.forEach(function(e) {
                  t[e] = t.factory(e);
                }), t.load = function(t) {
                  var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
                  o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
                  var i = document.getElementsByTagName("script")[0];
                  i.parentNode.insertBefore(o, i);
                };
              }
              drift.SNIPPET_VERSION = '0.3.1';
              drift.load('pyupvvckemp9');
            };
            
            setTimeout(function(){ 
                if (typeof window.jQuery !== 'undefined' && document.location.hostname !== 'www.moleculardevices.com.cn') {
                    LoadDriftWidget(); 
                 }
            }, 5000)
            </script>
