### ISSUE TITLE
[Products] Chevron icon to large for related products card

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#392]
Test on mobile: https://main--moleculardevices--hlxsites.hlx.live/products/cellular-imaging-systems/acquisition-and-analysis-software/in-carta-image-analysis-software

![IMG_7118](https://github.com/hlxsites/moleculardevices/assets/2643450/890f501e-1d9e-407a-a542-fc74db1c17ad)

**Comment by andreituicu** [comment]
My bad, sorry. I broke it when I merged https://github.com/hlxsites/moleculardevices/pull/315.
