### ISSUE TITLE
[Application] Absorbance page Metadata is missing

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#397]
On the `Absorbance` Application page, a lot of metadata is missing on import. E.g.
* Publication Date
* Category (manually added)
* Technology Type
* Thumbnail
* etc.

as opposed to other pages, like https://main--moleculardevices--hlxsites.hlx.page/applications/cellular-signaling-and-response.

**Comment by mhaack** [comment]
Fixed with full metadata imported again.
