### ISSUE TITLE
Metadata may be missing for the manually constructed pages

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#399]
The following pages have no metadata:

- [x] https://main--moleculardevices--hlxsites.hlx.live/applications
- [x] https://main--moleculardevices--hlxsites.hlx.live/lab-notes/blog
- [x] https://main--moleculardevices--hlxsites.hlx.live/lab-notes
- [x] https://main--moleculardevices--hlxsites.hlx.live/products
- [x] https://main--moleculardevices--hlxsites.hlx.live/products/accessories-consumables
- [x] https://main--moleculardevices--hlxsites.hlx.live/products/assay-kits
- [x] https://main--moleculardevices--hlxsites.hlx.live/products/additional-products
- [x] https://main--moleculardevices--hlxsites.hlx.live/technology
- [x] https://main--moleculardevices--hlxsites.hlx.live/products/culture-media-reagents

**Comment by mhaack** [comment]
All missing metadata has been added
