### ISSUE TITLE
[Category Pages] Product Compare Feature

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#400]
Implement product compare feature.
Possibly related to #[385](https://github.com/hlxsites/moleculardevices/issues/385) 

* Product cards have an extra checkbox to select for comparison
* When selecting products, a bar appear below showing the selected products with a button to begin the comparison
* Clicking the button opens a modal with the selected products and the specifications for comparison

<img width="1680" alt="Screenshot 2023-05-22 at 12 31 53" src="https://github.com/hlxsites/moleculardevices/assets/3651689/7a00f317-b4cf-4468-ba2f-81d4bdb03e3f">

<img width="1186" alt="Screenshot 2023-05-22 at 12 32 05" src="https://github.com/hlxsites/moleculardevices/assets/3651689/6ed03761-e7f2-4860-88fc-57f87712b36e">

Currently known pages:
* https://www.moleculardevices.com/products/microplate-readers
* https://www.moleculardevices.com/products/cellular-imaging-systems
* https://www.moleculardevices.com/products/additional-products
* https://www.moleculardevices.com/products/axon-patch-clamp-system

_There may be more. We need to check..._

Impl details:
* introduce page template "Product Compare" for pages we should have the compare feature
* the visibility of the "compare" checkbox on the card should be controlled by CSS and page template
* JS code for the compare banner and dialog should be bound to the template as well

**Comment by mhaack** [comment]
Details on the compare button display behavior. See https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1686745771698399?thread_ts=1686673497.907349&cid=C04QNDDUADT

For Franklin this means:
* manually add meta field `Specifications` with link to spec json URL
* update index config & sheet to index the new `Specifications`
* update code to render "Compare" box based on meta field
