### ISSUE TITLE
[Category Pages] Add View All/Products button in Hero

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#401]
Add View All/Products button in Hero to scroll to the card list
Known pages:
https://www.moleculardevices.com/applications
https://www.moleculardevices.com/products/assay-kits
https://www.moleculardevices.com/products/culture-media-reagents

<img width="1277" alt="Bildschirmfoto 2023-07-02 um 08 03 48" src="https://github.com/hlxsites/moleculardevices/assets/2643450/133d38c3-af22-46f2-8f69-dd7b9efab2ba">
<img width="1310" alt="Bildschirmfoto 2023-07-02 um 08 03 34" src="https://github.com/hlxsites/moleculardevices/assets/2643450/69181c74-5fd9-413c-9aef-86e7d54a31d3">

**Comment by mhaack** [comment]
+1 for post go-live or won't do at all as the button just scrolls down? This IMHO is missleading as the you would expect something more happen on a c2a button.

**Comment by andreituicu** [comment]
> won't do at all as the button just scrolls down

Personally that would've been my preference as well, but I thought that could be a post go live discussion. 🙂

**Comment by duynguyen** [comment]
Another place: https://www.moleculardevices.com/customer-breakthroughs

**Comment by mhaack** [comment]
Close it for now can be re-open on request.
