### ISSUE TITLE
[Products] Manually Import Series Subproducts

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#403]
Manually import all Series Subproducts into the `/products/series-products`.

The product data can be found at (_check if there are newer exports available_): [sheet](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B26CC8AF5-5E58-47C4-8A59-7F97BB7C5B26%7D&file=moldev-resources-sheet-05152023.xlsx&action=default&mobileredirect=true&cid=eed5ab2e-d768-47af-8c4c-a7c60a384585)

The target folder can be found [here](https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fmoleculardevices%2Fproducts%2Fseries%2Dproducts&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95)

Each row needs a dedicated word document where the we add the necessary metadata. You can check the following [example](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B417E5A26-A335-4574-AB20-5E50E695CB4D%7D&file=genepix-4000b-microarray-scanner.docx&action=default&mobileredirect=true)

**Comment by mhaack** [comment]
Done, all 27 Series products have been added and published.
