### ISSUE TITLE
Implement Application Note resource page

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#42]
Examples:

- https://www.moleculardevices.com/en/assets/app-note/br/assess-virus-neutralization-with-rapid-hts-friendly-assay
- https://main--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/assess-virus-neutralization-with-rapid-hts-friendly-assay

Tasks:

- [x] Overall content styling (might be mostly ok already)
- [x] PDF button styles incl. icon
- [x] Image alignment, width, margins
- [x] Image caption styling
- [x] Table caption styling

**Comment by lydiapuric** [comment]
WIP in https://github.com/hlxsites/moleculardevices/tree/application_node_page
