### ISSUE TITLE
[Service and Support] Create SpectraNet block

### ISSUE THREAD

**Issue by jose-correia** [hlxsites/moleculardevices#432]
https://www.moleculardevices.com/service-support

![Screenshot 2023-05-24 at 18 22 46](https://github.com/hlxsites/moleculardevices/assets/37300462/a6c2d450-55e9-41c4-9850-74b4650e1c07)

**Comment by mhaack** [comment]
I don’t this this needs an extra block can be a `column` block plus `image-list` as discussed.
