### ISSUE TITLE
[Product] Accessories and Consumables product cards should be filtered by path not category

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#444]
On the "Accessories and Consumables" products, the filter seems to behave differently than the filter in the original website.
Although all products with `subCategory="Accessories and Consumables"` have `category="Cellular Imaging Systems"`, the filter is based on the path (e.g. "FLIPR Pipette Tips" belongs to "FLIPR" filter).

https://main--moleculardevices--hlxsites.hlx.live/products/accessories-consumables

**Comment by andreituicu** [comment]
I propose to close this issue and keep just https://github.com/hlxsites/moleculardevices/issues/398
