### ISSUE TITLE
[Product] Allow custom description for variant items in "Order Options" tab for Assay Kits

### ISSUE THREAD

**Issue by lydiapuric** [hlxsites/moleculardevices#446]
The "Product Ordering Options" block allows an author to create a custom description for an item. 
This is a follow-up of issue #304.

Sample
https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/valitatiter#ordering-options
https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/gpcrs/catchpoint-cgmp-fluorescent-assay-kit#ordering-options
https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/clonedetect#ordering-options

**Comment by mhaack** [comment]
This can't be post go-live as we need the data to be imported !
