### ISSUE TITLE
[Integrity Compliance] Integrity compliance Pages Overall styling

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#479]
- [ ] Paddings and Margins
- [ ] Hero
- [ ] Text
- [ ] Headings
- [ ] Lists

_...more?_

Examples:
* https://franklin.moleculardevices.com/integrity-compliance/weee-information-italy
* https://franklin.moleculardevices.com/integrity-compliance/weee-information-bulgaria
* https://franklin.moleculardevices.com/integrity-compliance/weee-information-spain
* https://franklin.moleculardevices.com/integrity-compliance/weee-information-united-kingdom

**Comment by mhaack** [comment]
@andreituicu I suggest we close this one. The most of the styles are close, our headings are little more bold but the text and lists are ok. Only the tables on https://franklin.moleculardevices.com/integrity-compliance/weee-information-spain are different but I vote for not introducing an extra table style.

**Comment by andreituicu** [comment]
@mhaack no concern from my side. I opened it when we did the content check.
