### ISSUE TITLE
[Applications Cell Models] Style the titles and block margins

### ISSUE THREAD

**Issue by jose-correia** [hlxsites/moleculardevices#480]
Current state: https://franklin.moleculardevices.com/applications/3d-cell-models/organoids
https://franklin.moleculardevices.com/applications/cell-imaging
Original: https://www.moleculardevices.com/applications/3d-cell-models/organoids

**Comment by mhaack** [comment]
@jose-correia what is left here? Is that overlapping with #862?

**Comment by jose-correia** [comment]
@mhaack this is an issue that in the meantime was fixed by Duy i think, will close
