### ISSUE TITLE
[Applications Cell Counting] Hero and images are too big

### ISSUE THREAD

**Issue by jose-correia** [hlxsites/moleculardevices#481]
Franklin: https://franklin.moleculardevices.com/applications/cell-counting/cell-counter-a431-cells
Original: https://www.moleculardevices.com/applications/cell-counting/cell-counter-a431-cells

**Comment by paolomoz** [comment]
this is fixed as part of https://github.com/hlxsites/moleculardevices/pull/485

**Comment by mhaack** [comment]
This is fixed
