### ISSUE TITLE
[Integrity Compliance] Implement Location block

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#483]
Implement Location block.

Example page: https://www.moleculardevices.com/integrity-compliance/weee-information-spain

Alternatively the table block could be reused.

<img width="1157" alt="Screenshot 2023-06-01 at 11 42 10" src="https://github.com/hlxsites/moleculardevices/assets/3651689/6ddd2df9-f821-41da-bd8b-a492ce0b8dd4">

**Comment by mhaack** [comment]
Fixes using table: https://franklin.moleculardevices.com/integrity-compliance/weee-information-spain

**Comment by andreituicu** [comment]
Close enough :)
