### ISSUE TITLE
[Lab Notes] Import latest Lab Notes and update Teasers

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#489]
Latest Lab Notes published on the original website need to imported and the teasers on https://franklin.moleculardevices.com/lab-notes  need to be updated.

**Comment by mhaack** [comment]
@andreituicu which one would be good candidates for a test import? Maybe 2-3 blog docs? Also for #497

**Comment by andreituicu** [comment]
@mhaack For this particular issue, at the moment, https://www.moleculardevices.com/lab-notes shows these teasers:

* https://www.moleculardevices.com/lab-notes/cellular-imaging-systems/3d-biology-paradigm-shift-for-next-gen-drug-discovery
* https://www.moleculardevices.com/lab-notes/clone-screening/role-of-crispr-in-microbiome-engineering
* https://www.moleculardevices.com/lab-notes/cellular-imaging-systems/slas-2023-innovation-and-learning
* https://www.moleculardevices.com/lab-notes/microplate-readers/advantages-of-elisa-for-accurate-and-accelerated-drug-discovery

For https://github.com/hlxsites/moleculardevices/issues/497
* Has captions marked with `caption` class and reference list at the end of the page. https://franklin.moleculardevices.com/lab-notes/clone-screening/accelerated-production-of-monoclonal-antibodies-for-treatment-of-sars-cov-2-covid-19 

* Has captions marked with `text-caption` https://www.moleculardevices.com/lab-notes/clone-screening/covid-19-timeline-diagnostics-vaccines-antibody-discovery

going back to this issue, the delta of missing lab-notes can be seen on, because the lists are sorted by date
* https://www.moleculardevices.com/lab-notes/blog
* https://franklin.moleculardevices.com/lab-notes/blog

Currently, the missing blogs seem to be:
* https://www.moleculardevices.com/lab-notes/microplate-readers/advantages-of-elisa-for-accurate-and-accelerated-drug-discovery
* https://www.moleculardevices.com/lab-notes/cellular-imaging-systems/3d-biology-paradigm-shift-for-next-gen-drug-discovery
* https://www.moleculardevices.com/lab-notes/cellular-imaging-systems/slas-2023-innovation-and-learning
* https://www.moleculardevices.com/lab-notes/clone-screening/role-of-crispr-in-microbiome-engineering

**Comment by mhaack** [comment]
Import done with last export from 20th June
