### ISSUE TITLE
[Lab Notes] Vidyard videos incorrectly rendered

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#491]
The vidyard video on https://main--moleculardevices--hlxsites.hlx.page/lab-notes/cellular-imaging-systems/innovation-in-automated-high-content-imaging is rendered incorrectly, after the next paragraph and leaving a big empty space.

<img width="632" alt="Screenshot 2023-06-01 at 14 05 26" src="https://github.com/hlxsites/moleculardevices/assets/3651689/22841ccc-e4b9-46c0-8e2a-a08469f6e51d">

**Comment by mhaack** [comment]
This works now, closing.
