### ISSUE TITLE
[Customer Breakthrough] Hero should have 2 col layout > 991 px

### ISSUE THREAD

**Issue by lydiapuric** [hlxsites/moleculardevices#495]
See https://franklin.moleculardevices.com/en/assets/customer-breakthrough/dd/img/visikol
Original page: https://www.moleculardevices.com/en/assets/customer-breakthrough/dd/img/visikol

**Comment by andreituicu** [comment]
Duplicates https://github.com/hlxsites/moleculardevices/issues/424

**Comment by lydiapuric** [comment]
Closing as duplicate of #424
