### ISSUE TITLE
[Lab Notes] "Table of content" Style links don't work

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#496]
Table of content style links do not work, because the headers have different IDs autogenerated by Franklin, so old links are not good anymore.

<img width="497" alt="Screenshot 2023-06-01 at 14 32 16" src="https://github.com/hlxsites/moleculardevices/assets/3651689/b117aa53-6df7-496e-89a0-dcf0a092a543">

<img width="790" alt="Screenshot 2023-06-01 at 14 32 06" src="https://github.com/hlxsites/moleculardevices/assets/3651689/c23c8fa4-19c3-4cb3-a770-92cb5654f01d">

Example:
https://franklin.moleculardevices.com/lab-notes/clone-screening/accelerated-production-of-monoclonal-antibodies-for-treatment-of-sars-cov-2-covid-19

**Comment by mhaack** [comment]
This is fixed by https://github.com/hlxsites/moleculardevices/pull/640
