### ISSUE TITLE
[Lab Notes] Not all captions are marked as emphasised 

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#497]
Example:

https://franklin.moleculardevices.com/lab-notes/clone-screening/accelerated-production-of-monoclonal-antibodies-for-treatment-of-sars-cov-2-covid-19

Text or lists marked with either:
* `caption` or `text-caption` classes

should be emphasised.
<img width="809" alt="Screenshot 2023-06-01 at 14 36 06" src="https://github.com/hlxsites/moleculardevices/assets/3651689/796ae5b6-0c06-4acf-8c3d-824bebcd4e53">

<img width="777" alt="Screenshot 2023-06-01 at 14 35 59" src="https://github.com/hlxsites/moleculardevices/assets/3651689/906f2f66-28c1-4db1-9664-be52925bd759">

<img width="829" alt="Screenshot 2023-06-01 at 14 35 25" src="https://github.com/hlxsites/moleculardevices/assets/3651689/2dcf7d83-b601-4967-9d6d-7a11d8bec217">

**Comment by andreituicu** [comment]
@mhaack I think I contributed the code for this in the importer, but we haven't reimported the blogs since. We might need to do it, because there is a lot of them.

We anyway need to do it for https://github.com/hlxsites/moleculardevices/issues/489.

**Comment by mhaack** [comment]
@andreituicu this should be fixed I think.

**Comment by alexcarol** [comment]
It looks fixed, closing.
