### ISSUE TITLE
[Products] Ceros embeds not displayed

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#504]
Ceros embeds using embed blocks do not load on overview tab of

* https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-confocal-ht-ai
* https://franklin.moleculardevices.com/resources/interactive-demo/cloneselect-imager-fl
* https://franklin.moleculardevices.com/resources/interactive-demo/imagexpress-pico-automated-cell-imaging-system-interactive-demo
* https://franklin.moleculardevices.com/products/3d-biology
* plus all other interactive-demo pages

**Comment by andreituicu** [comment]
Probably related to https://github.com/hlxsites/moleculardevices/issues/423
