### ISSUE TITLE
[Resources Tab] Missing resource

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#511]
https://franklin.moleculardevices.com/products/assay-kits/elisa/catchpoint-simplestep-elisa-kits#resources > should have one entry https://main--moleculardevices--hlxsites.hlx.page/en/assets/app-note/reagents/faster-elisa-results-with-catchpoint-simplestep-elisa-kits in the resources sections, compare with https://www.moleculardevices.com/products/assay-kits/elisa/catchpoint-simplestep-elisa-kits#Resources

The meta data of the application note page is correct.

**Comment by alexcarol** [comment]
@mhaack this looks fixed, could you confirm?

**Comment by mhaack** [comment]
Yes confirm this is fixed.
