### ISSUE TITLE
[Events] Reimport news to used product carousel

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#523]
Where: https://main--moleculardevices--hlxsites.hlx.page/events/sbi2-virtual

What: There is featured products carousel on some event pages. However products are listed as simple links for now, without carousel.
The featured products carousel (mini) used on this page is similar to the one on Customer breakthrough pages. We could reuse them.

**Comment by mhaack** [comment]
As discussed with @duynguyen this should be changed to "Product Carousel (no compare)" as it is the same product carousel like on the category pages with the compare function.

**Comment by mhaack** [comment]
Done
