### ISSUE TITLE
[Technology] Missing related Product

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#526]
Missing related product.  Could be related to https://github.com/hlxsites/moleculardevices/issues/403 , as the document for ID5 is currently missing. Still would be good to check back after the product is imported to make sure the problem is fixed.

Example:
https://franklin.moleculardevices.com/technology/western-blot#related-products-services
https://www.moleculardevices.com/technology/western-blot#relatedproducts

**SpectraMax iD5 Multi-Mode Microplate Reader** is listed as a related product in the word document, but does not appear in the rendered `Related Products` block. Most likely it has to do with the fact that it is a series product.

Original
<img width="931" alt="Screenshot 2023-06-01 at 17 49 24" src="https://github.com/hlxsites/moleculardevices/assets/3651689/ed807c5e-9ad0-4121-884c-9200231569ff">

Franklin
<img width="930" alt="Screenshot 2023-06-01 at 17 51 38" src="https://github.com/hlxsites/moleculardevices/assets/3651689/1772d4fb-90f4-43b9-ab9b-ceb5cbce639b">

**Comment by andreituicu** [comment]
On https://main--moleculardevices--hlxsites.hlx.page/technology/time-resolved-fluorescence-trf-tr-fret-htrf#related-products-services there is actually no product shown.

**Comment by andreituicu** [comment]
Should be fixed at the moment, I added H1s for all series products.

**Comment by mhaack** [comment]
Why are h1 needed if we have Titel in meta data?

**Comment by andreituicu** [comment]
@mhaack there is a lot of code working with `h1`s. Sometimes it falls back to title, if `h1` is empty, but I think it is safer to have the h1s, especially cards and carousels mostly are looking for the h1s first as they match the exact text from the original website, so it is more performant.

In this case, the filter was based on h1 only: https://github.com/hlxsites/moleculardevices/blob/main/blocks/related-products/related-products.js#L15 . I could've added a fallback to title there as well, but it would be more ineficient.

**Comment by mhaack** [comment]
Not sure if I really like the current approach as the default Franklin approach is sort of opposite. Not 100% but sort of. Here it takes H1 first (for page title) and meta data second. 

So having a heading one in the doc’s is perfectly fine. But the way we use it in index and code I’m not sure. My preference would be getting rid of ‘h1’ in index totally. As that feels more “standard”. 

Let have a chat tomorrow.

**Comment by mhaack** [comment]
Two more general thoughts on this, the more I think about it:

> Sometimes it falls back to title, if h1 is empty,
1. I think we should have this consistent across all blocks. 

2. Think this is too complicated for the average author. I know we did not question it because it was that was before. We should not forget about ease of use for the authors.

**Comment by andreituicu** [comment]
I will start by saying that I don't have necessarily a preference

Unfortunately, there are a lot of cases where the title and h1 don't match and the original website uses the h1 information for  cards titles and breadcrumbs (and for sure other uses cases which I'm missing now on the spot). If we wanted to remove the h1s from the index, we would need to store this info in yet another metadata field and index that one, as it is not in anything else we store/index.
