### ISSUE TITLE
Fix "key features" section in cloneselect

### ISSUE THREAD

**Issue by alexcarol** [hlxsites/moleculardevices#528]
Carousel is probably the right approach (it was auto-imported as embed, content changes will be needed)

Current: https://franklin.moleculardevices.com/cloneselect-single-cell-printer-ceros-demo
Expected: https://www.moleculardevices.com/cloneselect-single-cell-printer-ceros-demo

**Comment by mhaack** [comment]
On the original this page is gone and now redirects to search results. @alexcarol please double check, then delete our page as well and add a redirect.

**Comment by alexcarol** [comment]
Confirmed and done, thanks for pointing it out.
