### ISSUE TITLE
Integrate Component Library into Sidekick

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#53]
For the authors we should have some kitchen sink aka. block collection document to showcase all the content centric content elements and blocks.

See https://github.com/adobe/franklin-sidekick-library
Sample Sidekick Library implementation https://main--rosalind-boilerplate--dylandepass.hlx.live/tools/sidekick/library.html?plugin=blocks

**Comment by andreituicu** [comment]
We can leverage:
https://github.com/adobe/helix-sidekick-extension
https://main--rosalind-boilerplate--dylandepass.hlx.live/tools/sidekick/library.html?plugin=blocks

To create nice documentation and easy to discover styling options and blocks.

**Comment by andreituicu** [comment]
It would be good to check that we have documented as well https://live-md30.pantheonsite.io/web-design-style-guide/web-design-style-guide
