### ISSUE TITLE
[Technology] Missing Resources

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#540]
In the `Resources` tab there are missing items, which are present on the original website.

Example: 
* https://www.moleculardevices.com/technology/time-resolved-fluorescence-trf-tr-fret-htrf#Resources shows **22 resources**
* https://main--moleculardevices--hlxsites.hlx.page/technology/time-resolved-fluorescence-trf-tr-fret-htrf#resources shows **only 8 resources.**

**Comment by mhaack** [comment]
@duynguyen we should switch the resources filtering to the identifier now. https://main--moleculardevices--hlxsites.hlx.page/technology/time-resolved-fluorescence-trf-tr-fret-htrf#resources is now empty as we had the issue with the comma in the title. The new identifier does not have the comma issue any more.

**Comment by mhaack** [comment]
This was fixed with the latest import and re-published. Just checked the number of resources is the same now.
