### ISSUE TITLE
[Video Gallery] Support "filter" style variant of hero

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#549]
![Screenshot 2023-06-02 at 17 28 22](https://github.com/hlxsites/moleculardevices/assets/2643450/3daec279-2e2d-4444-adba-7717e78dd8a5)

Pages:

- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/axon-patch-clamp
- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/cellular-imaging-systems
- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/clone-screening
- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/microplate-readers

**Comment by andreituicu** [comment]
We could reuse the `card-list-filter` if we wanted for this. We already have a variant which overlays itself over the hero on:

https://franklin.moleculardevices.com/lab-notes
https://franklin.moleculardevices.com/lab-notes/blog

**Comment by mhaack** [comment]
+1
