### ISSUE TITLE
[Product] pages may have high TBT and low LHS

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/moleculardevices#555]
Tested on several pages. TBT > 350-500ms and LHS between 60 and 90

- https://main--moleculardevices--hlxsites.hlx.page/products/clone-screening/microbial-screening/qpix-400-series-microbial-colony-pickers
- https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/valitatiter
- https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

**Comment by andreituicu** [comment]
Is this issue different from https://github.com/hlxsites/moleculardevices/issues/430 ?

**Comment by mhaack** [comment]
Closing as this is duplicated with #430
