### ISSUE TITLE
[TechDebt] [Shopify Integration] CORS issue in add cart

### ISSUE THREAD

**Issue by lydiapuric** [hlxsites/moleculardevices#561]
Tested https://franklin.moleculardevices.com/products/assay-kits/igg-quantification-assays/valitatiter#ordering-options and in the console I see a CORS issue for add cart. The action is successful and reading the cart is successful.

ordering-options.js:71 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://shop.moleculardevices.com/cart/add.js?id=42181000429745&quantity=1&_=1685912558873&callback=addToCart with MIME type text/javascript. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by andreituicu** [comment]
As far as I've seen, this also present on the original website. 
That is of course not to say we shouldn't try to fix it, just adding the information here for context. 

<img width="1171" alt="Screenshot 2023-06-04 at 23 49 48" src="https://github.com/hlxsites/moleculardevices/assets/3651689/913345fe-caa9-4a63-915f-f3ca9e9e351a">

**Comment by lydiapuric** [comment]
@andreituicu marked this issue correctly as enhancement. @mhaack I am considering to close this issue in this case. WDYT?

**Comment by andreituicu** [comment]
@lydiapuric my personal view would be that they should invest in doing https://github.com/hlxsites/moleculardevices/issues/562 , but would like to hear @mhaack opinion too.

**Comment by mhaack** [comment]
Discussed this with @andreituicu quickly this mooring, thanks @andreituicu for documenting #562. We know the current solution is sub optimal, but it is the same like on the old page, so at least it is not making things worse. I'm ok we resolve it for now if we have all the pieces working.

**Comment by andreituicu** [comment]
Closing as discussed above, since this works identically as the previous drupal website. Keeping https://github.com/hlxsites/moleculardevices/issues/562 for the moldev team to address it in the future, by properly configuring CORS headers in shopify.
