### ISSUE TITLE
[TechDebt] [Shopify] Migrate Shopify integration away from usage of JSONP 

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#562]
### Context

On the new Franklin site we have migrated the Shopify cart interactions as they were performed on the original Drupal website using JSONP, as part of https://github.com/hlxsites/moleculardevices/pull/558

Original calls (snippets):

```javascript
    jQuery('.add_to_cart').click(function() {
        var e = jQuery(this).attr('data-variant-id')
          , a = jQuery('#' + e).text();
        if (a != '') {
            jQuery.ajax({
                dataType: 'jsonp',
                url: 'https://shop.moleculardevices.com/cart/add.js?id=' + e + '&quantity=' + a,
                type: 'POST',
                crossDomain: !0,
                success: function(t) {}
            })
```

```javascript
        jQuery.ajax({
            url: '//shop.moleculardevices.com/cart.json',
            dataType: 'jsonp',
            type: 'GET',
            success: function(t) {
               ...
            },
            error: function(t, e, a) {
              ...
            }
```

including the known issue of CORS warning in the console: https://github.com/hlxsites/moleculardevices/issues/561

The migration in that sense was 1:1.

### Problem

JSONP poses a number of security concerns and should no longer be used.

### Solution

Migrate away from JSONP using one of the following alternatives:

1. See if shopify allows setting the correct CORS headers and switching from JSONP requests to regular `fetch` requests (https://shopify.dev/changelog/storefront-api-allows-for-cross-origin-resource-sharing suggests it might, but I am not an expert in the shopify API)
2. Setup a proxy for the shopify API under the moldev domain, correctly set the CORS headers in the proxy and switch to using `fetch` requests, instead of JSONP

**Comment by mhaack** [comment]
Closing as defered, can be re-opend if needed later.
