### ISSUE TITLE
Use title only for query

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#563]
These blocks should be updated:
- https://github.com/hlxsites/moleculardevices/blob/main/blocks/related-products/related-products.js#L15-L20
- https://github.com/hlxsites/moleculardevices/blob/main/blocks/latest-resources/latest-resources.js#L25-L34
- https://github.com/hlxsites/moleculardevices/blob/main/blocks/resources/resources.js#L46-L54

**Comment by mhaack** [comment]
This also relates to #540

**Comment by duynguyen** [comment]
already fixed
