### ISSUE TITLE
[Lab Notes] Overview page should list 3 recent posts

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#608]
Where: https://franklin.moleculardevices.com/lab-notes

Under recent posts, 3 latest blogs should be listed. Currently there are only 2.

**Comment by paolomoz** [comment]
@andreituicu @duynguyen if this is a duplicate should we close it?

**Comment by andreituicu** [comment]
@paolomoz I usually just close them in pair when they are fixed, just so we don't loose track of the fact that this is for example mentioned also by the customer and the xcel needs to be updated.

**Comment by mhaack** [comment]
Import done with last export from 20th June
