### ISSUE TITLE
[Lab Notes] ToC anchor links not working

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#609]
Where:
- https://franklin.moleculardevices.com/lab-notes/cellular-imaging-systems/advanced-technology-for-automated-3d-biology-workflows-slas-europe-2022#compound_screening_and_high_content_imaging
- https://franklin.moleculardevices.com/lab-notes/cellular-imaging-systems/advanced-technology-for-automated-3d-biology-workflows-slas-europe-2022#organ_on_a_chip_assay
- https://franklin.moleculardevices.com/lab-notes/cellular-imaging-systems/7-tips-for-optimizing-your-3d-cell-imaging-and-analysis-workflow#Usemicroplates

Table of content anchor links don't go to the expected sections.

**Comment by mhaack** [comment]
@duynguyen i think this is the same as #602 wdyt? We have a specific solution for the hero already but since that links can be everywhere we should have a generic solution.

**Comment by mhaack** [comment]
Actually I checked the links again. This must be fixed in content. The hash value is wrong/old since Franklin has a different rule for I’d generation.

**Comment by mhaack** [comment]
The importer must be able to find out where the hash link is linking to (that should be possible if it is on the same page), get the (heading) content, generate a new hash and rewrite the link.
