### ISSUE TITLE
[Product] RFQ must work with "bundle" parameter

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#627]
Make use the bundle request parameter is used by the RFQ for.

- if no bundle, only pid is present > always use the product title
- if `bundle` parameter is present use the bundle title, fall back to product title if bundle title does not exist

Sample to test with: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers

**Comment by dev-rajneeshkumar** [comment]
Yes @mhaack this is the correct scenario though for some cases we have custom title as well. W ill share those links  with you .
