### ISSUE TITLE
CTA Buttons with Link

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/moleculardevices#65]
Implement call to action buttons in the form of links.
These CTA Buttons take the user to a new page, with the correct query parameters (e.g. Request Type, Product ID, Category ID) and usually a HubSpot form.
The link query parameter information should be taken from the page metadata, so authors don't have to manually input each link.

Examples:
* https://www.moleculardevices.com/products/microplate-readers
* https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

<img width="1680" alt="Screenshot 2023-03-13 at 16 05 00" src="https://user-images.githubusercontent.com/3651689/224742367-df38def4-8eb0-4728-baf2-1e3bf53e760c.png">

<img width="1680" alt="Screenshot 2023-03-13 at 16 06 56" src="https://user-images.githubusercontent.com/3651689/224742966-940cef04-a8f3-4dec-8829-884801c33ebb.png">

**Comment by mhaack** [comment]
This is already implemented.
