### ISSUE TITLE
Useless scrollbar in get-in-touch form

### ISSUE THREAD

**Issue by johan-t** [hlxsites/moleculardevices#659]
When opening the get-in-touch form a scrollbar appears, because the element is to big. 

<img width="667" alt="Screenshot 2023-06-19 at 09 56 05" src="https://github.com/hlxsites/moleculardevices/assets/30388999/68ced8be-0c1f-4244-9fb9-c8ff7a02ce17">

**Comment by Sky-De** [comment]
Assign this to me
Ty
