### ISSUE TITLE
[Blog] Recent post section is broken

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#676]
URL: https://main--moleculardevices--hlxsites.hlx.page/lab-notes

![Screenshot 2023-06-20 at 17 43 38](https://github.com/hlxsites/moleculardevices/assets/2643450/c6e0f16a-78e1-4a42-91ed-20b21f482da7)

**Comment by andreituicu** [comment]
This is broken because of the missing metadata in one of the blog pages in the latest import.
I will try to add some checks to avoid NPEs and maybe add some defaults if possible, but it should ultimately be fixed by adding the missing metadata on blogs.
