### ISSUE TITLE
[Product] Store "Add to Cart" option is missing in US hero banner

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#711]
The "Add to Cart" option is not available on the "Ordering Options" tab and in the banner section for US.

**Comment by johan-t** [comment]
Current progress: The basic form is functional, you can select options and variants. The conditions for styling of the variant drop down if nothing is selected in the options drop down is also in place, the quantity indicator also works.
Whats still left to do: Right now the data for the products and variants is only simulated, but needs to be replaced with the real data coming from the API call. The price calculation of the products and their variants needs to be implemented and the add to cart functionality.
