### ISSUE TITLE
Implement Column layout options

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#72]
Implement the following column layout options:

- [x] `Columns (layout 33 66)` - sample: https://main--moleculardevices--hlxsites.hlx.page/lab-notes/cellular-imaging-systems/3d-organoids-and-automation-of-complex-cell-assays
- [x] `Columns (layout 66 33)` - sample: https://main--moleculardevices--hlxsites.hlx.page/lab-notes/general/lab-automation-inside-access-from-our-subject-matter-expert
- [x] `Columns (layout 25 75)` - sample: https://main--moleculardevices--hlxsites.hlx.page/lab-notes/cellular-imaging-systems/case-study-assay-ready-patient-derived-organoids-and-high-throughput-3d-imaging
- [x] `Columns (layout 75 25)`
- [x] `Swap` option for mobile used on some blog pages

**Comment by andreituicu** [comment]
Additionally added 

`Columns (layout 60 40)` and `Columns (layout 40 60)` both can be found in https://www.moleculardevices.com/lab-notes/general/celebrating-art-science-di-interview-daniele-tortorella
