### ISSUE TITLE
[Applications] add separator to covid19 update page

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#740]
https://main--moleculardevices--hlxsites.hlx.page/applications/coronavirus-research/covid19-company-update

There are separators between sections.

**Comment by mhaack** [comment]
Lets use "horizontal line" here and style it correctly. https://github.com/hlxsites/moleculardevices/blame/9e5843a3cf7bf55388cd935bbff72b3574237b0c/styles/styles.css#L659

**Comment by duynguyen** [comment]
fixed by #750
