### ISSUE TITLE
[RFQ] For customer breakthrough display the related products

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#783]
From https://franklin.moleculardevices.com/en/assets/customer-breakthrough/br/national-horizons-centre
To https://franklin.moleculardevices.com/quote-request?mdcmp=7014u000001x6quAAA&pid=national-horizons-centre-uses-the-spectramax

Current: we show the title, like for other product RFQ as well
Expected: for customer breakthrough type show the products from the related products meta data

**Comment by AhmedMustafa2201** [comment]
@mhaack can you please explain it a bit further?

**Comment by mhaack** [comment]
This is about special handling of customer breakthrough doc's for RFQ. I'm working on this right now.
