### ISSUE TITLE
remove grey background for wave section

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#785]
https://main--moleculardevices--hlxsites.hlx.page/products/gxp-compliance-solutions

the background of Citations carousel is grey, even though it's not set in content.

culprit: https://github.com/hlxsites/moleculardevices/blob/main/styles/styles.css#L630

**Comment by duynguyen** [comment]
might need to check leadership page because git blame links back to it where this code was added.

**Comment by AhmedMustafa2201** [comment]
could you please assign this issue to me?

**Comment by AhmedMustafa2201** [comment]
@duynguyen could you please review my PR for this issue?
