### ISSUE TITLE
[Hero] Support for region specific info & buttons

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#792]
Some Hero's have region specific content, like product finder hero:
https://www.moleculardevices.com/product-finder vs. https://de.moleculardevices.com/product-finder vs. https://it.moleculardevices.com/product-finder

Or some customer break through: https://main--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/br/university-of-rouen

This also relates to #744 and #460

**Comment by andreituicu** [comment]
Heros mentioned in this issue are fixed. The ones from https://github.com/hlxsites/moleculardevices/issues/744 and https://github.com/hlxsites/moleculardevices/issues/460 will be fixed in their respective issues.
