### ISSUE TITLE
[Product] Related products should be carousel on mobile

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#819]
For all the pages, cards under related products should be in a carousel in mobile. They are stacked today and also stacked on the old page (which is a bug according to Meghna). So we keep this as a new requirement short fixed after go-live.

Sample:
* https://main--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-confocal#related-products-services
* https://main--moleculardevices--hlxsites.hlx.page/applications/food-and-beverage#related-products-services

**Comment by alexcarol** [comment]
Is this not done, though? I see that for example in this page it's implemented: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers (Related products and services)

**Comment by mhaack** [comment]
This is a different page & block. The issue is about the product pages like https://main--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-confocal#related-products-services sorry will add some links to the description
