### ISSUE TITLE
Align captions and remove bold 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#838]
Center align and remove bold for captions under images/videos.
https://franklin.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/in-carta-image-analysis-software

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4cbe63f3-43eb-44cc-8c57-1a6820c45d4c)

**Comment by duynguyen** [comment]
alignment fixed by #852 . Bold text has to be fixed in content. IMO this is a good exercise for "potential author" .
