### ISSUE TITLE
Fix styling issues in product pages

### ISSUE THREAD

**Issue by alexcarol** [hlxsites/moleculardevices#851]
Example page: https://main--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/acquisition-and-analysis-software/in-carta-image-analysis-software

This potentially affects more product pages, so it requires some investigation as to which pages should be affected.

- [x] Alignment and font of captions - style bug
- [x] Alignment of buttons - maybe content issue
- [x] Main title wrapping - works as designed

**Comment by duynguyen** [comment]
alignments of buttons - what customer reported.
<img width="1176" alt="Screen Shot 2023-07-07 at 10 55 15" src="https://github.com/hlxsites/moleculardevices/assets/601729/f24d85c1-059b-4442-91f5-8de00b473085">
