### ISSUE TITLE
Improve page performance

### ISSUE THREAD

**Issue by alinarublea** [hlxsites/moleculardevices#857]
Improving page performance by using party town  to load GTM and research if its possible to be used also for page rendering, in case not research other tools or practices to reduce the tbt of the page.

**Comment by andreituicu** [comment]
Related to https://github.com/hlxsites/moleculardevices/issues/430, https://github.com/hlxsites/moleculardevices/issues/555

**Comment by andreituicu** [comment]
Closing, keeping https://github.com/hlxsites/moleculardevices/issues/430
