### ISSUE TITLE
Fix "Save time and money.." title for these pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#858]
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers#overview
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-mini-reader
https://franklin.moleculardevices.com/products/microplate-readers/washers/aquamax-microplate-washer
https://franklin.moleculardevices.com/products/assay-kits/igg-quantification-assays/valitatiter

The title "**Save time and money with a microplate reader and washer bundle**" should be center aligned, and have a font size of 70px with blue color. Also, add a little space above the bullets here. 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ecc88397-eb2e-40ae-99c1-3c7ad451f717)

Add line separators above "Assure data integrity ...." title 
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers#overview
https://franklin.moleculardevices.com/products/microplate-readers/washers/aquamax-microplate-washer

For SpectraMax Mini, the text and image is incorrect for this section, please update as it is on live. 
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-mini-reader
https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-mini-reader

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f69bf272-af77-4a07-af5c-71ac2a52e11c)

https://franklin.moleculardevices.com/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution-com
Update font size for "Bundle your 3D biology workflow solution and save!" to be  70px with blue color and Sub title to be h4:30px

Fix title and subtitle font size for these sections as well

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8a763e49-451c-4581-9db6-befae3f99904)

Title- h3:40 px
Subtitle- h4:30 px

**Comment by MeghnaTewari** [comment]
Another URL for the same issue. Fix "Bundle. Optimize. Save. ", 70px with blue color, center-aligned 
https://franklin.moleculardevices.com/products/clone-screening/single-cell-isolation/dispencell-single-cell-dispenser

**Comment by alexcarol** [comment]
I can't find the "save time and money..." title (or one with similar styling) for https://franklin.moleculardevices.com/products/assay-kits/igg-quantification-assays/valitatiter, could you point out where it should be?

**Comment by MeghnaTewari** [comment]
@alexcarol Forgot to mention, need to fix the spacing for this URL.

Please add a little space in both places and left align bullets with the text 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/571bfca2-a745-4dc5-915f-78dce7bd6e2a)
