### ISSUE TITLE
Fix clone screening page issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#860]
https://franklin.moleculardevices.com/products/clone-screening#qpix-400-series

- [x] On the customer breakthrough carousel, the images should be in a circle, globally
- [x] For the products section, the title should be h3: 40px and the subtitle h4: 30px.
Like this - 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fff1c149-98b8-482f-89a3-11a1a6dbfb8f)

- [x]  For the "Applications & Research" and "Related Products & Services" sections, left align the titles and text coming in the cards, globally.

**Comment by MeghnaTewari** [comment]
@alexcarol Yes, you are right.

1. Another example page for my 1st point - https://franklin.moleculardevices.com/products/3d-biology

2. More example pages For my last point
https://franklin.moleculardevices.com/products/cellular-imaging-systems
https://franklin.moleculardevices.com/products/3d-biology
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4c2072bf-8091-469f-aa66-5d6cf62bed55)

https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9da71ea3-2817-4378-b9ac-770789bd7e38)

https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1df0c944-d494-4b40-9599-c692d7e5a5ed)

**Comment by MeghnaTewari** [comment]
> Could you clarify what you mean by "globally" in the first and last points? Do you have any other examples of pages where this should be applied too (if that's the case)?

@alexcarol This point is not done. Can you please check? The title and the text are still center-aligned for me.
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9dbfbf6f-5b93-4cd0-b767-13da6b6b524b)

**Comment by alexcarol** [comment]
@MeghnaTewari it should be fixed now, could you check again?

**Comment by MeghnaTewari** [comment]
fixed now. Thanks.
