### ISSUE TITLE
[Geo Sites] 404 error on video gallery

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#868]
https://dede-hlxsites-moleculardevices.onelink-translations.com/video-gallery
https://frfr-hlxsites-moleculardevices.onelink-translations.com/video-gallery

**Comment by mhaack** [comment]
These pages have special rules redirection to https://www.moleculardevices.com/video-gallery-landing/de and https://www.moleculardevices.com/video-gallery-landing/fr we need to add them in Franklin as well and make sure they are not indexed

**Comment by mhaack** [comment]
Landing pages have been added and are working, however sub pages like https://dede-hlxsites-moleculardevices.onelink-translations.com/video-gallery/microplate-readers still return 404

**Comment by mhaack** [comment]
@dev-rajneeshkumar please clarify and take core of the rules for de/fr for the video sub pages.

**Comment by mhaack** [comment]
Closing this one as the sub video gallery pages have been fixed and work now.
