### ISSUE TITLE
[Products] Broken product comparison table and UI issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#873]
https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers

Fix the specifications table on both the pages.

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7e538941-6052-478f-bcae-b34c727dbdd3)

Also,
1. Fix the large h2 titles 
2. Under "applications and assays" fix bullets alignment, add arrow icon and fix spacing between the TOC bullets
3. Centre align the titles
4. Add anchor link on view products CTA in the banner

https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b792a615-bb02-4634-9dc6-912da029963b)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/79118c7b-66d5-4535-b576-9a1805995380)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/22835608-51fc-408e-bd40-a659f8ef08f8)

https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/770c5dbb-b83b-421e-894f-bd92b572cbdc)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f3ad6903-409d-4503-a5ab-602349e9587e)
Reduce img size 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/93b46ae8-c5c0-48a5-84dd-b9bf3055149e)

https://franklin.moleculardevices.com/products/microplate-readers/fluorescence-readers
https://franklin.moleculardevices.com/products/microplate-readers/luminescence-readers

Reduce font size and make it blue 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ce9a2e5c-6d06-43a4-a948-7f50447d44c7)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c5056f4a-7b1a-42c7-80c2-8be34c27ddf1)

**Comment by MeghnaTewari** [comment]
For the "ImageXpress HCI system comparison", please make the order of products like the below screenshot from live. Also please keep the same title

https://franklin.moleculardevices.com/products/cellular-imaging-systems

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/0381f348-07d5-4a94-856e-56cca0281d7d)

**Comment by duynguyen** [comment]
@MeghnaTewari we can try to keep the same order of products.
Re. title: the titles on original page were handcrafted and not similar to anywhere else. In the new table we retrieve them from the product page. As agreed with @dev-rajneeshkumar and @kapildhiman before, we take this title from product page as the source of truth.

**Comment by MeghnaTewari** [comment]
@duynguyen Any update on the comparison table issue? They are severely broken 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a2ef0167-f2e8-48bc-a50c-454932e693f6)
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers
https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers

**Comment by duynguyen** [comment]
@MeghnaTewari yes because content was not published. I just did and table seems to display fine now.

**Comment by MeghnaTewari** [comment]
@alinarublea addressing a couple of common issues for both the tables - 

https://issue-873--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers
https://issue-873--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers

1. Please remove extra space from here 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8eb10f3d-9a5a-4cf1-b1f7-0070de9efe41)

2. Please increase the width to add some more space on the right  
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2bc64ef1-7b7f-4458-88e4-043bac509c09)

3. Add a little space above the product images 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2b68bc2f-44d9-4c8b-a80b-f21d07f70b81)

4. Fix the URL of id3 and id5, showing 404

https://issue-873--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ea45b495-4a24-468b-827a-272d6c0f8f99)

5. Fix the URL for ABS, showing 404

https://issue-873--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d02479ed-dde5-4e20-8bd0-0f96733eb717)

**Comment by duynguyen** [comment]
@MeghnaTewari fixed 4 and 5

**Comment by alinarublea** [comment]
@MeghnaTewari can you check again should be looking a little better

**Comment by MeghnaTewari** [comment]
Yes, looks better!

Can we have the default scroll bar set to the left when the page is opened?

Like this 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d441336f-e811-4842-a940-84826dcbd5e6)

Please remove some more space
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/43c8e655-e0f9-467d-bd2f-31566b0618bf)

**Comment by alinarublea** [comment]
@MeghnaTewari the space should look better now, but the scroll is still starting from the other direction

**Comment by MeghnaTewari** [comment]
@duynguyen @alinarublea I just noticed that this issue is marked completed but styling issues on category pages are still not fixed. 

cc @mhaack 

> Also,
> 
> 1. Fix the large h2 titles
> 2. Under "applications and assays" fix bullets alignment, add arrow icon and fix spacing between the TOC bullets
> 3. Centre align the titles
> 4. Add anchor link on view products CTA in the banner
> 
> https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers
> 
> ![image](https://user-images.githubusercontent.com/138755144/252145836-b792a615-bb02-4634-9dc6-912da029963b.png) ![image](https://user-images.githubusercontent.com/138755144/252145874-79118c7b-66d5-4535-b576-9a1805995380.png) ![image](https://user-images.githubusercontent.com/138755144/252146058-22835608-51fc-408e-bd40-a659f8ef08f8.png)
> 
> https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers
> 
> ![image](https://user-images.githubusercontent.com/138755144/252146218-770c5dbb-b83b-421e-894f-bd92b572cbdc.png) ![image](https://user-images.githubusercontent.com/138755144/252146291-f3ad6903-409d-4503-a5ab-602349e9587e.png) Reduce img size ![image](https://user-images.githubusercontent.com/138755144/252146241-93b46ae8-c5c0-48a5-84dd-b9bf3055149e.png)
> 
> https://franklin.moleculardevices.com/products/microplate-readers/fluorescence-readers https://franklin.moleculardevices.com/products/microplate-readers/luminescence-readers
> 
> Reduce font size and make it blue
> 
> ![image](https://user-images.githubusercontent.com/138755144/252146483-ce9a2e5c-6d06-43a4-a948-7f50447d44c7.png) ![image](https://user-images.githubusercontent.com/138755144/252146657-c5056f4a-7b1a-42c7-80c2-8be34c27ddf1.png)

**Comment by alinarublea** [comment]
@MeghnaTewari I added more space to the flourescence and luminescence pages, and I also opened this pr for the bullet points if you can check https://github.com/hlxsites/moleculardevices/pull/998 .

**Comment by MeghnaTewari** [comment]
@alinarublea 

1. Please add arrow icons for all the application titles and apply bold 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4e1acafd-45be-49e6-b22e-221b7b826ed2)

2. Move AlphaScreen/AlphaLISA below Western Blot
3. Please align these 3 titles together so it looks better 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2c1abead-4823-4825-bce0-bfa5c6b71c62)
