### ISSUE TITLE
Mega menu issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#877]
1. Fix Multi mode readers link under products, it is going to the i3x page
2. Remove "BioAssemblyBot 400" from  CELLULAR IMAGING SYSTEMS > LAB AUTOMATION & CUSTOMIZATION 
3. Under ACCESSORIES & CONSUMABLES > CLONE SCREENING remove CloneSelect Single-Cell Printer Cartridges and add "QPix Tips" https://franklin.moleculardevices.com/products/clone-screening/accessories-consumables/qpix
4. Under Innovations, remove extra space and fix the alignment 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c456372b-fc30-4e90-8e98-22c7f9b35042)

5. Remove extra space to maintain consistency 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5818388f-46e0-40c3-a3c4-b7b759f7e94e)

6. Remove the outline from "SPECTRANET CUSTOMER PORTAL" add space above Europe, and add "Mon to Fri 8am - 5pm GMT" below the number
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ef3367b3-683d-4065-bc8a-8bb398174992)
 
7. Remove the outline from Read More buttons, under **Events and Newsroom** and left align it
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9955c787-4bd3-4e53-b209-d6d3eef1f692)

8. In the Leadership submenu, replace this image with the hands image that is on live.
  https://franklin.moleculardevices.com/leadership
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/eac336d3-01fd-4523-a096-68ea708b7096)

9. This image looks a bit stretched, can we zoom it out a little?

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/efd5ebfa-7c12-49f4-9ca1-e2629ef81986)

**Comment by MeghnaTewari** [comment]
1. Increase the sub-menu section width to "1170px", It is "1140px" currently 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/511bfeb4-40bd-46d0-a044-ea0fb8a86218)

2. Enlarge the background circle 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/90950dad-02c0-4795-a9cc-5538650f9c40)

screenshot from live- 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/14f4bd21-fcf0-4e46-bf6e-3dbefe6db730)

**Comment by mhaack** [comment]
Fixed 1, 2, 3 in content

**Comment by duynguyen** [comment]
@MeghnaTewari could you please review the changes here? https://menu-style-fix--moleculardevices--hlxsites.hlx.page/

**Comment by MeghnaTewari** [comment]
1. Please remove one line space from here
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b204407f-1261-4e38-ba25-96e180eaacca)

2. Add one line space here and remove extra space above the read more button 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3f43386e-3d57-4b70-b846-a2b19f96619d)

3. Leadership sub-menu is empty
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e36c5ba7-5f3a-401d-882c-ebb7c08926af)

4. Wrap this word so it comes in the next line, it is overlapping on the image a little bit 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f1c0107b-794d-4131-a83c-21e5cea6719f)

5. Under blogs, remove the outline from read more, left align the text and add an arrow icon 

6. Also, I see a couple of new issues on this URL

Like this OIC button is short under applications and company

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ac3a033e-51fe-4146-b97e-c5c92cdc6e5c)
images are streching 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/79326542-dd11-46b3-9c95-e46b2ae36103)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5c2b7056-a0a9-4b62-91d5-6767364e9db4)

**Comment by MeghnaTewari** [comment]
I can see a very small alignment issue on my screen 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b19bf528-1f6e-4f55-bccd-99ada80d957e)

**Comment by duynguyen** [comment]
hmm.. they are aligned on my screen
<img width="460" alt="Screenshot 2023-07-24 at 17 54 48" src="https://github.com/hlxsites/moleculardevices/assets/601729/b9dd151b-6871-4676-89e8-0023b4d544a2">

**Comment by MeghnaTewari** [comment]
Issue with the resolution for smaller screens i guess

**Comment by duynguyen** [comment]
@MeghnaTewari either screen size or browser etc. given that's a very minor UI issue that's not re-produceable for all users, can we give it a check?

**Comment by MeghnaTewari** [comment]
Yes.
