### ISSUE TITLE
Fix Custom Organoid Expansion Service page issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#878]
https://franklin.moleculardevices.com/products/3d-biology/custom-organoid-expansion-service#overview

1. Speak to a specialist CTA missing in the banner 
2. Right side video on the Overview has a play icon missing.
3. Workflow image is missing under "Custom organoid expansion workflow"
4. **Drug Discovery and Development and Patient-derived organoids (Tumoroids)** topic cards missing in applications tab 
https://franklin.moleculardevices.com/products/3d-biology/custom-organoid-expansion-service#applications
5. Lab automation HCS and cellular imaging cards are missing in related products tab
https://franklin.moleculardevices.com/products/3d-biology/custom-organoid-expansion-service#related-products-services

**Comment by mhaack** [comment]
@MeghnaTewari on 1. "Speak to a specialist CTA missing in the banner" I see the C2A button?

![Screenshot 2023-07-10 at 15 23 28](https://github.com/hlxsites/moleculardevices/assets/2643450/440b3440-4933-490a-9d1e-b402afb5129e)
