### ISSUE TITLE
Wave content UI issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#879]
1. Footer UI distorted 
https://franklin.moleculardevices.com/products/additional-products/genepix-microarray-systems-scanners 

2. Add a little space here, and update the font size of the title to 60px, globally.
https://franklin.moleculardevices.com/products/assay-kits/cardiotox/earlytox-cardiotoxicity-kit
https://franklin.moleculardevices.com/applications/drug-discovery-and-development

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/64b56e95-dbcb-4166-852f-b1a5f2ac40e6)

3. Fix card dimensions and remove the Latest Resources section, not required for 2 resources.
https://franklin.moleculardevices.com/products/additional-products/threshold-immunoassay-system
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2866e143-53f1-4767-8b5b-9b34b1c5a083)

should be like this 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9cfb6276-aec2-4dce-8f92-c5570aa7d80c)

**Comment by MeghnaTewari** [comment]
@duynguyen Point number 2 is not done on the application pages. Please update the font size.
https://franklin.moleculardevices.com/applications/drug-discovery-and-development

**Comment by duynguyen** [comment]
@MeghnaTewari - just fixed it, could you please re-check?

**Comment by MeghnaTewari** [comment]
Looks good now. Thanks
