### ISSUE TITLE
[Products] Fix CTA + spacing issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#890]
1. Fix " Read press release , Visit Lab Automation View blog post"  CTA
https://franklin.moleculardevices.com/applications/organoid-innovation-center

2. Fix "Learn more about IN Carta" CTA and shift the Learn More CTA above the line separator 
https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-confocal-ht-ai
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3ee011e7-1fdf-4fa8-b2b7-cdeb65dfda6e)

3. Fix "Learn More View Modules" CTA, center align "View Options" CTA, center align "Cellular Image Gallery" , add 2 line separators for metaexpress section

https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-confocal
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/029aea80-62f6-4640-8e07-ed74d4d3f7c3)

5. Fix Download GxP eBook CTA
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-m-series-readers 

6. Remove Applications tab
https://franklin.moleculardevices.com/products/microplate-readers/washers/multiwash-microplate-washer#applications 

7. Remove applications tab
https://franklin.moleculardevices.com/products/microplate-readers/acquisition-and-analysis-software/softmax-pro-software#applications  

9. Reduce the font size of "Scalable, automated plate-based assay workcells" title 
https://franklin.moleculardevices.com/service-support/lab-automation-solutions/lab-automation-for-high-throughput-plate-based-assays

10. Add space above "Assure data integrity...." title
https://franklin.moleculardevices.com/products/gxp-compliance-solutions/spectratest-validation-plates

11. Add line separators 
https://franklin.moleculardevices.com/products/clone-screening/mammalian-screening/clonepix-2-mammalian-colony-picker
https://franklin.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/stratominer

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/309bf816-ffdc-47f8-b03b-3645de9db055)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d445bb42-75a8-4ada-8b21-3f18352bd0b7)

12. Remove the white background for "View Interactive Demo" CTA
 https://franklin.moleculardevices.com/products/axon-patch-clamp-system/acquisition-and-analysis-software/pclamp-software-suite

**Comment by mhaack** [comment]
Most of these are content issues:

1. fixed, for the press release quote we maybe can use the quote block as well, @duynguyen wdyt?
2. fixed
