### ISSUE TITLE
[Applications] UI issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#895]
1. Can we update the TOC section for some pages like it is on live? Grey background and bullets under the titles
https://franklin.moleculardevices.com/technology/luminescence
https://franklin.moleculardevices.com/technology/absorbance#overview
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/46b3f6b3-2501-4e79-9c17-37d5726cc9a9)

2. Fix "View ELISA protocol****Automate ELISA workflow" CTA
https://franklin.moleculardevices.com/applications/enzyme-linked-immunosorbent-assay-elisa

3. Center align "Latest Resources" globally.
 https://franklin.moleculardevices.com/technology/fluorescence 

4. Add space above the title and add line separator 
https://franklin.moleculardevices.com/technology/fluorescence-polarization
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fab826ea-da00-41ac-8005-413b70ff155f)

Remove
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/48b5b1b1-6d7a-486f-9a7d-63449a98c10a)

5. Fix UI of the table and TOC bullets should be below the paragraph
https://franklin.moleculardevices.com/technology/time-resolved-fluorescence-trf-tr-fret-htrf 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/31d39ca4-9abd-4ab2-83b8-9a88eab69340)
Screenshot from live
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fab03de1-5a24-4031-8c98-c3e5bd575333)

6. Topic cards missing 
https://franklin.moleculardevices.com/technology/western-blot 

7.  Topic card images should be consistent globally with the dimensions - 555*282
 https://franklin.moleculardevices.com/applications/cell-counting
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8fc1aa4f-5e67-433a-93ad-9862433c50ed)

8.  Add line separator 
https://franklin.moleculardevices.com/applications/cell-imaging/cell-painting
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/454ec6d0-f8b3-4f8b-a095-c41a26dc4473)

9. Fix "See detailed workflow" CTA , Add space above all the titles and unbold caption under the video
https://franklin.moleculardevices.com/applications/live-cell-imaging 

10. Remove the double arrow icon from all the cards, add space above "Neurite outgrowth applications..." title
https://franklin.moleculardevices.com/applications/neurite-outgrowth 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2f7d3bfc-7214-4af8-8a0f-30b453908a17)

11. Add line separator above "Featured assets to optimize your cell line.." title 
https://franklin.moleculardevices.com/applications/cell-line-development-workflow 

12. Fix "Learn more View video" CTA and add space above the titles
https://franklin.moleculardevices.com/applications/synthetic-biology 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/82b1f8cf-06b6-4390-ba56-d025bdd6b009)

13. "See detailed workflow" CTA missing and add arrow icons after "Watch Video"
https://franklin.moleculardevices.com/applications/3d-cell-models

**Comment by lydiapuric** [comment]
Content fixes were done for:
2) https://franklin.moleculardevices.com/applications/enzyme-linked-immunosorbent-assay-elisa

**Comment by lydiapuric** [comment]
@MeghnaTewari Regarding point 1, TOC
We agreed with @kapildhiman in the past that TOC subtitles / categories are not available to be generated dynamically with the TOC, so therefore these titles will and cannot not provided.
cc @mhaack

**Comment by MeghnaTewari** [comment]
okay, got it. Thanks

**Comment by lydiapuric** [comment]
@MeghnaTewari Could you please validate the changes, see also the URL where the changes are available in this issue. Thanks!

**Comment by MeghnaTewari** [comment]
@lydiapuric Please find my inline comments - 

Point 1 - Can we add a little space here, on the absorbance page? Also please left align all the titles for topic cards 
https://895-applications--moleculardevices--hlxsites.hlx.page/technology/absorbance
https://895-applications--moleculardevices--hlxsites.hlx.page/technology/luminescence
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/260f3be6-b0b9-4dec-b7d6-50a9c733fa58)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2919c7c7-1c45-4eed-bf36-e4440a2c55c8)

Point 3 - Looks good, I hope the Latest Resources text will be center aligned globally. 

Point 4 - Please remove this text 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/0a93cf99-b0f5-4008-837e-161031728506)
https://895-applications--moleculardevices--hlxsites.hlx.page/technology/fluorescence-polarization

Point 6 - Anchor links not working, please fix.
https://895-applications--moleculardevices--hlxsites.hlx.page/technology/western-blot
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/43907500-7117-46a7-8ba2-68b75715e349)

Point 7- Can you please align the topic card images? This change should be applied globally.
https://895-applications--moleculardevices--hlxsites.hlx.page/applications/cell-counting
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/181e4d66-5c98-4949-b912-c99056ee589c)

Point 13- Please add arrow icons after "Watch Video" and link "See detailed workflow" CTA to the workflow tab 
https://895-applications--moleculardevices--hlxsites.hlx.page/applications/3d-cell-models

**Comment by lydiapuric** [comment]
@MeghnaTewari Thanks for the first validation.
In the meantime, I could address the last issues - except point 7, see the comments below.
Could you please revalidate them?
 
Regarding point 7:
I cannot align topic card images without defining a global height for the headlines. This would introduce unnecessary empty spaces in the cards between the title and image because the headlines differ between the size of 1 and 3 lines. The reason is that these cards are generated and one card does not know the next card or the length of the headline.

**Comment by lydiapuric** [comment]
And another question @MeghnaTewari 
You asked me to unbold caption under the video in
https://895-applications--moleculardevices--hlxsites.hlx.page/applications/live-cell-imaging

Is this also a global change or an exceptional style for applications?

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari Thanks for the first validation. In the meantime, I could address the last issues - except point 7, see the comments below. Could you please revalidate them?
> 
> Regarding point 7: I cannot align topic card images without defining a global height for the headlines. This would introduce unnecessary empty spaces in the cards between the title and image because the headlines differ between the size of 1 and 3 lines. The reason is that these cards are generated and one card does not know the next card or the length of the headline.

@lydiapuric  Given that we have already defined a global height for the headlines on the live site, I believe it is appropriate to apply the same here. We have allocated space for two lines in case the title is longer, and the overall layout appears fine without any strange gaps.

Check this screenshot from live- 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/12f03883-fc7d-42b2-9930-c1d0996a0993)

**Comment by MeghnaTewari** [comment]
> And another question @MeghnaTewari You asked me to unbold caption under the video in https://895-applications--moleculardevices--hlxsites.hlx.page/applications/live-cell-imaging
> 
> Is this also a global change or an exceptional style for applications?

@lydiapuric On the live site, we use two quote styles: 
1. For products = Font size - 24px + Bold ( No italics )
Example ( https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers ) 

2. For applications = Font size - 14 px + italics 
Example ( https://www.moleculardevices.com/applications/live-cell-imaging )

Please update globally for products and apps.

**Comment by mhaack** [comment]
What would be the style for other pages? We agreed should have these kinds of things styled similar and have less exceptions in favor of a unified experience (@dev-rajneeshkumar was part of that discussion).

If we go with 1) for products, does the apply to all products? And can we use 2) for the rest (not only applications)?

**Comment by lydiapuric** [comment]
Thanks @mhaack regarding the question about the video caption. 

@MeghnaTewari Regarding the alignment of topic titles and image:

However, the space is not 2 lines when 2 1-liner titles are next to each other, so there is no empty space of 2 lines in general, see 
<img width="1140" alt="Screenshot 2023-07-18 at 13 47 09" src="https://github.com/hlxsites/moleculardevices/assets/3846840/b89a47f1-3b45-4d15-ad70-3cf7054e4dc1">

As said, we can't determine how long the next topic card's title is, as this list is dynamically generated.

**Comment by mhaack** [comment]
@lydiapuric then lets go with this ☝️ generic style as descripted above and only one overlay with `.product ....` .

**Comment by lydiapuric** [comment]
@MeghnaTewari The cation style is adjusted.

**Comment by lydiapuric** [comment]
Alignment of image for topic cards will be addressed with #931.

@MeghnaTewari The cards images to be aligned, what is the scope for this adjustment? Is this restricted to Related Application Topic Cards?

**Comment by lydiapuric** [comment]
@MeghnaTewari Could you please test the alignment of image for topic cards in
- https://931-topic-card--moleculardevices--hlxsites.hlx.page/technology/absorbance
- https://931-topic-card--moleculardevices--hlxsites.hlx.page/technology/luminescence

**Comment by MeghnaTewari** [comment]
@lydiapuric This looks good.
