### ISSUE TITLE
Make coveo tab section sticky

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#899]
https://franklin.moleculardevices.com/search-results#t=All&sort=relevancy

Screenshot from live
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a2408163-b44e-43fc-bd76-a847566265f7)

Also, remove extra space from here 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2f945c6a-e6fc-472f-80cd-6e6163f9bbf2)

**Comment by mhaack** [comment]
@MeghnaTewari please re-test extra spaces are removed and search tab is now sticky as well.
