### ISSUE TITLE
Implement "news" & "in the news" aka publication pages

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#9]
Both page types share the same layout and styles

- [x] use auto block to move image into section to have two column layout
- [x] short version of header/hero with only breadcrumb and title
- [x] both types use "Resource" templates with different categories

Sample Press Release: https://www.moleculardevices.com/newsroom/news/advanced-solutions-life-sciences-collaborate-to-develop-3d-biology-automation-technologies-for-drug-discovery
Sample "in the news": https://www.moleculardevices.com/newsroom/in-the-news/millions-in-fda-fines-and-thousands-of-warning-letters-how-gxp-compliance-software-can-help

**Comment by lydiapuric** [comment]
WIP in https://github.com/hlxsites/moleculardevices/tree/publication_page

Started creating template-specific styles
