### ISSUE TITLE
[TechDebt] Ensure links for "js-hydrated" pages open the right tab

### ISSUE THREAD

**Issue by alexcarol** [hlxsites/moleculardevices#929]
Example link: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers#fluorescence

In this case the example link opens the "Overview" tab, which is the default one (instead of "Applications"). This happens because the page has not been fully populated yet and the ID cannot be found.

Note: This behaviour couldn't arise in the original site because the user never sees a URL with an anchor, as clicking on the "fluorescence link" only causes the page to scroll, but doesn't alter the site url.

**Comment by mhaack** [comment]
Closing as defered, can be re-opend if needed later.
