### ISSUE TITLE
Fix media gallery issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#936]
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

Please fix these issues, globally.

1. Remove the scroll bar in the video gallery pop-up.

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f3a57f5c-e61e-46c0-b2ba-1090e17dcd41)

2. Once the carousel reaches the last slide, it should automatically cycle back to the first slide.

3. Move the arrow icon slightly upwards to center

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/bafb9ee1-9f76-4628-b7b1-d9c53412cac4)

**Comment by duynguyen** [comment]
@MeghnaTewari can you verify if all issues are fixed here? https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

**Comment by MeghnaTewari** [comment]
@duynguyen Issue number 1 and 2 are still reproducible to me 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/26d7274a-6eaf-4566-a0e5-db8025bc351e)

**Comment by duynguyen** [comment]
@MeghnaTewari sorry wrong link: https://936--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

**Comment by MeghnaTewari** [comment]
@duynguyen Other changes look good, but there is still an issue with the arrow icon. For some images/ videos, it is still not in the center. Can we do something about it? 

Example- https://936--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers#
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/384a09a4-da8e-403b-9ce7-c20489f1cb13)

https://936--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-pico#
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/89807b80-bf77-47b4-82fe-152b69b49e60)


Also, I have noticed images that are originally smaller, are extremely zoomed in here 

Example- https://936--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-pico#

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9e9b890b-77d3-47df-8b10-c3f3a2f01f47)
Screenshot from live 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/275a8943-e5f0-4790-a55b-f37dd1a44d17)

This image is cutting off from the bottom 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c8747e90-c6a8-4e70-bb85-066874e883e7)


Additionally, when you click the back arrow button from the 2nd slide, it takes you to the last slide instead of the first slide. 
https://936--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-pico#
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/38dfb70e-4a10-45b7-b46f-54a5deaac45d)

**Comment by duynguyen** [comment]
@MeghnaTewari could you please check again? I align all images to center of the page. Arrow buttons should be in fixed position so that you don't need to move mouse when clicking them.

**Comment by MeghnaTewari** [comment]
Looks great! Thanks.
