### ISSUE TITLE
UI issues on product pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#937]
1. Please reduce the size of these images. Also in the URL  it should be ".com" instead of the hyphen 
https://franklin.moleculardevices.com/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution-com

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b24ef79a-3680-48ff-a2eb-79d799b7f242)

2. Remove the line separator above "Assure data integrity.." 
https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers/spectramax-abs-plate-readers
https://franklin.moleculardevices.com/products/microplate-readers/acquisition-and-analysis-software/softmax-pro-software
https://franklin.moleculardevices.com/products/gxp-compliance-solutions/softmax-pro-gxp-software-installation-validation-services

3. Add a little space here
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/filtermax-f3-f5-readers

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fbc3b3d4-f071-4f7e-9954-c66d4c43c8e1)

4. Centre align "Cellular Image Gallery" text.  Add space above the disclaimer text and remove the letter "S" and remove the extra asterisks. 
https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-confocal-ht-ai 
https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-confocal

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/da6149c7-f191-4011-9db0-7667e3c5d7e8)

5. Fix the font size for this section- 
**Center align "Turnkey solutions for ..."  with font h2:36 px.  
"MetaXpress Application Modules"  h2: 24px blue color 
"Expedite image analysis and data...." h4:18px**
 https://franklin.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/metaxpress

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1add5977-888d-45ef-a148-2f01e4b575d0)

6. View Interactive Demo CTA is not working, and remove the cross button below. Add line separators here 
 https://franklin.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/cellreporterxpress

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b2cde129-3362-435a-b3d1-561ff768e116)

7. Add line separator 
https://franklin.moleculardevices.com/products/clone-screening/single-cell-isolation/dispencell-single-cell-dispenser

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ef662656-b25e-4671-a580-025a8d7a3060)

8. Remove Request pricing CTA from the banner 
https://franklin.moleculardevices.com/products/flipr-penta-high-throughput-cellular-screening-system

9. Empty resources
https://franklin.moleculardevices.com/service-support/lab-automation-solutions/lab-automation-for-high-content-screening#resources

10. Remove line separator 
https://franklin.moleculardevices.com/products/gxp-compliance-solutions/softmax-pro-gxp-software
https://franklin.moleculardevices.com/products/gxp-compliance-solutions/softmax-pro-gxp-software-installation-validation-services

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/152b5713-7192-4725-a1c1-2c9034d1d54c)

**Comment by duynguyen** [comment]
@MeghnaTewari @lydiapuric FYI - I moved point 11 to a new issue #943 as it would be easier with an embedded HTML.

**Comment by MeghnaTewari** [comment]
Ok, thanks.

**Comment by lydiapuric** [comment]
@MeghnaTewari 
When a user requests URL https://franklin.moleculardevices.com/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution.com, this user is redirected internally to https://franklin.moleculardevices.com/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution-com. A user will never see a 404.

**Comment by lydiapuric** [comment]
Fixes done (WIP):
1. Please reduce the size of these images
https://franklin.moleculardevices.com/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution.com

**Comment by MeghnaTewari** [comment]
@lydiapuric Can you pls provide the URL where I can verify the fixes?

**Comment by mhaack** [comment]
To add on this a . is not supported in Franklin as part of the document name.

**Comment by lydiapuric** [comment]
@MeghnaTewari If you see franklin.moleculardevices.com still in the validation link, it was only a content change necessary to fix the issue, no code changes.

**Comment by MeghnaTewari** [comment]
@lydiapuric All the issues are still reproducible to me. Sharing screenshots for some- 

The line separator is still there - 

https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers/spectramax-abs-plate-readers
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c50ace11-20da-4ec6-b7da-e984e8b7dcdd)

Space is not added

https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/filtermax-f3-f5-readers
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b00bca13-fbab-4163-99d5-750008d2b691)

Text is not center aligned 
https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-confocal-ht-ai
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/303f3e6a-8bdd-4fce-9009-caa70592b4b7)

**Comment by MeghnaTewari** [comment]
Some more minor UI issues I have identified- 

https://franklin.moleculardevices.com/products/gxp-compliance-solutions

1. Centre align all the h2 titles
2. Font looks different here 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fe9b8640-40da-4233-b475-b37efbe32ab8)

Live- 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/91b7a958-1bfe-41d2-ae81-7f650187d3bd)

3. Update font size to be 40px with blue color
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2c54151c-e5f2-422b-ba84-31d7b9361023)

4. Reduce font size to 24px 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/6b23fa39-a066-4d92-8b4b-bf9f37e8ed8b)

5. Align button parallelly 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/940c5d40-ba45-4f8f-b3c5-40dec95d0496)

**Comment by lydiapuric** [comment]
@MeghnaTewari Til now I was able to work on points 1 - 3,  see comments and URLs in https://github.com/hlxsites/moleculardevices/issues/937#issuecomment-1647675704
The other issues are not yet addressed!

**Comment by MeghnaTewari** [comment]
These changes look good.

**Comment by MeghnaTewari** [comment]
> 8. @MeghnaTewari Please clarify: Remove Request pricing CTA from the banner
>    The Request Pricing is on the original page on the banner too.
>    https://franklin.moleculardevices.com/products/flipr-penta-high-throughput-cellular-screening-system

The request pricing CTA should only be visible for US and EU regions. Currently, it is visible for all the regions.
 
For US and EU there should be these 2 CTA buttons 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9ebea180-83d2-4088-bcfa-2286eb11857d)


For all the other regions it should be this-

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d3982d77-8f02-4623-a6e7-1518c8d87274)

cc @mhaack

**Comment by MeghnaTewari** [comment]
> @MeghnaTewari All issues incl. new ones got addressed, please validate. See validation issues and URLs in [#937 (comment)](https://github.com/hlxsites/moleculardevices/issues/937#issuecomment-1647675704)

Verified, looks good.

**Comment by mhaack** [comment]
@lydiapuric @MeghnaTewari on the request pricing C2A, yes this should work this was implemented by @andreituicu.

**Comment by lydiapuric** [comment]
@mhaack I rechecked, and this is what I see:
When I am in with CH, IE or US, I see 3 buttons. (Tested with VPN, cleaning up local storage for 'ipstack:geolocation' and making sure I see the changed country code with `JSON.parse(localStorage.getItem('ipstack:geolocation')).country_code`)

<img width="706" alt="Screenshot 2023-07-26 at 11 34 46" src="https://github.com/hlxsites/moleculardevices/assets/3846840/3ac62e7c-304d-4a09-a50a-65a1d5ef0482">

I will create a separate issue to work on this.

**Comment by MeghnaTewari** [comment]
@mhaack  The Franklin site should follow the same as the live site as it is intentional to hide the 'download brochure' alternative CTA for US and EU regions. As for whether we should keep all three buttons for US and EU, I don't think I can make that decision.

**Comment by lydiapuric** [comment]
@MeghnaTewari Could you please verify the CTA buttons?
https://franklin.moleculardevices.com/products/flipr-penta-high-throughput-cellular-screening-system

**Comment by MeghnaTewari** [comment]
@lydiapuric Looking fine for other regions. But for US and EU I am still seeing the 'download brochure' CTA.

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/369df191-5276-4b14-849e-eba1fe8bca92)

**Comment by MeghnaTewari** [comment]
Also, the Request Pricing CTA should be orange and white on the hover. The second CTA should be white outlined with the same hover behavior ( This used to be correct on Franklin earlier ) 

Example from live - 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8dce31bf-d222-4309-a692-45a4efcec46f)

Both the CTAs are blue on Franklin- 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5e3fbe46-4518-4b4b-ae94-e52acc655025)

**Comment by lydiapuric** [comment]
@MeghnaTewari Thanks for the quick validation. I will address the mentioned issues.

**Comment by lydiapuric** [comment]
@MeghnaTewari Regarding CTA buttons and Pricing, can you please retest in https://937-pricing--moleculardevices--hlxsites.hlx.page/products/flipr-penta-high-throughput-cellular-screening-system

**Comment by lydiapuric** [comment]
@MeghnaTewari Thanks, so the pricing button is orange, but the non-EU primary button is blue. I missed that one, adjusting...

**Comment by MeghnaTewari** [comment]
Correct.

**Comment by lydiapuric** [comment]
@MeghnaTewari  Changes done, please retest.
https://937-pricing--moleculardevices--hlxsites.hlx.page/products/flipr-penta-high-throughput-cellular-screening-system

**Comment by MeghnaTewari** [comment]
Looks great! Thanks.
