### ISSUE TITLE
Product Finder issues

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#944]
https://franklin.moleculardevices.com/product-finder

- [x] 1. Bold text "Steps for Product Finder" 

- [x] 2. Checkboxes are nonclickable 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c2c35a7f-64da-4dbb-8bc6-9acd26507769)

- [x] 3. Apply highlight on hover behavior for all the cards 

**Example from live** - ![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d2023235-8c42-4937-918b-2132793797b0)

- [x] 4 "Features" dropdown is missing

**Screenshot from live** -  ![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a6627597-5233-472b-aef3-66c9838e3d98)

- [ ] 5. Order of the products should be the same as it is on live, for all the categories 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/cba2154f-53f3-4682-9354-c15e9d7564e3)

- [x] 6. Update Read more to "Request Quote" for all cards. Also on clicking the cards, the RFQ form is not opening. 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2d5612f2-433a-4547-b227-c5bc83f71316)

- [x] 7. For a single card, there should not be compare option

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ac0362f5-ea6c-4774-91b1-48c379f4e43a)

- [x] 8. Add an arrow icon after the product name, for all the cards
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7172b4b3-7f34-4d28-962c-37239310da6e)

- [x] 9. For some cards, the description is missing 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/9719f575-1811-4cef-aaea-f83783d4978e)

- [x] 10. Update dropdown style similar to live
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/cc4402ba-9471-4325-b259-9d4ad5bb717b)

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d53e2b94-3696-4eda-a99d-d9498aa0b6b1)

**Comment by mhaack** [comment]
@MeghnaTewari thanks for reporting, some comments on the findings:

1, 2, 3, 6, 7, 8: are style issues and can be fixed
4: this is left out by intention because: a) we don't have the data in the exports & b) there is no value in that as 95% it does not matter what you select products will be the same
5: what are the rules for the order, what is the sorting criteria?
9: content issue, can be fixed manually as well
10: this is by intention, also on other drop down boxed (like contact page). The old side is using a bootstrap extension, we decided to go with browser default drop-down as this is more internet standard and more accesible

**Comment by dev-rajneeshkumar** [comment]
@mhaack For #4 which data is missing can you please explain?

**Comment by mhaack** [comment]
Ok for 5#

**Comment by mhaack** [comment]
For 4.: the attributes have not been part of the export. We only saw this in the dev JSON URL’s you share on Slack. Let’s discuss in the sync how to handle these.

**Comment by dev-rajneeshkumar** [comment]
ok

**Comment by MeghnaTewari** [comment]
@jose-correia these 2 issues are still not fixed


> * [x]  5. Order of the products should be the same as it is on live, for all the categories
> 
> ![image](https://user-images.githubusercontent.com/138755144/255531889-cba2154f-53f3-4682-9354-c15e9d7564e3.png)
> 
> * [x]  6. Update Read more to "Request Quote" for all cards.
> 
> ![image](https://user-images.githubusercontent.com/138755144/255534444-2d5612f2-433a-4547-b227-c5bc83f71316.png)
> 

One new issue that I observed-

1. When you select some values from the dropdown within a category and click on "start over," and then revisit the same category, the filters remain preselected. Ideally, they should be cleared/reset instead.

2. Additionally, every time you click on "start over" and revisit the same category, an extra arrow icon is added in the cards. 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fb298ba3-7768-402a-9a99-a3787244e32f)



[product finder issue.webm](https://github.com/hlxsites/moleculardevices/assets/138755144/54afcd62-b6a9-4a3e-bdd1-b6a2ed8238ae)

cc @mhaack
