### ISSUE TITLE
Lab automation page issue

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#945]
This section should be in tabs 

https://franklin.moleculardevices.com/service-support/lab-automation-solutions/lab-automation-for-high-throughput-plate-based-assays

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/426c7d91-789f-4fbd-ade6-f5ff022fd95b)

Live -  ![image](https://github.com/hlxsites/moleculardevices/assets/138755144/03075865-9bca-4f4e-85bd-c7a3be6d00df)

https://franklin.moleculardevices.com/service-support/lab-automation-solutions/lab-automation-for-high-throughput-clone-screening

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ad2747a9-ee6a-49c5-9fce-f312e662d883)

Live- ![image](https://github.com/hlxsites/moleculardevices/assets/138755144/248ff434-f2d5-4992-85a1-298784e8132e)

**Comment by mhaack** [comment]
This is related to #347.
