### ISSUE TITLE
Minor UI issues on mobile 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#948]
1. Fix the featured applications cards width, globally
https://franklin.moleculardevices.com/products/3d-biology/custom-organoid-expansion-service

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/358ae6ec-3a37-48df-a97f-cb963d895616)

2. Remove the white line that is coming on several  pages
https://franklin.moleculardevices.com/applications/organoid-innovation-center
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/09c0fa41-8447-4625-b9e1-a93b496180d5)
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/da1b8b3c-d58f-4ccd-bd75-385e322876c9)

3. For category pages having video in the banner, keep the banner title on the left side and the video icon on the right, and the description above the title- 
https://franklin.moleculardevices.com/products/microplate-readers
https://franklin.moleculardevices.com/applications/organoid-innovation-center
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers
https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c51b755c-f896-48ce-9085-34c68cc4f130)

Example from live- 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/23b5712d-4bbd-4104-a134-6b5074701d34)

**Comment by duynguyen** [comment]
@MeghnaTewari re.
> For category pages having video in the banner, keep the banner title on the left side and the video icon on the right, and the description above the title

it doesn't look very nice like this on mobile because the title is cut too narrow. Isn't it better to stack them like other hero blocks? both for aesthetic and consistency.
(agree with you the divider should be removed, fixing it now)

**Comment by MeghnaTewari** [comment]
@duynguyen I agree with you, it does look better here but the length of the banner is increasing. Could you please reduce a small amount of space from above and below the play icon? That should make it look just fine.

**Comment by MeghnaTewari** [comment]
@duynguyen Looks good.
