### ISSUE TITLE
Distorted UI on few landing pages 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#949]
Distorted UI

https://franklin.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023
https://franklin.moleculardevices.com/en/assets/app-note/dd/img/high-throughput-modeling-inflammatory-bowel-disease-using-human-intestina-organoids

For this page content is not up to date, and several sections are missing like - 

https://franklin.moleculardevices.com/en/assets/promotion/dd/img/slas-eu-2023

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/24a06f05-1271-4fd6-a7b7-070b5c2ff53a)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f384a439-7757-42d4-bae6-ddfe173e2f40)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/5fcbbbd2-4949-41d4-bd9b-c74c226b0870)

**Comment by duynguyen** [comment]
Fixed:
https://franklin.moleculardevices.com/en/assets/scientific-posters/dd/img/slas-2023
https://franklin.moleculardevices.com/en/assets/app-note/dd/img/high-throughput-modeling-inflammatory-bowel-disease-using-human-intestina-organoids
