### ISSUE TITLE
Fix  minor issues on landing pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#950]
- [x] 1. Remove the vertical line and null

https://franklin.moleculardevices.com/en/assets/tutorials-videos/dd/img/using-differentiated-ipscs-to-build-ready-to-use-3d-models
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3905807c-8929-4363-989a-6c8a49960df7)

- [x] 2.  https://franklin.moleculardevices.com/en/assets/scientific-posters/dd/img/leveraging-automated-workflows-to-enable-complex-organoid-assays?page=thankyou&rfq=&subscribe=false

https://franklin.moleculardevices.com/en/assets/app-note/dd/img/understanding-organoid-morphology-using-3d-image-analysis?page=thankyou&rfq=&subscribe=false

  - [x] Subtitle on the banner should be white for all TY pages

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f9cc1c2d-f276-484b-a139-1f39e2ebe348)

  - [x] Fix View ModulesLearn more CTA

  - [x] Update font size of h3 title to 40 px 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4fae6aef-be4c-457e-8cfb-a36b0f265f3c)

  - [x] Images for these sections should be alternate, if the 1st one is on the left the next one should be on the right

Like this - 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/0d33c5eb-5d3d-4eca-94c6-60da11a6a500)

  - [x] "More Great Resources" should be in blue clr 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/670b366c-8ebe-4358-b54c-619273b95a08)

  - [x] Fix carousel to show arrow buttons 
  - [x] Images in the carousel should be of the same height 
  - [x] The resource type in the carousel ( Example Blog)  should be in green clr 
  - [x] Learn more should be a CTA button center aligned 
  - [x] Update the font size of the title in the carousel to 22 px and remove extra space above the title 

Ref URL - https://www.moleculardevices.com/en/assets/scientific-posters/dd/img/leveraging-automated-workflows-to-enable-complex-organoid-assays?page=thankyou&rfq=&subscribe=false

- [x] 3. Subtitle should be in white color for all the landing pages 

https://franklin.moleculardevices.com/en/assets/tutorials-videos/dd/img/scale-up-your-screening-3d-biology-for-therapeutic-drug-discovery
https://franklin.moleculardevices.com/en/assets/tutorials-videos/dd/img/3d-imaging-seminar-series

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b8321d7f-1a8a-4884-a6f6-60165c3f49a5)

**Comment by alexcarol** [comment]
@MeghnaTewari  What do you mean with add an arrow button? Do you mean the arrow buttons to scroll the carousel left and right?
![image](https://github.com/hlxsites/moleculardevices/assets/1713440/ff846501-1137-4f5b-b58e-9ad3b0f16d69)

**Comment by MeghnaTewari** [comment]
Yes I meant arrow buttons for the carousel to scroll

**Comment by alexcarol** [comment]
@MeghnaTewari here's the PR with the changes, in the description you'll see all the URLs to test the changes: https://github.com/hlxsites/moleculardevices/pull/967
(they're the ones that start with issue-950)

**Comment by MeghnaTewari** [comment]
@alexcarol 

1. Please reduce the size of learn more buttons a little bit.
2. Arrows are missing from the carousel 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/fc150241-5603-41ac-9d2d-083185c6d8e6)

3.  Update this block to be full width 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/309b5bd4-476e-4a03-8888-62764cb19af1)

**Comment by alexcarol** [comment]
> @alexcarol
> 
> 1. Please reduce the size of learn more buttons a little bit.
> 2. Arrows are missing from the carousel
>    ![image](https://user-images.githubusercontent.com/138755144/256736568-fc150241-5603-41ac-9d2d-083185c6d8e6.png)
> 3. Update this block to be full width
> 
> ![image](https://user-images.githubusercontent.com/138755144/256741606-309b5bd4-476e-4a03-8888-62764cb19af1.png)

I addressed issues 1 and 3. Regarding issue 2, at the moment we're showing the carousel arrows when the display is not big enough to show all the cards (like on mobile, or if the browser is less than 1200 px wide for this case with 3 items), I discussed it with the team and the consensus is that there's no value for the customer for the customer in showing the arrows (as they can already see all the images). If you feel that it would still be important to have it, let's discuss it in a new issue to avoid blocking the rest of the changes.

**Comment by alexcarol** [comment]
@MeghnaTewari I'll go ahead and merge the changes, but feel free to reply if I missed anything or create a new issue with any new changes required.

**Comment by MeghnaTewari** [comment]
Sure.
