### ISSUE TITLE
Fix 404 error on landing pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#952]
Promo pages-

- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/accelerate-your-cell-line-development-synthetic-biology-workflows (tabs)
- [x] https://franklin.moleculardevices.com/en/assets/promotion/br/discovery-starts-here
- [ ] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/slas-eu-2022
- [x] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/add-another-dimension-to-your-research
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/abm/tanvex/scale-up-biosimilar-pipelines-with-cell-line-development-automation
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/abm/inovio/scale-up-dna-medicines-with-plasmid-cloning-automation
- [x] https://franklin.moleculardevices.com/en/assets/promotion/br/real-discovery-starts-here
- [x] https://franklin.moleculardevices.com/en/assets/promotion/br/automated-elisa-workcells
- [x] https://franklin.moleculardevices.com/eu/assets/promotion/bpd/qpix-colony-picker
- [x] https://franklin.moleculardevices.com/en/assets/promotion/general/bioincubator-solutions
- [x] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/high-throughput-organoid-imaging-and-screening
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/accelerate-your-cell-line-development-synthetic-biology-workflows-de (tabs)
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/accelerate-your-cell-line-development-synthetic-biology-workflows-fr (tabs)
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/accelerate-your-cell-line-development-synthetic-biology-workflows-it (tabs)
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/accelerate-your-cell-line-development-synthetic-biology-workflows-es (tabs)
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/accelerate-your-cell-line-development-synthetic-biology-workflows-nl (tabs)
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/optimize-your-high-value-cell-lines-de
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/optimize-your-high-value-cell-lines-fr
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/optimize-your-high-value-cell-lines-it
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/optimize-your-high-value-cell-lines-es
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/optimize-your-high-value-cell-lines-nl 
- [x] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/streamline-your-path-to-drug-development (tabs)
- [ ] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/pegs-europe
- [x] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/high-throughput-organoid-imaging-analysis-and-screening
- [ ] https://franklin.moleculardevices.com/en/assets/promotion/dd/img/slas-2023   ( This page redirecting to the homepage currently but should not ) 
- [x] https://franklin.moleculardevices.com/en/assets/promotion/bpd/colony-picking-automation
- [ ] 

Other pages-

- [x] https://franklin.moleculardevices.com/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis 
- [x] https://franklin.moleculardevices.com/en/assets/scientific-posters/dd/img/bio-printed-3d-liver-model-and-high-content-imaging-for-assessment-of-compound-toxicity-effects
- [x] https://franklin.moleculardevices.com/en/assets/app-note/br/quantify-tnfa-secretion-thp-1-derived-macrophages-with-alphalisa-assay

**Comment by mhaack** [comment]
Closing as part of clean up as well.
