### ISSUE TITLE
Provide export of specifications for Product Finder

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#960]
Provide export list of specifications for Product Finder only

**Comment by dev-rajneeshkumar** [comment]
Hi 
@mhaack 
 here is the list of specifications specially assigned for Product finder only. Most of the values belong to Microplate reader category only and 3 other products has association for these. This should solve Features dropdown issue
[finder-specs-export-26-07-2023.xlsx](https://github.com/hlxsites/moleculardevices/files/12172398/finder-specs-export-26-07-2023.xlsx)
.

**Comment by dev-rajneeshkumar** [comment]
Hi @mhaack 
As discussed here is the next sheet for individual relation of specifications with each product in product finder.
[finder-specifications-checklist-26-07-2023.xlsx](https://github.com/hlxsites/moleculardevices/files/12175848/finder-specifications-checklist-26-07-2023.xlsx)

**Comment by mhaack** [comment]
Thinks this works
