### ISSUE TITLE
"Undefined" text on citations tab on few product pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#977]
On clicking "view more", undefined text is coming on product pages under the citations tab

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2292ea83-ade2-42be-89bb-9093cac4a70c)

Few example URLs - 

https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers#citations
https://franklin.moleculardevices.com/products/microplate-readers/fluorescent-readers/gemini-em-xps-readers#citations
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers#citations

Also, remove the asterisk after " click here" and the external icon should be added for the link

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/76534aa8-847f-4723-b4e3-73e16766afc7)

Example from live- 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3c95c0a2-145e-4e60-9d6e-7c09de17dca2)

**Comment by MeghnaTewari** [comment]
@duynguyen This page looks good.

checked another page and found the asterisks.
https://977--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-pico#citations
https://977--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-nano#citations
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3ce85704-06e5-4e39-9663-c303dda34a2c)

**Comment by duynguyen** [comment]
@MeghnaTewari thanks you're quick 🙂 
I was updating the content for all citations to to remove the asterisks. Also added the open new tab behavior.
