### ISSUE TITLE
Breadcrumbs missing on newsroom pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#978]
Breadcrumbs missing on news articles, PR, and events pages 

https://franklin.moleculardevices.com/newsroom/in-the-news/cell-cultured-meat-where-are-we-now
https://franklin.moleculardevices.com/newsroom/news/society-for-laboratory-automation-and-screening-2023-international-conference-and-exhibition
https://franklin.moleculardevices.com/events/labdays-aarhus-2023

For events, add to calendar is missing 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/354da026-1353-4d03-9cf7-06db46819f2b)

Add character limit on the In The News page 

https://franklin.moleculardevices.com/newsroom/in-the-news
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/2dfac507-41d4-4cf8-9d2e-3cd1dfa3ec1a)

**Comment by mhaack** [comment]
@MeghnaTewari the missing add to calendar button I remember we agreed to don't implement that one as is it not used. cc @dev-rajneeshkumar @kapildhiman @lydiapuric
