### ISSUE TITLE
UI issues on product and application pages 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#979]
- [x] 1. Remove the applications tab 

https://franklin.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/in-carta-image-analysis-software#overview
https://franklin.moleculardevices.com/products/cellular-imaging-systems/acquisition-and-analysis-software/cellreporterxpress#applications

- [x] 2. Applications tab is empty and the content of the application is showing in the Options tab

https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-4#applications

- [x] 3.  Align icons with the title and add line separators

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4ce9e466-7cad-4eb6-b9e4-046a022f9dcb)

The text should be full width 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3cb4e63e-e8b0-434e-85ed-ffb1611466a3)

- [x] 4. column ratio should be 1:2, it is 1:1 currently 

https://franklin.moleculardevices.com/applications/coronavirus-research/vaccine-development
https://www.moleculardevices.com/applications/coronavirus-research/covid19-company-update
https://franklin.moleculardevices.com/applications/coronavirus-research
https://franklin.moleculardevices.com/applications/3d-cell-models

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/bea9bae2-2aa1-4a20-822a-aed1d48edb68)

- [ ] #1004

https://franklin.moleculardevices.com/technology/time-resolved-fluorescence-trf-tr-fret-htrf#overview

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7fe5726a-1dab-49f9-a8c0-7f7993bc5b18)

- [x] 6. This section should be 2 columns, image, and caption on the right and text on the left 

 https://franklin.moleculardevices.com/applications/monoclonality

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/64acd2db-bf41-4436-9a56-5332f3a9613b)

- [x] 7. Content is extending on all tabs

https://franklin.moleculardevices.com/service-support/lab-automation-solutions/lab-automation-for-high-throughput-clone-screening

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c4d60e17-e733-47fe-a466-086fb6b90bc0)

- [x] 8. Add space

https://franklin.moleculardevices.com/service-support/lab-automation-solutions

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/0a4422c1-6809-4b0e-8d03-5ddb184dbd7f)

- [x] 9. Remove extra space  

https://franklin.moleculardevices.com/service-support/lab-automation-solutions/lab-automation-for-high-throughput-plate-based-assays
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e9363fe5-cdb1-4556-b3e7-dadf66c9071f)

**Comment by MeghnaTewari** [comment]
Another UI issue on the blog page 

Please fix the CTA buttons 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1149476b-7701-4980-9dce-6b48feb76334)

Increase width for this section

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/c4840ae4-5b15-4421-997c-9b7bea3ea294)

SS from live

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/7f7d2816-f8fc-44ff-a76b-c3891d1b2027)

**Comment by mhaack** [comment]
@MeghnaTewari I move the blog issues to #1001

**Comment by alexcarol** [comment]
@MeghnaTewari could you clarify which page does  "3. Align icons with the title and add line separators" refer to?

**Comment by MeghnaTewari** [comment]
@alexcarol  here is the URL

https://franklin.moleculardevices.com/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-confocal#options

**Comment by MeghnaTewari** [comment]
@alexcarol Few more minor issues I have observed for this page 

https://issue-979--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-micro-confocal#options

1. Can you please make the content full-width and images a bit smaller?
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b1266a03-50e7-42c3-96bd-65a66fd17f23)

2. center align both the captions 
add some space above the disclaimer text 
Remove extra asterisks from the disclaimer text 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/12e2de55-0d99-4faf-a9ae-90beb3a382bb)

3.  Add space above the "Standard hardware options" title 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4fd5adc6-e8c2-4546-a77f-db711926cc13)

4. Left-align the entire section "Customization options" and update the title to be 36px
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/901c9e74-7e24-4511-804c-5f25ed72e653)

5. Include this text in the sentence above - i.e. streaming at >100 frames per second.
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/de4a96cf-3244-441f-b21b-a67589cee69c)

**Comment by MeghnaTewari** [comment]
@alexcarol Thanks, validated all of them, and looks fine. 

Just one more thing, the spacing here now is too less, please add one line of space and that's all. 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/6ab21b75-7bee-4e13-a0f4-4045dbc56a5d)
