### ISSUE TITLE
External icon is missing 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#981]
We are noticing that external icon link is not appearing on Franklin for all  the pages. We have considered all links as external excluding below domains/subdomains and classes
domains:  ([moleculardevices.com](http://moleculardevices.com/))|([molecular-devices.myshopify.com](http://molecular-devices.myshopify.com/))|([moldev.com](http://moldev.com/))|([go.pardot.com](http://go.pardot.com/))|([pi.pardot.com](http://pi.pardot.com/))|(drift.me)
classes: .button-wrap,.socialLinks, .addtoany_list, .social-connect

**Comment by andreituicu** [comment]
@MeghnaTewari do you have a few examples where the icon is added? just want to make sure I have some good test cases to try out.

**Comment by andreituicu** [comment]
@MeghnaTewari sorry, I meant examples where the icon is present on the original website, but missing on the Franklin version.

**Comment by duynguyen** [comment]
@MeghnaTewari external icons in citations tab on product pages will be fixed in #977

**Comment by MeghnaTewari** [comment]
@andreituicu here are a few examples from live

https://www.moleculardevices.com/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers

https://www.moleculardevices.com/newsroom/news/society-for-laboratory-automation-and-screening-2023-international-conference-and-exhibition

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/6f4a01a9-780f-407a-9a77-9aace0f25f9d)

https://www.moleculardevices.com/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution.com

https://www.moleculardevices.com/en/assets/customer-breakthrough/dd/cns/york-university

**Comment by MeghnaTewari** [comment]
@duynguyen @andreituicu external links should always open in a new tab.

**Comment by duynguyen** [comment]
ok extended PR #989 to fix external links everywhere.

**Comment by duynguyen** [comment]
@MeghnaTewari some example pages for the fix:
https://977--moleculardevices--hlxsites.hlx.page/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers
https://977--moleculardevices--hlxsites.hlx.page/newsroom/news/society-for-laboratory-automation-and-screening-2023-international-conference-and-exhibition
https://977--moleculardevices--hlxsites.hlx.page/products/3d-biology/3d-bioprinting-bab400-bioprinter-automation-solution-com
https://977--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/cns/york-university

**Comment by MeghnaTewari** [comment]
@duynguyen can you please reduce the size of the icon and remove a little space between the icon and the text? 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/8bbe54c7-d38a-45c1-921e-2770f663bbb2)

screenshot from live 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a9398603-dda7-4d71-a205-5e30cd28d614)
