### ISSUE TITLE
Table style for blogs

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#982]
https://franklin.moleculardevices.com/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers
https://franklin.moleculardevices.com/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-softmax-pro-software

For both the pages

1. Increase table width as per the live site 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/cd40fe4e-d684-4df5-b36e-596dc6bd6abf)

2. Left align the content for all the columns
3. The pdf link added on the image should open in a new tab

**Comment by mhaack** [comment]
Moved the PDF link topic to #983
