### ISSUE TITLE
Fix microplate reader page issues 

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#987]
https://franklin.moleculardevices.com/products/microplate-readers

- [x]  Update this text  to - Our SpectraMax microplate readers and SoftMax Pro software

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ab87f963-48a5-466a-92b6-3a16ff222c77)

- [x] "Compare plate readers" CTA should anchor the link to "Explore our SpectraMax series of microplate readers" section

- [x] Update "GxP Solutions" CTA to read " GxP compliance"

- [x] For "Lab Automation" CTA, lowercase the a in automation 

- [x] Update  "Ultimate Guide to Microplate Reader Solutions" title color to  white 
- [x] reduce the image size and add flipping book link 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/486798b0-b924-4a9b-8d95-ad7d820f1c70)

- [x] Fix the spelling of webinar and update the link on "View complementary webminar"  CTA  to https://franklin.moleculardevices.com/en/assets/tutorials-videos/br/critical-considerations-for-choosing-right-microplate-reader

- [x]  Remove the vertical line and null from the banner 

https://franklin.moleculardevices.com/en/assets/tutorials-videos/br/critical-considerations-for-choosing-right-microplate-reader

- [x] Remove the white space below the carousel
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/d388d7da-1c0d-4561-ae30-98bb0e6c28ec)

- [x] Add some space in these places 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ca1a1343-5f12-4823-84ee-cf3d16426c59)

- [x] center align the title text
- [x] fix the image size for cards
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/cc6ec9db-5e55-4c95-a28e-e9f8bb27fb14)

**Comment by MeghnaTewari** [comment]
> * [x]  Update "GxP Solutions" CTA to read " GxP compliance"

@alexcarol Please lower case c in compliance

**Comment by alexcarol** [comment]
@MeghnaTewari here are the text URLs, could you check that it works as intended?
https://issue-987--moleculardevices--hlxsites.hlx.page/products/microplate-readers
https://issue-987--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/br/critical-considerations-for-choosing-right-microplate-reader

**Comment by MeghnaTewari** [comment]
@alexcarol  Please fix 

1.  Flipping book should open in the popup not in a new tab 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/336180f1-c236-4fb7-8016-0c78ba629705)

2. Buttons are not working
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e72b427c-5650-4af4-a270-ae11ce20ef0e)

3. Add some space 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/792b8422-ee67-4ce8-9a3c-fff3b1485bcf)

4.  Left align bullets and CTA
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a4b0614e-242a-4a8a-ba09-1670e3e09acd)

5. Reduce image size a little bit, it looks blur 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/01647633-4c0e-4d84-aaf5-b2f900a765ed)

6. Add little space 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1458b9c2-757c-4fa0-8308-f0d5383c63e2)

**Comment by alexcarol** [comment]
> 1. Flipping book should open in the popup not in a new tab
>    ![image](https://user-images.githubusercontent.com/138755144/257841197-336180f1-c236-4fb7-8016-0c78ba629705.png)
@MeghnaTewari  Is that a general behaviour across all flipbooks or only on this page?

**Comment by MeghnaTewari** [comment]
@alexcarol  From what I recall, this seems to be the first page where we've added a flipping book. For the time being, it should only be applied to this page. Once I crosscheck more pages, I'll get back to you on this.

**Comment by alexcarol** [comment]
> @alexcarol From what I recall, this seems to be the first page where we've added a flipping book. For the time being, it should only be applied to this page. Once I crosscheck more pages, I'll get back to you on this.

Found them: https://main--moleculardevices--hlxsites.hlx.page/en/assets/brochures/dd/img/a-life-sciences-company, https://main--moleculardevices--hlxsites.hlx.page/en/assets/brochures/dd/img/3d-biology-drug-discovery-paradigm

It looks like in both cases they are embedded in the page, so it looks like an exceptional behaviour, I'll see what I can do about it.

**Comment by alexcarol** [comment]
@MeghnaTewari i've addressed most issues, i'll address the flippingbook and buttons not working in a separate PR, could you check everything else works as expected?

**Comment by MeghnaTewari** [comment]
@alexcarol Everything else looks good.
